using Content.Shared._KS14.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class Ks14Tab : Control
{
    public Ks14Tab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionCheckBox(KsCCVars.SlurFilterEnabled, SlurFilterEnabled);

        // KS14: DeepL chat translation language. The stored value is the DeepL target code (empty = off).
        var languages = new (string Code, string Loc)[]
        {
            ("", "ks-ui-options-translate-language-off"),
            ("EN-US", "ks-ui-options-translate-language-en-us"),
            ("EN-GB", "ks-ui-options-translate-language-en-gb"),
            ("DE", "ks-ui-options-translate-language-de"),
            ("RU", "ks-ui-options-translate-language-ru"),
            ("FR", "ks-ui-options-translate-language-fr"),
            ("ES", "ks-ui-options-translate-language-es"),
            ("PT-BR", "ks-ui-options-translate-language-pt-br"),
            ("IT", "ks-ui-options-translate-language-it"),
            ("PL", "ks-ui-options-translate-language-pl"),
            ("NL", "ks-ui-options-translate-language-nl"),
            ("UK", "ks-ui-options-translate-language-uk"),
            ("JA", "ks-ui-options-translate-language-ja"),
            ("KO", "ks-ui-options-translate-language-ko"),
            ("ZH-HANS", "ks-ui-options-translate-language-zh-hans"),
        };
        var languageEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var (code, loc) in languages)
            languageEntries.Add(new OptionDropDownCVar<string>.ValueOption(code, Loc.GetString(loc)));
        Control.AddOptionDropDown(KsCCVars.TranslateLanguage, DropDownTranslateLanguage, languageEntries);

        Control.Initialize();
    }
}
