using Content.Client._KS14.Voice; // KS14
using Content.Shared._KS14.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration; // KS14
using Robust.Shared.Localization;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class Ks14Tab : Control
{
    [Dependency] private IConfigurationManager _configurationManager = default!; // KS14
    [Dependency] private IUserInterfaceManager _userInterfaceManager = default!; // KS14

    // KS14 start: voice chat options, kept so they can follow cvar changes made while the tab is open
    private readonly List<BaseOption> _voiceOptions = [];
    private readonly List<Action> _voiceUnsubscribers = [];
    // KS14 end

    public Ks14Tab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionCheckBox(KsCCVars.SlurFilterEnabled, SlurFilterEnabled);
        Control.AddOptionCheckBox(KsCCVars.ActionFoldersEnabled, ActionFoldersEnabled);
        Control.AddOptionCheckBox(KsCCVars.ActionLayoutPersistenceEnabled, ActionLayoutPersistenceEnabled);

        // KS14: DeepL chat translation language. The stored value is the DeepL target code (empty = off).
        var languages = new (string Code, string Loc)[]
        {
            ("", "ks-ui-options-translate-language-off"),
            ("EN-US", "ks-ui-options-translate-language-en-us"),
            ("EN-GB", "ks-ui-options-translate-language-en-gb"),
            ("DE", "ks-ui-options-translate-language-de"),
            ("RU", "ks-ui-options-translate-language-ru"),
            ("FR", "ks-ui-options-translate-language-fr"),
            ("ES", "ks-ui-options-translate-language-es"),
            ("PT-BR", "ks-ui-options-translate-language-pt-br"),
            ("IT", "ks-ui-options-translate-language-it"),
            ("PL", "ks-ui-options-translate-language-pl"),
            ("NL", "ks-ui-options-translate-language-nl"),
            ("UK", "ks-ui-options-translate-language-uk"),
            ("JA", "ks-ui-options-translate-language-ja"),
            ("KO", "ks-ui-options-translate-language-ko"),
            ("ZH-HANS", "ks-ui-options-translate-language-zh-hans"),
        };
        var languageEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var (code, loc) in languages)
            languageEntries.Add(new OptionDropDownCVar<string>.ValueOption(code, Loc.GetString(loc)));
        Control.AddOptionDropDown(KsCCVars.TranslateLanguage, DropDownTranslateLanguage, languageEntries);

        // KS14 start: voice chat
        _voiceOptions.Add(Control.AddOptionCheckBox(KsCCVars.VoiceHearEnabled, VoiceHearEnabled));
        _voiceOptions.Add(Control.AddOptionCheckBox(KsCCVars.VoiceActivation, VoiceActivation));
        _voiceOptions.Add(Control.AddOptionPercentSlider(KsCCVars.VoiceVolume, SliderVoiceVolume, min: 0f, max: 2f));
        _voiceOptions.Add(Control.AddOptionSlider(KsCCVars.VoiceJitterBufferMs, SliderVoiceJitter, min: 60, max: 400));
        VoiceOpenButton.OnPressed += _ => _userInterfaceManager.GetUIController<KsVoiceUIController>().OpenWindow();
        // KS14 end

        Control.Initialize();
    }

    // KS14 start: voice settings only make sense while the server has voice chat enabled, and the options menu only
    //      reads cvars when it opens. So while this tab is on screen, follow the server's switch and any change to
    //      the voice cvars made elsewhere (the console, say). Subscribed only while in the tree: the
    //      configuration manager outlives every options window, and would otherwise keep each one alive.
    protected override void EnteredTree()
    {
        base.EnteredTree();

        VoiceSection.Visible = _configurationManager.GetCVar(KsCCVars.VoiceEnabled);
        WatchCVar(KsCCVars.VoiceEnabled, enabled => VoiceSection.Visible = enabled);
        VoiceActivation.Visible = _configurationManager.GetCVar(KsCCVars.VoiceActivationAllowed);
        WatchCVar(KsCCVars.VoiceActivationAllowed, allowed => VoiceActivation.Visible = allowed);
        WatchCVar<bool>(KsCCVars.VoiceHearEnabled, _ => ReloadVoiceOptions());
        WatchCVar<bool>(KsCCVars.VoiceActivation, _ => ReloadVoiceOptions());
        WatchCVar<float>(KsCCVars.VoiceVolume, _ => ReloadVoiceOptions());
        WatchCVar<int>(KsCCVars.VoiceJitterBufferMs, _ => ReloadVoiceOptions());
    }

    protected override void ExitedTree()
    {
        foreach (var unsubscribe in _voiceUnsubscribers)
            unsubscribe();

        _voiceUnsubscribers.Clear();
        base.ExitedTree();
    }

    private void WatchCVar<T>(CVarDef<T> cVar, Action<T> onChanged) where T : notnull
    {
        _configurationManager.OnValueChanged(cVar, onChanged);
        _voiceUnsubscribers.Add(() => _configurationManager.UnsubValueChanged(cVar, onChanged));
    }

    private void ReloadVoiceOptions()
    {
        foreach (var option in _voiceOptions)
            option.LoadValue();

        Control.ValueChanged();
    }
    // KS14 end
}
