// SPDX-FileCopyrightText: 2022 Flipp Syder
// SPDX-FileCopyrightText: 2023 metalgearsloth
// SPDX-FileCopyrightText: 2024 Piras314
// SPDX-FileCopyrightText: 2025 Aiden
// SPDX-FileCopyrightText: 2025 Hagvan
// SPDX-FileCopyrightText: 2025 John Willis
// SPDX-FileCopyrightText: 2025 Tayrtahn
// SPDX-FileCopyrightText: 2025 eoineoineoin
//
// SPDX-License-Identifier: MIT

using Content.Client.Pinpointer.UI; // Goobstation
using Content.Client.Resources;
<<<<<<< HEAD
using Content.Client.UserInterface.Controls; // Goobstation
=======
using Content.Client.Viewport;
using Content.Shared.DeviceNetwork;
using Content.Shared.SurveillanceCamera;
using Content.Shared.SurveillanceCamera.Components;
>>>>>>> upstream/master
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects; // Goobstation
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Map; // Goobstation
using Robust.Shared.Prototypes;
using Robust.Shared.Utility; // Goobstation

namespace Content.Client.SurveillanceCamera.UI;

[GenerateTypedNameReferences]
public sealed partial class SurveillanceCameraMonitorWindow : FancyWindow // Goobstation
{
    private static readonly ProtoId<ShaderPrototype> CameraStaticShader = "CameraStatic";

    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
<<<<<<< HEAD
    [Dependency] private IEntityManager _entManager = default!; // Goobstation

    public event Action<string>? CameraSelected;
=======
    [Dependency] private readonly IEntityManager _entityManager = default!;

    /// <summary>
    /// Triggered when a camera is selected.
    /// First parameter contains the camera's address.
    /// Second optional parameter contains a subnet - if possible, the monitor will switch to this subnet.
    /// </summary>
    public event Action<string, string?>? CameraSelected;

    public event Action<string>? SubnetOpened;
>>>>>>> upstream/master
    public event Action? CameraRefresh;
    public event Action? SubnetRefresh;
    public event Action? CameraSwitchTimer;
    public event Action? CameraDisconnect;

    private string _currentAddress = string.Empty;
    private bool _isSwitching;
    private readonly FixedEye _defaultEye = new();
<<<<<<< HEAD
    private readonly SpriteSystem _spriteSystem; // Goobstation
    private readonly Dictionary<NetEntity, string> _reverseCameras = new(); // Goobstation
    private readonly Dictionary<string, string> _resolveCameraName = new(); // Goobstation
    private Texture? _blipTexture; // Goobstation
=======
    private readonly Dictionary<string, int> _subnetMap = new();
    private EntityUid? _mapUid;

    private string? SelectedSubnet
    {
        get
        {
            if (SubnetSelector.ItemCount == 0
                || SubnetSelector.SelectedMetadata == null)
            {
                return null;
            }

            return (string) SubnetSelector.SelectedMetadata;
        }
    }
>>>>>>> upstream/master

    public SurveillanceCameraMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entManager.System<SpriteSystem>(); // Goobstation

        // This could be done better. I don't want to deal with stylesheets at the moment.
        var texture = _resourceCache.GetTexture("/Textures/Interface/Nano/square_black.png");
        var shader = _prototypeManager.Index(CameraStaticShader).Instance().Duplicate();

        CameraView.ViewportSize = new Vector2i(770, 770);
        CameraView.Eye = _defaultEye; // sure
        CameraViewBackground.Stretch = TextureRect.StretchMode.Scale;
        CameraViewBackground.Texture = texture;
        CameraViewBackground.ShaderOverride = shader;

        // Set trackable entity selected action - Camera Selection
        NavMap.TrackedEntitySelectedAction += SetTrackedEntityFromNavMap; // Goobstation

<<<<<<< HEAD
        SubnetRefreshButton.OnPressed += _ => SubnetRefresh!();
        CameraRefreshButton.OnPressed += _ => CameraRefresh!();
        CameraDisconnectButton.OnPressed += _ => CameraDisconnect!();
=======
        SubnetSelector.OnItemSelected += args =>
        {
            // piss
            SubnetOpened?.Invoke((string) args.Button.GetItemMetadata(args.Id)!);
        };
        SubnetRefreshButton.OnPressed += _ => SubnetRefresh?.Invoke();
        SubnetRefreshButtonMap.OnPressed += _ => SubnetRefresh?.Invoke();
        CameraRefreshButton.OnPressed += _ => CameraRefresh?.Invoke();
        CameraDisconnectButton.OnPressed += _ => CameraDisconnect?.Invoke();

        CameraMap.EnableCameraSelection = true;
        CameraMap.CameraSelected += OnCameraMapSelected;
>>>>>>> upstream/master
    }

    // Goobstation start
    // need to translate entity to string and then call the same method the list does
    private void SetTrackedEntityFromNavMap(NetEntity? netEntity)
    {
        if (!netEntity.HasValue)
            return;

        CameraSelected!(_reverseCameras[netEntity.Value]);
    }

    public EntityUid Entity;

    // Needed for NavMap to initialize and draw the grid
    public void SetEntity(EntityUid uid)
    {
        Entity = uid;

        // Pass owner to nav map
        NavMap.Owner = uid;

        // Set nav map grid uid
        var stationName = Loc.GetString("surveillance-camera-monitor-ui-unknown-location");

        if (_entManager.TryGetComponent<TransformComponent>(uid, out var xform))
        {
            NavMap.MapUid = xform.GridUid;

            // Assign station name
            if (_entManager.TryGetComponent<MetaDataComponent>(xform.GridUid, out var stationMetaData))
                stationName = stationMetaData.EntityName;

            var msg = new FormattedMessage();
            msg.AddMarkupOrThrow(Loc.GetString("surveillance-camera-monitor-ui-station-name", ("stationName", stationName)));

            StationName.SetMessage(msg);
            _blipTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));
        }

        else
        {
            StationName.SetMessage(stationName);
            NavMap.Visible = false;
        }
    }

    // Add a particular camera
    private void AddTrackedEntityToNavMap(NetEntity ent, NetCoordinates coordinates, bool selected, bool mobile)
    {
        var coords = _entManager.GetCoordinates(coordinates);
        var texture = new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_square.png"));
        var color = selected ? Color.Green : Color.Red;
        var blink = false;
        var modulator = Color.White;

        if (mobile)
            color = selected ? Color.Green : Color.Orange;
        else
            color = selected ? Color.Green : Color.Red;

        var blip = new NavMapBlip(coords, _spriteSystem.Frame0(texture), color * modulator, blink);
        NavMap.TrackedEntities[ent] = blip;
    }
    // Goobstation End

    // The UI class should get the eye from the entity, and then
    // pass it here so that the UI can change its view.
    public void UpdateState(IEye? eye, string activeAddress, Dictionary<string, (string, (NetEntity, NetCoordinates))> cameras, Dictionary<string, (string, (NetEntity, NetCoordinates))> mobileCameras, EntityUid monitor, EntityCoordinates? monitorCoords) // Goobstation
    {
        CameraMap.SetActiveCameraAddress(activeAddress);
        CameraMap.SetAvailableSubnets(subnets);

        _currentAddress = activeAddress;
        SetCameraView(eye);
        // Goobstation start
        _reverseCameras.Clear();
        _resolveCameraName.Clear();
        NavMap.TrackedEntities.Clear();
        foreach (var (camera, (name, (ent, coordinates))) in cameras)
        {
            _reverseCameras[ent] = camera;
            _resolveCameraName[camera] = name;
            AddTrackedEntityToNavMap(ent, coordinates, camera.Equals(_currentAddress) ? true : false, false);
        }
        foreach (var (camera, (name, (ent, coordinates))) in mobileCameras)
        {
            _reverseCameras[ent] = camera;
            _resolveCameraName[camera] = name;
            AddTrackedEntityToNavMap(ent, coordinates, camera.Equals(_currentAddress) ? true : false, true);
        }
        // Show monitor on nav map
        if (monitorCoords != null && _blipTexture != null)
            NavMap.TrackedEntities[_entManager.GetNetEntity(monitor)] = new NavMapBlip(monitorCoords.Value, _blipTexture, Color.Cyan, true, false);
        // Goobstation end
    }


    private void SetCameraView(IEye? eye)
    {
        var eyeChanged = eye != CameraView.Eye || CameraView.Eye == null;
        CameraView.Eye = eye ?? _defaultEye;
        CameraView.Visible = !eyeChanged && !_isSwitching;
        CameraDisconnectButton.Disabled = eye == null;

        if (eye != null)
        {
            if (!eyeChanged)
            {
                return;
            }

            _isSwitching = true;
            CameraViewBackground.Visible = true;
            // Goobstation start
            if (_resolveCameraName.TryGetValue(_currentAddress, out var name))
                CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                    ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connecting")),
                    ("address", _currentAddress)) + " - " + name;
            else
                CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                    ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connecting")),
                    ("address", _currentAddress));
            // Goobstation end
            CameraSwitchTimer!();
        }
        else
        {
            CameraViewBackground.Visible = true;
            CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status-disconnected");
        }
    }

    public void OnSwitchTimerComplete()
    {
        _isSwitching = false;
        CameraView.Visible = CameraView.Eye != _defaultEye;
        CameraViewBackground.Visible = CameraView.Eye == _defaultEye;
        // Goobstation start
        if (_resolveCameraName.TryGetValue(_currentAddress, out var name))
            CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                            ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connected")),
                            ("address", _currentAddress)) + " - " + name;
        else
            CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                            ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connected")),
                            ("address", _currentAddress));
<<<<<<< HEAD
        // Goobstation end
=======
    }

    private int AddSubnet(string subnet)
    {
        var name = subnet;
        if (_prototypeManager.TryIndex<DeviceFrequencyPrototype>(subnet, out var frequency))
        {
            name = Loc.GetString(frequency.Name ?? subnet);
        }

        SubnetSelector.AddItem(name);
        SubnetSelector.SetItemMetadata(SubnetSelector.ItemCount - 1, subnet);

        return SubnetSelector.ItemCount - 1;
    }

    private void OnSubnetListSelect(ItemList.ItemListSelectedEventArgs args)
    {
        CameraSelected!((string) SubnetList[args.ItemIndex].Metadata!, null);
    }

    public void SetMap(EntityUid mapUid)
    {
        CameraMap.MapUid = _mapUid = mapUid;
    }

    private void OnCameraMapSelected(NetEntity netEntity)
    {
        if (_mapUid is null || !_entityManager.TryGetComponent<SurveillanceCameraMapComponent>(_mapUid.Value, out var mapComp))
            return;

        if (!mapComp.Cameras.TryGetValue(netEntity, out var marker) || !marker.Active)
            return;

        if (!string.IsNullOrEmpty(marker.Address))
            CameraSelected?.Invoke(marker.Address, marker.Subnet);
        else
            _entityManager.RaisePredictiveEvent(new RequestCameraMarkerUpdateMessage(netEntity));
>>>>>>> upstream/master
    }
}
