using Content.Shared._KS14.ZLevel.Elevators;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._KS14.ZLevel.Elevators.UI;

[GenerateTypedNameReferences]
public sealed partial class ZLevelElevatorControllerMenu : DefaultWindow
{
    public event Action<NetEntity>? OnFloorSelected;

    public ZLevelElevatorControllerMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(ZLevelElevatorControllerState state)
    {
        // Handed the raw state rather than a phrase picked here: which words a moving lift gets, and
        //      whether a language distinguishes up from down at all, is the translation's business.
        StatusLabel.Text = Loc.GetString(
            "zlevel-elevator-ui-status",
            ("moving", state.Moving),
            ("direction", state.Direction.ToString())
        );

        NoShaftLabel.Visible = state.Floors.Count == 0;

        // Rebuilt wholesale rather than patched: the floor list is the z-level stack, and a stack can gain
        //      or lose members at any time, so there is no stable row to update in place.
        FloorContainer.RemoveAllChildren();

        // The state arrives ascending, because that is how a stack is ordered. A lift panel reads top floor
        //      first, so it is walked backwards.
        for (var index = state.Floors.Count - 1; index >= 0; index--)
        {
            var floor = state.Floors[index];
            FloorContainer.AddChild(BuildFloorButton(floor, isCurrent: floor.ZLevel == state.CurrentFloor));
        }
    }

    private Button BuildFloorButton(ZLevelElevatorFloor floor, bool isCurrent)
    {
        // Every marker the floor carries goes in as a flag, so the one string owns their wording, their
        //      order and the spacing between them. Wrapping a label in a wrapper string per marker, as
        //      this used to, fixes all three in C# where no translation can reach them.
        //
        // Obstructed floors stay pressable on purpose: the elevator cuts its way in. Refusing them would
        //      hand anyone who welded a sheet of plating over a shaft the power to take a floor off the
        //      panel. Saying so is the point - an operator ought to know they are about to make a hole.
        var label = Loc.GetString(
            "zlevel-elevator-ui-floor",
            ("number", floor.Number),
            ("current", isCurrent),
            ("called", floor.Called),
            ("obstructed", floor.Obstructed)
        );

        var button = new Button
        {
            Text = label,
            HorizontalExpand = true,
            Disabled = isCurrent,
            StyleClasses = { "OpenBoth" },
        };

        var zLevel = floor.ZLevel;
        button.OnPressed += _ => OnFloorSelected?.Invoke(zLevel);

        return button;
    }
}
