- type: entity
  parent: BaseMachineCircuitboard
  id: MassDriverCircuitboard
  name: mass driver board
  components:
  - type: MachineBoard
    prototype: MassDriver
    stackRequirements:
      Steel: 5
      Manipulator: 2
      Cable: 4
...
