- type: entity
  id: BaseStationSiliconLawAsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Asimov
- type: entity
  id: BaseStationShuttlesATSless
  abstract: true
  components:
  - type: GridSpawn
    groups:
      ruins:
        hide: true
        nameGrid: true
        minCount: 4
        maxCount: 6
        stationGrid: false
        paths:
        - /Maps/Ruins/abandoned_outpost.yml
        - /Maps/Ruins/atmos_interchange.yml
        - /Maps/Ruins/chunked_tcomms.yml
        - /Maps/Ruins/biodome_satellite.yml
        - /Maps/Ruins/derelict.yml
        - /Maps/Ruins/djstation.yml
        - /Maps/Ruins/empty_flagship.yml
        - /Maps/Ruins/hydro_outpost.yml
        - /Maps/Ruins/old_ai_sat.yml
        - /Maps/Ruins/ruined_prison_ship.yml
        - /Maps/Ruins/syndicate_dropship.yml
        - /Maps/Ruins/whiteship_ancient.yml
        - /Maps/Ruins/whiteship_bluespacejumper.yml
        - /Maps/Ruins/wrecklaimer.yml
      wrecks:
        minimumDistance: 150
        maximumDistance: 300
        stationGrid: false
        minCount: 20
        maxCount: 35
        addComponents:
        - type: Gravity
          enabled: true
          inherent: true
        - type: IFF
          flags: HideLabel
          color: "#88b0d1"
        protos:
        - ChunkDebrisSmall
        - ChunkDebrisSmall
        - ChunkDebrisSmall
        - ChunkDebrisSmall
        - ChunkDebris
        - SpindlyAsteroid
        - SpindlyAsteroid
        - SpindlyAsteroid
        - BlobAsteroid
        - SwissCheeseAsteroid
        - SwissCheeseAsteroid
        - ClusterAsteroid
      vgroid:
        minimumDistance: 300
        maximumDistance: 350
        nameDataset: NamesBorer
        stationGrid: false
        addComponents:
        - type: Gravity
          enabled: true
          inherent: true
        protos:
        - VGRoid
...
