using Content.Client.UserInterface.Controls;
using Content.Shared._KS14.Packets.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._KS14.Packets.UI;

[GenerateTypedNameReferences]
public sealed partial class ExecutorMenu : FancyWindow
{
    public event Action? OnExecutionButton;
    public event Action? OnSaveButton;
    public event Action? OnLoadButton;

    public event Action? OnTerminateButton;

    public event Action? OnSendInputButton;
    public ExecutorMenu()
    {
        RobustXamlLoader.Load(this);

        ExecuteButton.OnPressed += _ => OnExecutionButton?.Invoke();
        SaveButton.OnPressed += _ => OnSaveButton?.Invoke();
        LoadButton.OnPressed += _ => OnLoadButton?.Invoke();
        SendInputButton.OnPressed += _ => OnSendInputButton?.Invoke();
        TerminateButton.OnPressed += _ => OnTerminateButton?.Invoke();
    }

    public void UpdateState(ExecutorBoundUserInterfaceState state)
    {
        Input.TextRope = Rope.Leaf.Empty;
        Input.CursorPosition = new TextEdit.CursorPos();
        Input.InsertAtCursor(state.Command);
    }

    public void WriteLog(string log)
    {
        ExecutorLog.Text += log;
    }
}

