using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._KS14.Voice.UI;

/// <summary>
///     Hands the player their personal microphone link. The link itself is never displayed, only opened or copied,
///         so it doesn't end up on screen captures.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class KsVoiceLinkWindow : FancyWindow
{
    public event Action? OpenPressed;
    public event Action? CopyPressed;
    public event Action? ResetPressed;

    /// <summary>
    ///     The rows that can't wrap, and so set how narrow the window may get.
    /// </summary>
    private readonly Control[] _unwrappableRows;

    public KsVoiceLinkWindow()
    {
        RobustXamlLoader.Load(this);

        Explanation.SetMessage(Loc.GetString("ks-voice-window-explanation"));
        Warning.SetMessage(FormattedMessage.FromMarkupOrThrow($"[color=#d0a23a]{FormattedMessage.EscapeText(Loc.GetString("ks-voice-window-warning"))}[/color]"));

        OpenButton.OnPressed += _ => OpenPressed?.Invoke();
        CopyButton.OnPressed += _ => CopyPressed?.Invoke();
        ResetButton.OnPressed += _ => ResetPressed?.Invoke();

        _unwrappableRows = [ButtonRow, KeybindLabel, StatusLabel];
    }

    protected override void Resized()
    {
        base.Resized();
        UpdateMinimumSize();
    }

    /// <summary>
    ///     Keeps the window from being resized small enough to hide anything. A fixed minimum can't: the explanation and
    ///         warning wrap, so the narrower the window, the taller they get, until they push the buttons out of the
    ///         bottom. So the minimum height follows the width, and the rows that can't wrap set the minimum width.
    /// </summary>
    private void UpdateMinimumSize()
    {
        // Not laid out yet: there's nothing to measure against.
        if (RootBox.Size.X <= 0f)
            return;

        var marginSize = new Vector2(RootBox.Margin.SumHorizontal, RootBox.Margin.SumVertical);

        // Title bar and borders: everything around the contents and their margin.
        var frameSize = Size - RootBox.Size - marginSize;

        var widestRow = 0f;
        foreach (var row in _unwrappableRows)
        {
            row.Measure(Vector2Helpers.Infinity);
            widestRow = MathF.Max(widestRow, row.DesiredSize.X);
        }

        // How tall the contents are when laid out at the current width (DesiredSize includes the margin).
        RootBox.Measure(new Vector2(RootBox.Size.X + marginSize.X, float.PositiveInfinity));

        var minSize = new Vector2(frameSize.X + marginSize.X + widestRow, frameSize.Y + RootBox.DesiredSize.Y);
        if (minSize.EqualsApprox(MinSize, tolerance: 0.5))
            return;

        MinSize = minSize;

        // Dragging resizes through SetSize, which the new minimum overrides anyway; keep it in step so the next drag
        //      starts from the size actually shown.
        if (Size.X < minSize.X || Size.Y < minSize.Y)
            SetSize = Vector2.Max(Size, minSize);
    }

    public void SetLinkAvailable(bool available)
    {
        OpenButton.Disabled = !available;
        CopyButton.Disabled = !available;
    }

    public void SetStatus(string status)
    {
        StatusLabel.Text = status;
        UpdateMinimumSize();
    }

    public void SetKeybind(string keybind)
    {
        KeybindLabel.Text = keybind;
        UpdateMinimumSize();
    }

    public void SetCopyText(string text)
    {
        CopyButton.Text = text;
        UpdateMinimumSize();
    }
}
