using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._KS14.Voice.UI;

/// <summary>
///     Hands the player their personal microphone link. The link itself is never displayed, only opened or copied,
///         so it doesn't end up on screen captures.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class KsVoiceLinkWindow : FancyWindow
{
    public event Action? OpenPressed;
    public event Action? CopyPressed;
    public event Action? ResetPressed;

    public KsVoiceLinkWindow()
    {
        RobustXamlLoader.Load(this);

        Explanation.SetMessage(Loc.GetString("ks-voice-window-explanation"));
        Warning.SetMessage(FormattedMessage.FromMarkupOrThrow($"[color=#d0a23a]{FormattedMessage.EscapeText(Loc.GetString("ks-voice-window-warning"))}[/color]"));

        OpenButton.OnPressed += _ => OpenPressed?.Invoke();
        CopyButton.OnPressed += _ => CopyPressed?.Invoke();
        ResetButton.OnPressed += _ => ResetPressed?.Invoke();
    }

    public void SetLinkAvailable(bool available)
    {
        OpenButton.Disabled = !available;
        CopyButton.Disabled = !available;
    }

    public void SetStatus(string status)
    {
        StatusLabel.Text = status;
    }

    public void SetKeybind(string keybind)
    {
        KeybindLabel.Text = keybind;
    }

    public void SetCopyText(string text)
    {
        CopyButton.Text = text;
    }
}
