- type: job
  id: ScenarioNt
  name: job-name-scenario-nt
  description: job-description-scenario-nt
  playTimeTracker: JobScenarioNt
  startingGear: null # scenario spawns get NOTHING
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-nobody
  canBeAntag: false
  access:
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: ScenarioNt
    - type: NpcFactionMember
      factions:
      - NanoTrasen
