- type: job
  id: ScenarioSyndie #TODO soot: species whitelist to be human only
  name: job-name-scenario-syndie
  description: job-description-scenario-syndie
  playTimeTracker: JobScenarioSyndie
  startingGear: null # scenario spawns get NOTHING
  icon: "JobIconSyndicate"
  supervisors: job-supervisors-nobody
  canBeAntag: false
  access:
  - SyndicateAgent
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: ScenarioSyndie
    - type: NpcFactionMember
      factions:
      - Syndicate
