using Content.Shared._Starlight.Plumbing;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Starlight.Plumbing.UI;

[GenerateTypedNameReferences]
public sealed partial class PlumbingFilterWindow : DefaultWindow
{
    public event Action<bool>? OnToggle;
    public event Action<string>? OnAddReagent;
    public event Action<string>? OnRemoveReagent;
    public event Action? OnClear;

    private bool _enabled = true;
    private string? _selectedReagent;

    public PlumbingFilterWindow()
    {
        RobustXamlLoader.Load(this);

        ToggleStatusButton.OnPressed += _ =>
        {
            _enabled = !_enabled;
            UpdateToggleButton();
            OnToggle?.Invoke(_enabled);
        };

        AddReagentButton.OnPressed += _ =>
        {
            var reagentId = ReagentIdInput.Text.Trim();
            if (string.IsNullOrEmpty(reagentId))
                return;

            OnAddReagent?.Invoke(reagentId);
            ReagentIdInput.Text = "";
        };

        RemoveButton.OnPressed += _ =>
        {
            if (_selectedReagent != null)
                OnRemoveReagent?.Invoke(_selectedReagent);
        };

        ClearButton.OnPressed += _ => OnClear?.Invoke();

        FilteredList.OnItemSelected += args =>
        {
            _selectedReagent = args.ItemList[args.ItemIndex].Metadata as string;
            RemoveButton.Disabled = _selectedReagent == null;
        };

        FilteredList.OnItemDeselected += _ =>
        {
            _selectedReagent = null;
            RemoveButton.Disabled = true;
        };
    }

    private void UpdateToggleButton()
    {
        ToggleStatusButton.Text = _enabled
            ? Loc.GetString("plumbing-filter-enabled")
            : Loc.GetString("plumbing-filter-disabled");
    }

    public void UpdateState(PlumbingFilterBoundUserInterfaceState state)
    {
        _enabled = state.Enabled;
        UpdateToggleButton();

        // Update filtered reagents list
        FilteredList.Clear();
        foreach (var reagentId in state.FilteredReagents)
        {
            FilteredList.Add(new ItemList.Item(FilteredList)
            {
                Metadata = reagentId,
                Text = reagentId
            });
        }

        _selectedReagent = null;
        RemoveButton.Disabled = true;
    }
}
