using System;
using Content.Client.Stylesheets;
using Content.Shared._KS14.AdminMusic;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._KS14.AdminMusic.UI;

[GenerateTypedNameReferences]
public sealed partial class KsAdminMusicPopup : Control
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IEntityNetworkManager _net = default!;
    [Dependency] private readonly KsAdminMusicManager _adminMusicManager = default!;

    private readonly KsAdminMusicEntry _entry;

    public KsAdminMusicPopup(KsAdminMusicEntry entry)
    {
        _entry = entry;

        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

    }

    public void UpdateData()
    {
        VoteTitle.SetMessage(FormattedMessage.FromUnformatted(_vote.Title));
        VoteCaller.Text = Loc.GetString("ui-vote-created", ("initiator", _vote.Initiator));

        for (var i = 0; i < _voteButtons.Length; i++)
        {
            var entry = _vote.Entries[i];
            if (_vote.DisplayVotes)
            {
                _voteButtons[i].Text = Loc.GetString("ui-vote-button", ("text", entry.Text), ("votes", entry.Votes));
            }
            else
            {
                _voteButtons[i].Text = Loc.GetString("ui-vote-button-no-votes", ("text", entry.Text));
            }

            if (_vote.OurVote == i)
                _voteButtons[i].Pressed = true;
        }
    }

    private void AttemptFollowVoteEntity()
    {
        if (_targetEntity != null)
        {
            var msg = new GhostWarpToTargetRequestEvent(_targetEntity.Value);
            _net.SendSystemNetworkMessage(msg);
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        // Logger.Debug($"{_gameTiming.ServerTime}, {_vote.StartTime}, {_vote.EndTime}");

        var curTime = _gameTiming.RealTime;
        var timeLeft = _entry.EndTime - curTime;
        if (timeLeft < TimeSpan.Zero)
            timeLeft = TimeSpan.Zero;

        // Round up a second.
        timeLeft = TimeSpan.FromSeconds(Math.Ceiling(timeLeft.TotalSeconds));

        TimeLeftBar.Value = Math.Min(1, (float)((curTime.TotalSeconds - _vote.StartTime.TotalSeconds) /
                                                 (_vote.EndTime.TotalSeconds - _vote.StartTime.TotalSeconds)));

        TimeLeftText.Text = $"{timeLeft:m\\:ss}";
    }
}
