using Content.Shared._KS14.AdminMusic;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Sources;
using Robust.Shared.Timing;

namespace Content.Client._KS14.AdminMusic.UI;

[GenerateTypedNameReferences]
public sealed partial class KsAdminMusicPopup : Control
{
    [Dependency] private IGameTiming _gameTiming = default!;

    private KsAdminMusicEntry _entry = null!;
    private IAudioSource _audioSource = null!;
    public event Action<KsAdminMusicEntry>? OnCancelPressed;

    public KsAdminMusicPopup()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        TimeLeftBar.MinValue = 0f;
    }

    public void SetData(KsAdminMusicEntry entry, AudioStream audioStream, IAudioSource audioSource)
    {
        _entry = entry;
        _audioSource = audioSource;

        VolumeSlider.Value = entry.Volume;
        OnVolumeChanged();

        // ya we copy
        var artist = string.IsNullOrEmpty(audioStream.Artist)
            ? Loc.GetString("lobby-state-song-unknown-artist")
            : audioStream.Artist;

        var title = string.IsNullOrEmpty(audioStream.Title)
            ? Loc.GetString("lobby-state-song-unknown-title")
            : audioStream.Title;

        TitleText.Text = $"{artist} - {title}";
        TimeLeftBar.MaxValue = (float)audioStream.Length.TotalSeconds;

        StopMusicButton.OnPressed += _ => OnCancelPressed?.Invoke(_entry);
        VolumeSlider.OnValueChanged += _ => OnVolumeChanged();
    }

    private void OnVolumeChanged()
    {
        _audioSource.Gain = VolumeSlider.Value;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        TimeLeftBar.Value = (float)(_gameTiming.CurTime - _entry.StartTime).TotalSeconds;
    }
}
