using Content.Client.Shuttles.UI;
using Content.Shared._KS14.Sensors.Prototypes;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._KS14.Shuttles.UI;

/// <summary>
///     The DOCK tab in the KS instrument language: the fork counterpart of the
///         upstream <see cref="DockingScreen"/>, same public surface so the instrument
///         window swaps it in transparently. The upstream screen's detached DockObject
///         build is dropped: its host container was retired upstream.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class KsDockScreen : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _protoManager = default!;

    private KsSensorHudPrototype? _hud;
    private KsSensorHudPrototype Hud => _hud ??= _protoManager.Index(KsSensorHudPrototype.DefaultId);

    /// <summary>Stored by GridID then by docks.</summary>
    public Dictionary<NetEntity, List<DockingPortState>> Docks = new();

    /// <summary>Store the dock buttons for the side buttons.</summary>
    private readonly Dictionary<NetEntity, Button> _ourDockButtons = new();

    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity>? UndockRequest;

    public KsDockScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PlotPanel.Title = Loc.GetString("ks-dock-panel-plot");
        PortsPanel.Title = Loc.GetString("ks-dock-panel-ports");

        var palette = Hud.GetScreen("dock");
        foreach (var panel in new[] { PlotPanel, PortsPanel })
        {
            panel.Accent = palette.Accent;
            panel.Background = palette.Background;
        }

        DockingControl.OnViewDock += OnView;
        DockingControl.DockRequest += (entity, netEntity) =>
        {
            DockRequest?.Invoke(entity, netEntity);
        };
        DockingControl.UndockRequest += entity =>
        {
            UndockRequest?.Invoke(entity);
        };
    }

    private void OnView(NetEntity obj)
    {
        if (_ourDockButtons.TryGetValue(obj, out var viewed))
        {
            viewed.Pressed = true;
        }
    }

    public void UpdateState(EntityUid? shuttle, DockingInterfaceState state)
    {
        Docks = state.Docks;
        DockingControl.DockState = state;
        DockingControl.GridEntity = shuttle;
        BuildDocks(shuttle);
    }

    private void BuildDocks(EntityUid? shuttle)
    {
        DockingControl.BuildDocks(shuttle);
        var currentDock = DockingControl.ViewedDock;
        DockPorts.RemoveAllChildren();
        _ourDockButtons.Clear();

        if (shuttle == null)
        {
            DockingControl.SetViewedDock(null);
            return;
        }

        var shuttleNent = _entManager.GetNetEntity(shuttle.Value);

        if (!Docks.TryGetValue(shuttleNent, out var shuttleDocks) || shuttleDocks.Count <= 0)
        {
            DockPorts.AddChild(new Label
            {
                Text = Loc.GetString("ks-dock-ports-empty"),
                StyleClasses = { KsInstrumentSheetlet.StyleClassText },
                FontColorOverride = Hud.GetScreen("dock").TextDim,
            });
            return;
        }

        var buttonGroup = new ButtonGroup();
        var selected = false;

        foreach (var dock in shuttleDocks)
        {
            var button = new Button
            {
                Text = dock.Name,
                ToggleMode = true,
                Group = buttonGroup,
                StyleClasses = { KsInstrumentSheetlet.StyleClassAction },
                HorizontalExpand = true,
                Margin = new Thickness(0f, 0f, 0f, 2f),
            };
            KsInstrumentSheetlet.MakeInstrument(button);

            button.OnMouseEntered += _ =>
            {
                DockingControl.HighlightedDock = dock.Entity;
            };

            button.OnMouseExited += _ =>
            {
                DockingControl.HighlightedDock = null;
            };

            if (currentDock == dock.Entity)
            {
                selected = true;
                button.Pressed = true;
            }

            button.OnPressed += _ =>
            {
                OnDockPress(dock);
            };

            _ourDockButtons[dock.Entity] = button;
            DockPorts.AddChild(button);
        }

        // Button group needs one selected so just show the first one.
        if (!selected)
        {
            OnDockPress(shuttleDocks[0]);
        }
    }

    private void OnDockPress(DockingPortState state)
    {
        DockingControl.SetViewedDock(state);
    }
}
