using System.Linq;
using System.Numerics;
using Content.Shared._KS14.CCVar;
using Content.Shared._KS14.Sensors;
using Content.Shared._KS14.Sensors.Prototypes;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._KS14.Shuttles.UI;

/// <summary>
///     The ESM instrument screen: one ship-relative BOW-up bearing plot and one
///         emitter roster carry the whole designated set; live threats keep the
///         RWR's channel colours and per-channel strobe, memory tracks keep the
///         ELINT's ghost presentation.
///     The machines gate the panels, not the tab: an ELINT array unlocks the
///         precision side (roster memory, selection, signal analysis, FOCUS),
///         an RWR receiver unlocks the warning side (threat channels, posture,
///         the window's tab-alert flash). A missing machine degrades its panel
///         to a chip naming the absent fit; with neither machine the screen
///         shows nothing except the grid-level jam warnings in the log (your own
///         radar being attacked is not ESM product).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class KsEsmScreen : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IPrototypeManager _protoManager = default!;
    [Dependency] private IConfigurationManager _cfg = default!;

    private readonly SharedTransformSystem _xformSystem;

    /// <summary>Liveness edge detector driving the plot's contact ping and ghost fade.</summary>
    private readonly KsContactTransitions _transitions = new();

    /// <summary>The ANALYSIS percentage as displayed: eased toward the pushed progress so the counter counts up smoothly between state pushes.</summary>
    private float _analysisShown;

    private KsSensorHudPrototype? _hud;
    private KsSensorHudPrototype Hud => _hud ??= _protoManager.Index(KsSensorHudPrototype.DefaultId);
    private KsInstrumentPalette Palette => Hud.GetScreen("esm");

    /// <summary>Channels by descending priority (the match order), fixed for the session like the HUD palette.</summary>
    private readonly List<KsThreatChannelPrototype> _channels;

    /// <summary>Postures by descending severity; the first met one shows.</summary>
    private readonly List<KsPosturePrototype> _postures;

    // Session-constant strings, resolved once instead of per frame.
    private readonly string _liveText = Loc.GetString("ks-elint-roster-live");
    private readonly string _memoryText = Loc.GetString("ks-elint-roster-memory");
    private readonly string _rwrNoValueText = Loc.GetString("ks-rwr-field-no-value");
    private readonly string _elintNoValueText = Loc.GetString("ks-elint-field-no-value");
    private readonly string _selectedNoneText = Loc.GetString("ks-elint-selected-none");

    private EntityUid? _shuttleEntity;

    private bool _hasElint;
    private bool _hasRwr;

    /// <summary>
    ///     The rostered set, live threats first. Channel is matched only for live
    ///         threats under an RWR fit and drives the threat colouring and strobe;
    ///         null means "present it the ELINT way".
    /// </summary>
    private List<(KsSensorContactState Contact, KsThreatChannelPrototype? Channel)> _roster = new();

    /// <summary>
    ///     Rows are remade every push, so chip/status resolve once at rebuild; between
    ///         pushes only the bearing digits change and the frame pass skips
    ///         unchanged rows entirely (a Text write invalidates layout).
    /// </summary>
    private readonly List<RosterRow> _rosterRows = new();

    private sealed class RosterRow
    {
        public Button Button = default!;
        public KsSensorContactState Contact = default!;
        public KsThreatChannelPrototype? Channel;
        public string Chip = string.Empty;
        public string Status = string.Empty;
        public string? LastDigits;
    }

    /// <summary>Lit channel-counter rows, kept for the channel-rate blink.</summary>
    private readonly List<(Label Row, KsThreatChannelPrototype Channel)> _litChannelRows = new();

    /// <summary>Plot entries' resting colours + blink rates (entries themselves live on the plot).</summary>
    private readonly List<(int Index, Color Base, float BlinkHz)> _plotBlink = new();

    /// <summary>
    ///     Exact-fix plot entry indices paired with their source contact, so
    ///         FrameUpdate can re-reckon each fix every frame between pushes; rebuilt
    ///         with the plot.
    /// </summary>
    private readonly List<(int Index, KsSensorContactState Contact)> _plotFixes = new();

    private NetEntity? _selected;

    /// <summary>Resolved on push/selection; FrameUpdate reads it every frame.</summary>
    private KsSensorContactState? _selectedContact;

    /// <summary>Push-constant, gates CEASE.</summary>
    private bool _anyFocused;

    /// <summary>The posture the hosting window's ESM tab button should flash; null with no RWR receiver or nothing illuminating.</summary>
    public KsPosturePrototype? AlertPosture { get; private set; }

    /// <summary>The tab-alert strobe rate: the priority channel's own blink rate.</summary>
    public float AlertBlinkHz { get; private set; } = 1f;

    /// <summary>Focus analysis ordered on the selected emitter; the window's BUI sends the server message.</summary>
    public event Action<NetEntity>? OnFocusRequest;

    public event Action? OnClearFocusRequest;

    public KsEsmScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xformSystem = _entManager.System<SharedTransformSystem>();

        _channels = _protoManager.EnumeratePrototypes<KsThreatChannelPrototype>()
            .OrderByDescending(c => c.Priority)
            .ThenBy(c => c.ID, StringComparer.Ordinal)
            .ToList();
        _postures = _protoManager.EnumeratePrototypes<KsPosturePrototype>()
            .OrderByDescending(p => p.Order)
            .ToList();

        PlotPanel.Title = Loc.GetString("ks-esm-panel-plot");
        RosterPanel.Title = Loc.GetString("ks-esm-panel-roster");
        ThreatPanel.Title = Loc.GetString("ks-esm-panel-threat");
        SelectedPanel.Title = Loc.GetString("ks-esm-panel-selected");
        LogPanel.Title = Loc.GetString("ks-esm-panel-log");

        var palette = Palette;
        foreach (var panel in new[] { PlotPanel, RosterPanel, ThreatPanel, SelectedPanel, LogPanel })
        {
            panel.Accent = palette.Accent;
            panel.Background = palette.Background;
        }

        KsInstrumentSheetlet.MakeInstrument(FocusButton, CeaseButton);

        RwrChip.FontColorOverride = palette.Warning;
        ElintChip.FontColorOverride = palette.Warning;
        ElintDeafChip.FontColorOverride = palette.Warning;

        Plot.Palette = palette;
        Plot.OnEntrySelected += Select;
        LogList.Palette = palette;

        FocusButton.OnPressed += _ =>
        {
            if (_selected is { } selected)
                OnFocusRequest?.Invoke(selected);
        };

        CeaseButton.OnPressed += _ => OnClearFocusRequest?.Invoke();

        RebuildChannels();
        RefreshStatus();
        RefreshSelected();
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;
        // No own-hull silhouette on the ESM dial: with the plot's OwnGrid left
        // unset it draws its centre cross instead.
    }

    public void UpdateState(NavInterfaceState state)
    {
        var nav = state.KsSensorNav;
        var contacts = nav?.Contacts;

        _hasElint = nav?.HasElint ?? false;
        _hasRwr = nav?.HasRwr ?? false;

        // The machines gate the population, the datalink only feeds it: an ELINT
        // array rosters every designated contact the pool holds (live or memory),
        // a bare RWR only what is illuminating RIGHT NOW (a tripwire has no
        // memory), and a grid with neither fit rosters nothing at all, even when
        // allies relay designated tracks.
        IEnumerable<KsSensorContactState> population;
        if (contacts == null || !_hasElint && !_hasRwr)
            population = Enumerable.Empty<KsSensorContactState>();
        else if (_hasElint)
            population = contacts.Where(c => c.Designation != null);
        else
            population = contacts.Where(c => c.Designation != null && c.EmitterLive);

        _roster = population
            .Select(c => (Contact: c, Channel: _hasRwr && c.EmitterLive ? KsThreatEval.MatchChannel(c, _channels) : null))
            .OrderByDescending(t => t.Contact.EmitterLive)
            .ThenByDescending(t => t.Channel?.Priority ?? int.MinValue)
            .ThenBy(t => t.Contact.Designation, StringComparer.Ordinal)
            .ToList();

        _transitions.Update(contacts, _timing.CurTime);

        // The acquired/silent lines are ESM product and follow the dead-screen
        // rule; the jam lines are the grid's own radar being attacked and print
        // regardless of ESM fit.
        var log = nav?.EmissionLog;
        if (log != null && !_hasElint && !_hasRwr)
        {
            log = log.Where(e => e.Kind is KsEmissionLogKind.JamStart or KsEmissionLogKind.JamEnd).ToList();
            if (log.Count == 0)
                log = null;
        }
        LogList.Update(log);

        if (_selected != null && _roster.All(t => t.Contact.Grid != _selected))
            _selected = null;

        _selectedContact = SelectedContact();
        _anyFocused = _roster.Any(t => t.Contact.Focused);

        RwrChip.Visible = !_hasRwr;
        ChannelList.Visible = _hasRwr;
        PostureGrid.Visible = _hasRwr;
        ElintChip.Visible = !_hasElint;
        SelectedGrid.Visible = _hasElint;
        FocusRow.Visible = _hasElint;

        // Fitted but self-blinded by the own transmitter: the crew must learn why
        // the roster went stale, not wonder at a suddenly quiet sector. The RWR
        // side keeps warning regardless (deliberately no self-blind there).
        ElintDeafChip.Visible = _hasElint && (nav?.ElintDeaf ?? false);

        RebuildPlot();
        RebuildRoster();
        RebuildChannels();
        RefreshStatus();
        RefreshSelected();
    }

    private KsSensorContactState? SelectedContact()
    {
        if (_selected is not { } selected)
            return null;

        return _roster.FirstOrDefault(t => t.Contact.Grid == selected).Contact;
    }

    private void Select(NetEntity grid)
    {
        _selected = grid;
        Plot.Selected = grid;
        _selectedContact = SelectedContact();
        // A fresh selection starts its counter at the pushed value, no easing-in.
        _analysisShown = _selectedContact?.AnalysisProgress ?? 0f;
        RebuildRoster();
        RefreshSelected();
    }

    /// <summary>
    ///     A row's resting colour: a live threat under an RWR fit wears its channel
    ///         colour (falling back to the contact tier when unmatched), anything
    ///         else the ELINT presentation (tier colour, dimmed for memory).
    /// </summary>
    private Color RowColor(KsSensorContactState contact, KsThreatChannelPrototype? channel)
    {
        if (_hasRwr && contact.EmitterLive)
            return channel?.Color ?? Hud.GetContactColor(contact.Type);

        var baseColor = Hud.GetContactColor(contact.Type);
        return contact.Live ? baseColor : Hud.Dim(baseColor);
    }

    private void RebuildPlot()
    {
        Plot.Entries.Clear();
        _plotBlink.Clear();
        _plotFixes.Clear();
        Plot.Selected = _selected;
        Plot.Focused = null;

        foreach (var (contact, channel) in _roster)
        {
            if (contact.Focused)
                Plot.Focused = contact.Grid;

            // The plot gets the LIVE resting colour plus the transition timings: it
            // owns the presentation shading (afterglow, ghost fade, ping) itself.
            // Ghost/ping shading is ELINT presentation; a bare RWR plots only live
            // threats, which strobe instead.
            var entry = new KsBearingPlotEntry
            {
                Grid = contact.Grid,
                Label = contact.Designation ?? string.Empty,
                Color = _hasRwr && contact.EmitterLive
                    ? channel?.Color ?? Hud.GetContactColor(contact.Type)
                    : Hud.GetContactColor(contact.Type),
                Live = contact.Live,
                LastSeen = contact.LastSeen,
                GhostSince = _hasElint ? _transitions.BecameGhost(contact.Grid) : null,
                PingStart = _hasElint ? _transitions.BecameLive(contact.Grid) : null,
            };

            if (contact.Quality == KsPositionQuality.Exact)
            {
                // Dead-reckoned like every other instrument, and re-reckoned each
                // frame (see FrameUpdate): a fix plotted at the raw push position
                // would disagree with the nav scope's glided blip by whole degrees.
                entry.WorldPosition = contact.EstimatedPosition(_timing.CurTime);
                _plotFixes.Add((Plot.Entries.Count, contact));
            }
            else if (contact.Bearing is { } strobe)
                entry.Strobe = strobe;
            else
                continue; // roster-only: nothing may be plotted without leaking the relay ally

            if (_hasRwr && contact.EmitterLive)
                _plotBlink.Add((Plot.Entries.Count, entry.Color, channel?.BlinkHz ?? 1f));
            Plot.Entries.Add(entry);
        }
    }

    private void RebuildRoster()
    {
        RosterList.RemoveAllChildren();
        _rosterRows.Clear();

        if (_roster.Count == 0)
        {
            var emptyId = !_hasElint && !_hasRwr ? "ks-esm-roster-offline"
                : _hasElint ? "ks-elint-roster-empty"
                : "ks-rwr-threats-empty";

            RosterList.AddChild(new Label
            {
                Text = Loc.GetString(emptyId),
                StyleClasses = { KsInstrumentSheetlet.StyleClassText },
                FontColorOverride = Palette.TextDim,
            });
            return;
        }

        var own = OwnWorldPosition();
        var rotation = OwnRotation();

        foreach (var (contact, channel) in _roster)
        {
            var chip = channel != null
                ? Loc.GetString(channel.Label)
                : ClassLabel(contact);

            // LIVE is the EMISSION, not the hull track: an ally's relay can keep the
            // track alive after the emitter went silent. Dimming stays on track liveness.
            var status = contact.EmitterLive ? _liveText : _memoryText;

            var digits = RelativeBearingDigits(contact, own, rotation);

            var row = new Button
            {
                StyleClasses = { KsInstrumentSheetlet.StyleClassAction },
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2),
                Text = RosterRowText(contact, chip, digits, status),
            };
            KsInstrumentSheetlet.MakeInstrument(row);

            row.Label.FontColorOverride = RowColor(contact, channel);

            var grid = contact.Grid;
            row.OnPressed += _ => Select(grid);
            RosterList.AddChild(row);
            _rosterRows.Add(new RosterRow
            {
                Button = row,
                Contact = contact,
                Channel = channel,
                Chip = chip,
                Status = status,
                LastDigits = digits,
            });
        }
    }

    /// <summary>
    ///     One roster line: designation, the channel chip (threat channel for a live
    ///         threat under an RWR fit, else the heard classification), the RELATIVE
    ///         bearing matching the BOW-up plot, and the LIVE/MEM emission status.
    /// </summary>
    private string RosterRowText(KsSensorContactState contact, string chip, string? digits, string status)
    {
        var bearing = digits != null
            ? Loc.GetString("ks-rwr-threat-bearing", ("deg", digits))
            : _rwrNoValueText;

        return $"{contact.Designation,-6} {chip,-7} {bearing,4} {status,4}";
    }

    /// <summary>
    ///     What the heard emission classified as. Read from the emitter-class
    ///         SOURCES, not the contact's winning type: an emitter co-tracked by a
    ///         higher-tier sensor (visual, IRST) keeps its winning tier for
    ///         colour/precedence, but its classification is still what ELINT heard.
    ///         Falls back to the generic label once every emitter-class source has
    ///         aged out.
    /// </summary>
    private string ClassLabel(KsSensorContactState contact)
    {
        var hasJammer = false;
        var hasRadar = false;

        foreach (var source in contact.Sources)
        {
            hasJammer |= source.Type == KsSensorType.Jammer;
            hasRadar |= source.Type is KsSensorType.Elint or KsSensorType.Rwr;
        }

        var locId = hasJammer ? "ks-elint-class-jammer"
            : hasRadar ? "ks-elint-class-radar"
            : "ks-elint-class-unknown";
        return Loc.GetString(locId);
    }

    /// <summary>
    ///     Relative bearing (000 = bow) as bare digits, null for a roster-only relay
    ///         track: pure math, so the frame pass can compare before any Fluent
    ///         lookup. Own position/rotation arrive pre-fetched, once per list.
    /// </summary>
    private string? RelativeBearingDigits(KsSensorContactState contact, Vector2? own, Angle rotation)
    {
        Angle? dir = null;

        if (contact.Bearing is { } strobe)
        {
            dir = strobe.Bearing;
        }
        else if (contact.Quality == KsPositionQuality.Exact && own is { } ownPos)
        {
            var rel = contact.EstimatedPosition(_timing.CurTime) - ownPos;
            if (rel.LengthSquared() > 0f)
                dir = Math.Atan2(rel.Y, rel.X);
        }

        if (dir is not { } d)
            return null;

        return $"{KsBearingPlot.CompassDegrees(d - rotation):000}";
    }

    /// <summary>
    ///     The COMPASS bearing shown in the analysis panel: north-referenced
    ///         precision intel, unlike the roster's bow-relative quick-look. The
    ///         strobe's bearing for a bearing track, the direction toward the known
    ///         position for a fix, a placeholder for a roster-only track.
    /// </summary>
    private string CompassBearingLabel(KsSensorContactState contact)
    {
        float? deg = null;

        if (contact.Bearing is { } strobe)
        {
            deg = KsBearingPlot.CompassDegrees(strobe.Bearing);
        }
        else if (contact.Quality == KsPositionQuality.Exact && OwnWorldPosition() is { } own)
        {
            var rel = contact.EstimatedPosition(_timing.CurTime) - own;
            if (rel.LengthSquared() > 0f)
                deg = KsBearingPlot.CompassDegrees(Math.Atan2(rel.Y, rel.X));
        }

        return deg is { } d
            ? Loc.GetString("ks-sensor-contact-bearing", ("deg", $"{d:000}"))
            : _elintNoValueText;
    }

    private void RebuildChannels()
    {
        ChannelList.RemoveAllChildren();
        _litChannelRows.Clear();

        if (!_hasRwr)
            return;

        foreach (var channel in _channels)
        {
            var count = _roster.Count(t => t.Channel == channel && t.Contact.EmitterLive);
            var lit = count > 0;

            var row = new Label
            {
                Text = $"{Loc.GetString(channel.Label),-8} {count:00}",
                StyleClasses = { KsInstrumentSheetlet.StyleClassStrong },
                FontColorOverride = lit ? channel.Color : Palette.TextDim,
            };

            ChannelList.AddChild(row);
            if (lit)
                _litChannelRows.Add((row, channel));
        }
    }

    private void RefreshStatus()
    {
        if (!_hasRwr)
        {
            AlertPosture = null;
            return;
        }

        var palette = Palette;
        var threatCount = _roster.Count(t => t.Contact.EmitterLive);
        var litPriority = _litChannelRows.Count > 0 ? _litChannelRows.Max(r => r.Channel.Priority) : (int?) null;

        var posture = KsThreatEval.PickPosture(_postures, threatCount, litPriority);

        PostureValue.Text = posture != null ? Loc.GetString(posture.Label) : _rwrNoValueText;
        PostureValue.FontColorOverride = posture?.Color ?? palette.TextDim;

        var priorityChannel = _litChannelRows.Count > 0
            ? _litChannelRows.MaxBy(r => r.Channel.Priority).Channel
            : null;
        PriorityValue.Text = priorityChannel != null ? Loc.GetString(priorityChannel.Label) : _rwrNoValueText;
        PriorityValue.FontColorOverride = priorityChannel?.Color ?? palette.TextDim;

        // The tab-alert only escalates: an unthreatened posture (the always-met
        // floor) stays off the tab so the strip is quiet in a quiet sector.
        AlertPosture = threatCount > 0 ? posture : null;
        AlertBlinkHz = priorityChannel?.BlinkHz ?? 1f;
    }

    private Angle OwnRotation()
    {
        return _shuttleEntity is { } shuttle && _entManager.HasComponent<TransformComponent>(shuttle)
            ? _xformSystem.GetWorldRotation(shuttle)
            : Angle.Zero;
    }

    private Vector2? OwnWorldPosition()
    {
        if (!_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? xform)
            || !_entManager.TryGetComponent(_shuttleEntity, out PhysicsComponent? body))
            return null;

        var (_, _, worldMatrix) = _xformSystem.GetWorldPositionRotationMatrix(xform);
        return Vector2.Transform(body.LocalCenter, worldMatrix);
    }

    /// <summary>The Text setter invalidates layout even for identical text, and this runs per frame.</summary>
    private static void SetText(Label label, string? text)
    {
        if (label.Text != text)
            label.Text = text;
    }

    private void RefreshSelected()
    {
        if (!_hasElint)
            return;

        var palette = Palette;
        var contact = _selectedContact;

        FocusButton.Disabled = contact == null || contact.Focused;
        CeaseButton.Disabled = !_anyFocused;

        if (contact == null)
        {
            SetText(DesigValue, _selectedNoneText);
            SetText(ClassValue, "");
            SetText(BandValue, "");
            SetText(PatternValue, "");
            SetText(SignalValue, "");
            SetText(BearingValue, "");
            SetText(LastValue, "");
            SetText(AnalysisValue, "");
            DesigValue.FontColorOverride = palette.TextDim;
            return;
        }

        SetText(DesigValue, contact.Name != null ? $"{contact.Designation} {contact.Name}" : contact.Designation);
        DesigValue.FontColorOverride = contact.Live ? palette.Text : palette.TextDim;
        SetText(ClassValue, ClassLabel(contact));
        SetText(BandValue, contact.Band is { } band && _protoManager.TryIndex(band, out var bandProto)
            ? Loc.GetString(bandProto.Label)
            : Loc.GetString("ks-emitter-band-unknown"));
        SetText(PatternValue, contact.Pattern switch
        {
            KsEmissionPattern.Continuous => Loc.GetString("ks-emitter-pattern-continuous"),
            _ => Loc.GetString("ks-emitter-pattern-unknown"),
        });

        SetText(SignalValue, contact.SignalStrength is { } signal
            ? Loc.GetString("ks-elint-field-signal-value", ("percent", (int) MathF.Round(signal * 100f)))
            : _elintNoValueText);

        // A fixed contact outranks any bearing-quality wording: closing in and
        // earning a position must read as the upgrade it is, not as STABLE
        // decaying to a placeholder.
        var stability = contact.Quality == KsPositionQuality.Exact
            ? Loc.GetString("ks-sensor-stability-fix")
            : contact.Stability switch
            {
                KsBearingStability.Stable => Loc.GetString("ks-sensor-stability-stable"),
                KsBearingStability.Drifting => Loc.GetString("ks-sensor-stability-drifting"),
                _ => Loc.GetString("ks-sensor-stability-unknown"),
            };
        SetText(BearingValue, Loc.GetString("ks-elint-field-bearing-value",
            ("deg", CompassBearingLabel(contact)),
            ("stability", stability)));

        var age = (_timing.CurTime - contact.LastSeen).TotalSeconds;
        SetText(LastValue, age < 1.5
            ? Loc.GetString("ks-elint-field-last-seen-now")
            : Loc.GetString("ks-elint-field-last-seen-value", ("seconds", (int) age)));
        LastValue.FontColorOverride = contact.Live ? palette.Good : palette.TextDim;

        SetText(AnalysisValue, contact.Focused
            ? Loc.GetString("ks-elint-field-analysis-value", ("percent", (int) MathF.Round(_analysisShown * 100f)))
            : Loc.GetString("ks-elint-field-analysis-idle"));
        AnalysisValue.FontColorOverride = contact.Focused && contact.AnalysisProgress >= 1f ? palette.Good : palette.Text;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // BOW-up: the plot rides the ship's live rotation, so the picture turns
        // with the hull between server pushes.
        if (OwnWorldPosition() is { } own)
            Plot.OwnWorldPosition = own;
        Plot.PlotRotation = OwnRotation();

        // Fix dots glide along their dead-reckoned track like the nav scope's blips.
        // The entries are structs, so each is written back by index.
        foreach (var (index, contact) in _plotFixes)
        {
            var fix = Plot.Entries[index];
            fix.WorldPosition = contact.EstimatedPosition(_timing.CurTime);
            Plot.Entries[index] = fix;
        }

        var reduced = _cfg.GetCVar(KsCCVars.HudReducedMotion);
        var now = _timing.CurTime.TotalSeconds;

        // Threat strobe rides on the selection dim; bearings re-read per frame so
        // rows turn with the hull.
        var rosterOwn = OwnWorldPosition();
        var rosterRotation = OwnRotation();
        foreach (var row in _rosterRows)
        {
            var digits = RelativeBearingDigits(row.Contact, rosterOwn, rosterRotation);
            if (digits != row.LastDigits)
            {
                row.LastDigits = digits;
                row.Button.Text = RosterRowText(row.Contact, row.Chip, digits, row.Status);
            }

            var tint = row.Contact.Grid == _selected ? 1f : 0.75f;
            var v = _hasRwr && row.Contact.EmitterLive
                ? Hud.ThreatStrobe.Eval(now, reduced, row.Channel?.BlinkHz ?? 1f)
                : 1f;
            row.Button.Modulate = new Color(tint * v, tint * v, tint * v);
        }

        foreach (var (row, channel) in _litChannelRows)
        {
            var v = Hud.ThreatStrobe.Eval(now, reduced, channel.BlinkHz);
            row.Modulate = new Color(v, v, v);
        }

        foreach (var (index, baseColor, blinkHz) in _plotBlink)
        {
            var v = Hud.ThreatStrobe.Eval(now, reduced, blinkHz);
            var entry = Plot.Entries[index];
            entry.Color = new Color(baseColor.R * v, baseColor.G * v, baseColor.B * v, baseColor.A);
            Plot.Entries[index] = entry;
        }

        // Ease the displayed ANALYSIS counter toward the pushed progress;
        // reduce-motion snaps it.
        var target = _selectedContact?.AnalysisProgress ?? 0f;
        _analysisShown = reduced
            ? target
            : _analysisShown + (target - _analysisShown) * Math.Clamp(args.DeltaSeconds * 6f, 0f, 1f);
        if (MathF.Abs(target - _analysisShown) < 0.005f)
            _analysisShown = target;

        // Push-driven state ages between pushes (a quiet sector sends nothing):
        // keep the selected panel's LAST/bearing readouts counting.
        RefreshSelected();
    }
}
