using System.Linq;
using System.Numerics;
using Content.Shared._KS14.CCVar;
using Content.Shared._KS14.Sensors;
using Content.Shared._KS14.Sensors.Prototypes;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._KS14.Shuttles.UI;

/// <summary>
///     The KS console's instrument shell: a HighFleet-style frame with the
///         RADAR // MAP // ESM // DOCK tab strip and a status strip. The ESM tab
///         button doubles as the ship's master caution light: it flashes the
///         posture colour while the warning receiver holds live threats, so
///         illumination warnings escape the tab.
///     A bare <see cref="BaseWindow"/> (via the <see cref="KsBaseWindow"/> XAML-root
///         shim), not a FancyWindow: the whole window is the instrument, so the
///         bezel, title bar and close button are its own chrome, coloured from the
///         HUD prototype's chrome block.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class KsInstrumentWindow : KsBaseWindow
{
    /// <summary>Edge width (px) that grabs a resize instead of a move, matching FancyWindow's feel.</summary>
    private const int DragMarginSize = 7;

    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IPrototypeManager _protoManager = default!;
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IClyde _clyde = default!;

    /// <summary>The OS window hosting the suite while popped out, else null.</summary>
    private IClydeWindow? _popoutWindow;
    private WindowRoot? _popoutRoot;

    /// <summary>The in-game SetSize to restore on pop-in (popping out clears it so the suite fills the OS window).</summary>
    private Vector2 _prePopSetSize;

    private KsSensorHudPrototype? _hud;
    private KsSensorHudPrototype Hud => _hud ??= _protoManager.Index(KsSensorHudPrototype.DefaultId);

    private KsInstrumentTab _tab = KsInstrumentTab.Radar;
    private TimeSpan _tabSwitchedAt = TimeSpan.MinValue;

    /// <summary>The console's remembered switch positions; null until the BUI binds one.</summary>
    private KsConsoleUiPrefs? _prefs;

    /// <summary>Tab restore parked until the first state: MAP's Startup needs the shuttle bound.</summary>
    private KsInstrumentTab? _pendingTab;

    /// <summary>When the shell was created; drives the power-on boot flicker.</summary>
    private TimeSpan _bootStartedAt = TimeSpan.MinValue;

    public event Action<MapCoordinates, Angle>? RequestFTL;
    public event Action<NetEntity, Angle>? RequestBeaconFTL;

    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity>? UndockRequest;

    public event Action? RequestToggleRadar;
    public event Action? RequestToggleJammer;

    public event Action<NetEntity>? RequestElintFocus;
    public event Action? RequestElintClearFocus;

    public KsInstrumentWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        KsInstrumentSheetlet.MakeInstrument(
            RadarTabButton, MapTabButton, EsmTabButton, DockTabButton,
            PopChromeButton, CloseChromeButton);

        var shell = Hud.GetScreen("shell");
        foreach (var separator in new[] { Sep1, Sep2, Sep3 })
        {
            separator.FontColorOverride = shell.AccentDim;
        }

        var chrome = Hud.Chrome;
        Bezel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = chrome.WindowBackground,
            BorderColor = chrome.WindowBorder,
            BorderThickness = new Thickness(2),
        };
        TitleBar.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = chrome.TitleBackground,
            BorderColor = chrome.WindowBorder,
            BorderThickness = new Thickness(0, 0, 0, 1),
        };
        TitleLabel.FontColorOverride = chrome.TitleText;
        PopChromeButton.OnPressed += _ => PopOut();
        CloseChromeButton.OnPressed += _ => Close();

        StatusStrip.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = shell.Background,
            BorderColor = shell.AccentDim,
            BorderThickness = new Thickness(1),
        };
        StatusLabel.FontColorOverride = shell.Text;
        JammedLabel.FontColorOverride = shell.Warning;

        RadarTabButton.OnPressed += _ => SwitchTab(KsInstrumentTab.Radar);
        MapTabButton.OnPressed += _ => SwitchTab(KsInstrumentTab.Map);
        EsmTabButton.OnPressed += _ => SwitchTab(KsInstrumentTab.Esm);
        DockTabButton.OnPressed += _ => SwitchTab(KsInstrumentTab.Dock);

        // Tabs are exclusive.
        var group = new ButtonGroup();
        RadarTabButton.Group = group;
        MapTabButton.Group = group;
        EsmTabButton.Group = group;
        DockTabButton.Group = group;

        RadarTabButton.Pressed = true;
        SetupTab(_tab);

        _bootStartedAt = _timing.CurTime;

        MapContainer.RequestFTL += (coords, angle) => RequestFTL?.Invoke(coords, angle);
        MapContainer.RequestBeaconFTL += (ent, angle) => RequestBeaconFTL?.Invoke(ent, angle);
        DockContainer.DockRequest += (entity, netEntity) => DockRequest?.Invoke(entity, netEntity);
        DockContainer.UndockRequest += entity => UndockRequest?.Invoke(entity);

        RadarContainer.OnToggleRadar += () => RequestToggleRadar?.Invoke();
        RadarContainer.OnToggleJammer += () => RequestToggleJammer?.Invoke();

        EsmContainer.OnFocusRequest += target => RequestElintFocus?.Invoke(target);
        EsmContainer.OnClearFocusRequest += () => RequestElintClearFocus?.Invoke();
    }

    /// <summary>
    ///     Moves the suite into its own resizable OS window: a second ClydeWindow with
    ///         its own UI root, so rendering, input and FrameUpdate all follow
    ///         automatically because the engine iterates every root. Orphan, NEVER
    ///         Close(): Close raises OnClose, which the hosting BUI reads as "close
    ///         the console UI".
    /// </summary>
    private void PopOut()
    {
        if (_popoutWindow != null || Parent == null)
            return;

        _prePopSetSize = SetSize;
        var pixelSize = PixelSize;

        // Create the OS window BEFORE orphaning: if the driver/compositor refuses a
        // second window, the suite must stay where it is instead of vanishing.
        _popoutWindow = _clyde.CreateWindow(new WindowCreateParameters
        {
            Title = Loc.GetString("ks-instrument-window-title"),
            Width = Math.Max(pixelSize.X, (int) MinSize.X),
            Height = Math.Max(pixelSize.Y, (int) MinSize.Y),
        });
        // We re-home the suite on close instead of letting the engine dispose the
        // window under us.
        _popoutWindow.DisposeOnClose = false;
        _popoutWindow.RequestClosed += OnPopoutRequestClosed;

        Orphan();

        _popoutRoot = UserInterfaceManager.CreateWindowRoot(_popoutWindow);
        // Without the root controls (popup/tooltip/modal layers) the first tooltip
        // shown in the popped window throws. Vanilla ahelp has this latent bug.
        _popoutRoot.CreateRootControls();
        _popoutRoot.AddChild(this);
        // Below the root's popup/tooltip layers, or tooltips draw UNDER the opaque
        // suite (the OSWindow.Create ordering).
        SetPositionFirst();

        // The OS chrome owns drag/resize/close now (secondary windows are always
        // resizable); our title bar and edge handling come back on pop-in, and the
        // cleared SetSize lets the suite stretch-fill the OS window.
        TitleBar.Visible = false;
        SetSize = new Vector2(float.NaN, float.NaN);
    }

    private void OnPopoutRequestClosed(WindowRequestClosedEventArgs args)
    {
        PopIn();
    }

    /// <summary>Brings the suite back into the game window and destroys the OS window.</summary>
    private void PopIn()
    {
        if (_popoutWindow == null)
            return;

        TearDownPopout();

        TitleBar.Visible = true;
        SetSize = _prePopSetSize;
        UserInterfaceManager.WindowRoot.AddChild(this);
        Measure(Vector2Helpers.Infinity);
        RecenterWindow(new Vector2(0.5f, 0.5f));
    }

    /// <summary>
    ///     Destroys the popped-out OS window WITHOUT re-homing the suite. The BUI
    ///         calls this when the console UI dies while popped; without it the OS
    ///         window leaks and keeps floating stale (the vanilla ahelp/admin-camera
    ///         popout bug). Disposing the ClydeWindow also unhooks the
    ///         (already-emptied) root from engine tracking; the orphaned root itself
    ///         is plain managed memory.
    /// </summary>
    public void TearDownPopout()
    {
        if (_popoutWindow is not { } osWindow)
            return;

        osWindow.RequestClosed -= OnPopoutRequestClosed;
        // A disposed control (BUI teardown races) must not re-orphan (it would
        // assert), but the OS window still has to die either way.
        if (!Disposed)
            Orphan();
        osWindow.Dispose();
        _popoutWindow = null;
        _popoutRoot = null;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        // Base's MoveToFront would hoist the suite above the popout root's
        // popup/tooltip layers on every click; while popped out it must stay the
        // bottom-most root child instead.
        if (_popoutWindow != null)
            SetPositionFirst();
    }

    /// <summary>
    ///     FancyWindow's drag feel, reimplemented since the shell is a bare
    ///         BaseWindow: edges resize (when resizable), everything else moves.
    ///         While popped out the OS chrome owns both, so nothing drags.
    /// </summary>
    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        if (_popoutWindow != null)
            return DragMode.None;

        var mode = DragMode.Move;

        if (!Resizable)
            return mode;

        if (relativeMousePos.Y < DragMarginSize)
            mode = DragMode.Top;
        else if (relativeMousePos.Y > Size.Y - DragMarginSize)
            mode = DragMode.Bottom;

        if (relativeMousePos.X < DragMarginSize)
            mode |= DragMode.Left;
        else if (relativeMousePos.X > Size.X - DragMarginSize)
            mode |= DragMode.Right;

        return mode;
    }

    private void ClearTabs(KsInstrumentTab tab)
    {
        if (tab != KsInstrumentTab.Radar)
            RadarContainer.Visible = false;

        if (tab != KsInstrumentTab.Map)
        {
            MapContainer.Visible = false;
            MapContainer.SetMap(MapId.Nullspace, Vector2.Zero);
        }

        if (tab != KsInstrumentTab.Esm)
            EsmContainer.Visible = false;

        if (tab != KsInstrumentTab.Dock)
            DockContainer.Visible = false;
    }

    private void SetupTab(KsInstrumentTab tab)
    {
        switch (tab)
        {
            case KsInstrumentTab.Radar:
                RadarContainer.Visible = true;
                break;
            case KsInstrumentTab.Map:
                MapContainer.Visible = true;
                MapContainer.Startup();
                break;
            case KsInstrumentTab.Esm:
                EsmContainer.Visible = true;
                break;
            case KsInstrumentTab.Dock:
                DockContainer.Visible = true;
                break;
            default:
                throw new NotImplementedException();
        }
    }

    private void SwitchTab(KsInstrumentTab tab)
    {
        if (_tab == tab)
            return;

        _tab = tab;
        // A real click before the first state wins over the parked restore.
        _pendingTab = null;
        if (_prefs != null)
            _prefs.Tab = tab;
        ClearTabs(tab);
        SetupTab(tab);
        _tabSwitchedAt = _timing.CurTime;
    }

    /// <summary>
    ///     Rebinds the shell and its screens to the console's remembered switch
    ///         positions. The BUI calls this on open, before the first state lands,
    ///         so the face never flashes its defaults first.
    /// </summary>
    public void KsLoadPrefs(EntityUid console)
    {
        _prefs = _entManager.System<KsConsolePrefsSystem>().For(console);
        RadarContainer.KsLoadPrefs(_prefs);
        MapContainer.KsLoadPrefs(_prefs);

        // The tab itself waits for the first state: switching to MAP runs the
        // chart's Startup, which centres on a shuttle this window has not been
        // told about yet. The boot flicker hides the one-frame default tab.
        _pendingTab = _prefs.Tab;
    }

    public void UpdateState(EntityUid owner, ShuttleBoundUserInterfaceState cState)
    {
        var coordinates = _entManager.GetCoordinates(cState.NavState.Coordinates);
        RadarContainer.SetShuttle(coordinates?.EntityId);
        RadarContainer.SetConsole(owner);
        MapContainer.SetShuttle(coordinates?.EntityId);
        MapContainer.SetConsole(owner);
        EsmContainer.SetShuttle(coordinates?.EntityId);

        if (_pendingTab is { } pending)
        {
            _pendingTab = null;
            var button = pending switch
            {
                KsInstrumentTab.Map => MapTabButton,
                KsInstrumentTab.Esm => EsmTabButton,
                KsInstrumentTab.Dock => DockTabButton,
                _ => RadarTabButton,
            };
            button.Pressed = true;
            SwitchTab(pending);
        }

        RadarContainer.UpdateState(cState.NavState);
        MapContainer.UpdateState(cState.MapState);
        MapContainer.KsSetContacts(cState.NavState.KsSensorNav?.Contacts); // for map fog of war
        MapContainer.KsSetSensorNav(cState.NavState.KsSensorNav); // for the chart's SENSORS overlay
        EsmContainer.UpdateState(cState.NavState);
        DockContainer.UpdateState(coordinates?.EntityId, cState.DockState);

        UpdateStatusStrip(cState.NavState.KsSensorNav);
    }

    /// <summary>
    ///     The one-line shell readout under every tab, so the picture's essentials
    ///         survive on whatever screen the crew is watching.
    /// </summary>
    private void UpdateStatusStrip(KsSensorNavState? nav)
    {
        var contacts = nav?.Contacts?.Count ?? 0;
        var emitters = nav?.Contacts?.Count(c => c.Designation != null) ?? 0;

        var radar = nav is not { HasRadar: true }
            ? Loc.GetString("ks-instrument-status-radar-none")
            : Loc.GetString(nav.RadarActive ? "ks-instrument-status-radar-on" : "ks-instrument-status-radar-off");
        var jammer = nav is not { HasJammer: true }
            ? Loc.GetString("ks-instrument-status-jammer-none")
            : Loc.GetString(nav.JammerActive ? "ks-instrument-status-jammer-on" : "ks-instrument-status-jammer-off");

        var separator = $" {Loc.GetString("ks-instrument-tab-separator")} ";
        // An explicit array, not the params call: the params-span overload makes the
        // compiler emit an inline array, which the Robust sandbox's IL verifier
        // rejects (same family as non-empty collection expressions on List fields).
        StatusLabel.Text = string.Join(separator, new[]
        {
            Loc.GetString("ks-instrument-status-contacts", ("count", $"{contacts:00}")),
            Loc.GetString("ks-instrument-status-emitters", ("count", $"{emitters:00}")),
            radar,
            jammer,
        });

        JammedLabel.Visible = nav?.Jammed ?? false;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var reduced = _cfg.GetCVar(KsCCVars.HudReducedMotion);

        UpdateEsmTabAlert(reduced);

        // Power-on boot flicker: wins over the tab flicker while it runs;
        // reduce-motion (or a zero duration) skips straight to full brightness.
        if (_bootStartedAt != TimeSpan.MinValue)
        {
            var bootSince = (_timing.CurTime - _bootStartedAt).TotalSeconds;
            if (bootSince < Hud.BootDuration && !reduced)
            {
                var progress = (float) (bootSince / Hud.BootDuration);
                var flicker = Hud.Boot.Eval(bootSince, reducedMotion: false);
                // The blink rides a rising envelope: dark strobing at first,
                // settling to full brightness as the boot completes.
                var value = progress * MathHelper.Lerp(flicker, 1f, progress);
                Contents.Modulate = Color.White.WithAlpha(Math.Clamp(value, 0f, 1f));
                return;
            }

            Contents.Modulate = Color.White;
            _bootStartedAt = TimeSpan.MinValue;
        }

        // Purely cosmetic interlace flicker on a tab switch: it modulates the whole
        // screen host and settles to full brightness.
        if (_tabSwitchedAt == TimeSpan.MinValue)
            return;

        var since = (_timing.CurTime - _tabSwitchedAt).TotalSeconds;
        if (since < Hud.TabFlickerDuration && !reduced)
        {
            var flicker = Hud.TabFlicker.Eval(since, reducedMotion: false);
            Contents.Modulate = Color.White.WithAlpha(Math.Clamp(flicker, 0f, 1f));
        }
        else
        {
            Contents.Modulate = Color.White;
            _tabSwitchedAt = TimeSpan.MinValue;
        }
    }

    /// <summary>
    ///     The master caution light: while the ESM screen holds live threats its tab
    ///         button strobes the posture colour at the priority channel's rate, so a
    ///         crew watching any other screen still sees the warning. Reduced motion
    ///         holds the colour steady instead of blinking.
    /// </summary>
    private void UpdateEsmTabAlert(bool reduced)
    {
        if (EsmContainer.AlertPosture is not { } posture)
        {
            EsmTabButton.Label.FontColorOverride = null;
            return;
        }

        var v = Hud.ThreatStrobe.Eval(_timing.CurTime.TotalSeconds, reduced, EsmContainer.AlertBlinkHz);
        var c = posture.Color;
        EsmTabButton.Label.FontColorOverride = new Color(c.R * v, c.G * v, c.B * v, c.A);
    }
}
