using System.Linq;
using System.Numerics;
using Content.Client._KS14.Sensors;
using Content.Shared._KS14.Sensors;
using Content.Shared._KS14.Sensors.Prototypes;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;

namespace Content.Client._KS14.Shuttles.UI;

/// <summary>
///     The KS14 RADAR instrument screen: the fork counterpart of the upstream
///         NavScreen, hosting a <see cref="KsRadarControl"/> plus the ship readouts,
///         the threat/posture status panel (client-derived exactly like the ESM tab's
///         warning box, same RWR-fit gate and same <see cref="KsThreatEval"/>, so the
///         two instruments always agree), the emission toggles and the per-type
///         coverage-cone display controls.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class KsNavScreen : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _protoManager = default!;
    private readonly SharedTransformSystem _xformSystem;

    private KsSensorHudPrototype? _hud;
    private KsSensorHudPrototype Hud => _hud ??= _protoManager.Index(KsSensorHudPrototype.DefaultId);
    private KsInstrumentPalette Palette => Hud.GetScreen("radar");

    /// <summary>Channels by descending priority, fixed for the session like the HUD palette.</summary>
    private readonly List<KsThreatChannelPrototype> _channels;

    /// <summary>Postures by descending severity; the first met one shows.</summary>
    private readonly List<KsPosturePrototype> _postures;

    private EntityUid? _consoleEntity;
    private EntityUid? _shuttleEntity;

    /// <summary>The console's remembered switch positions; null until the shell binds them.</summary>
    private KsConsoleUiPrefs? _prefs;

    /// <summary>Radar on/off request; the console BUI sends the server message.</summary>
    public event Action? OnToggleRadar;

    /// <summary>Jammer on/off request; the console BUI sends the server message.</summary>
    public event Action? OnToggleJammer;

    public KsNavScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xformSystem = _entManager.System<SharedTransformSystem>();

        KsInstrumentSheetlet.MakeInstrument(
            RadarEmitToggle, JammerEmitToggle, DockToggle,
            SensorCoverageVisualToggle, SensorCoverageIrstToggle,
            SensorCoverageRadarToggle, SensorCoverageJammerToggle,
            SensorInfoToggle);

        _channels = _protoManager.EnumeratePrototypes<KsThreatChannelPrototype>()
            .OrderByDescending(c => c.Priority)
            .ThenBy(c => c.ID, StringComparer.Ordinal)
            .ToList();
        _postures = _protoManager.EnumeratePrototypes<KsPosturePrototype>()
            .OrderByDescending(p => p.Order)
            .ToList();

        PlotPanel.Title = Loc.GetString("ks-radar-panel-plot");
        ShipPanel.Title = Loc.GetString("ks-radar-panel-ship");
        StatusPanel.Title = Loc.GetString("ks-radar-panel-status");
        EmissionsPanel.Title = Loc.GetString("ks-radar-panel-emissions");
        DisplayPanel.Title = Loc.GetString("ks-radar-panel-display");

        var palette = Palette;
        foreach (var panel in new[] { PlotPanel, ShipPanel, StatusPanel, EmissionsPanel, DisplayPanel })
        {
            panel.Accent = palette.Accent;
            panel.Background = palette.Background;
        }

        foreach (var value in new[] { GridPosition, GridOrientation, GridLinearVelocity, GridAngularVelocity, ThreatsValue, ContactsValue, EmittersValue })
        {
            value.FontColorOverride = palette.Text;
        }

        NavRadar.KsPalette = palette;

        DockToggle.OnToggled += OnDockTogglePressed;
        DockToggle.Pressed = NavRadar.ShowDocks;

        RadarEmitToggle.OnPressed += _ => OnToggleRadar?.Invoke();
        JammerEmitToggle.OnPressed += _ => OnToggleJammer?.Invoke();

        // Each sensor type's coverage cone cycles off -> outline -> filled.
        SensorCoverageVisualToggle.OnPressed += _ => CycleCoverage(KsSensorType.VisualSearch, SensorCoverageVisualToggle, "ks-sensor-coverage-visual-toggle");
        SensorCoverageIrstToggle.OnPressed += _ => CycleCoverage(KsSensorType.IRST, SensorCoverageIrstToggle, "ks-sensor-coverage-irst-toggle");
        SensorCoverageRadarToggle.OnPressed += _ => CycleCoverage(KsSensorType.Radar, SensorCoverageRadarToggle, "ks-sensor-coverage-radar-toggle");
        SensorCoverageJammerToggle.OnPressed += _ => CycleCoverage(KsSensorType.Jammer, SensorCoverageJammerToggle, "ks-sensor-coverage-jammer-toggle");
        UpdateCoverageButton(KsSensorType.VisualSearch, SensorCoverageVisualToggle, "ks-sensor-coverage-visual-toggle");
        UpdateCoverageButton(KsSensorType.IRST, SensorCoverageIrstToggle, "ks-sensor-coverage-irst-toggle");
        UpdateCoverageButton(KsSensorType.Radar, SensorCoverageRadarToggle, "ks-sensor-coverage-radar-toggle");
        UpdateCoverageButton(KsSensorType.Jammer, SensorCoverageJammerToggle, "ks-sensor-coverage-jammer-toggle");

        // Contact text cycles none -> basic -> full, like the coverage cones: a busy
        // plot is usually readable at basic long before it needs blanking entirely.
        SensorInfoToggle.OnPressed += _ => CycleReadoutDetail();
        UpdateReadoutDetailButton();

        // The scope zoom is an instrument knob too. WorldRangeChanged reports
        // the lerped display value, which mid-glide is not what the crew
        // dialled - and a tab switch freezes that lerp, since a hidden control
        // stops drawing. Persist the wheel's target instead; the event is just
        // the "zoom changed" edge.
        NavRadar.WorldRangeChanged += _ =>
        {
            if (_prefs != null)
                _prefs.RadarRange = NavRadar.KsTargetRange;
        };

        RefreshStatus(null);
    }

    /// <summary>Puts every display switch back where this console's crew left it.</summary>
    public void KsLoadPrefs(KsConsoleUiPrefs prefs)
    {
        _prefs = prefs;

        NavRadar.ShowDocks = prefs.ShowDocks;
        DockToggle.Pressed = prefs.ShowDocks;

        foreach (var (type, mode) in prefs.CoverageModes)
        {
            NavRadar.KsCoverageModes[type] = mode;
        }
        UpdateCoverageButton(KsSensorType.VisualSearch, SensorCoverageVisualToggle, "ks-sensor-coverage-visual-toggle");
        UpdateCoverageButton(KsSensorType.IRST, SensorCoverageIrstToggle, "ks-sensor-coverage-irst-toggle");
        UpdateCoverageButton(KsSensorType.Radar, SensorCoverageRadarToggle, "ks-sensor-coverage-radar-toggle");
        UpdateCoverageButton(KsSensorType.Jammer, SensorCoverageJammerToggle, "ks-sensor-coverage-jammer-toggle");

        NavRadar.KsReadoutDetail = prefs.ReadoutDetail;
        UpdateReadoutDetailButton();

        if (prefs.RadarRange is { } range)
            NavRadar.KsRestoreRange(range);
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;
    }

    public void SetConsole(EntityUid? console)
    {
        _consoleEntity = console;
        NavRadar.SetConsole(console);
    }

    private void OnDockTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowDocks ^= true;
        args.Button.Pressed = NavRadar.ShowDocks;
        if (_prefs != null)
            _prefs.ShowDocks = NavRadar.ShowDocks;
    }

    private void CycleCoverage(KsSensorType type, Button button, string locId)
    {
        var mode = NavRadar.KsCoverageModes.GetValueOrDefault(type, KsCoverageDisplayMode.Outline);
        mode = (KsCoverageDisplayMode)(((int)mode + 1) % 3);
        NavRadar.KsCoverageModes[type] = mode;
        if (_prefs != null)
            _prefs.CoverageModes[type] = mode;
        UpdateCoverageButton(type, button, locId);
    }

    private void UpdateCoverageButton(KsSensorType type, Button button, string locId)
    {
        var mode = NavRadar.KsCoverageModes.GetValueOrDefault(type, KsCoverageDisplayMode.Outline);
        var modeText = Loc.GetString(mode switch
        {
            KsCoverageDisplayMode.Off => "ks-sensor-coverage-mode-off",
            KsCoverageDisplayMode.Outline => "ks-sensor-coverage-mode-outline",
            _ => "ks-sensor-coverage-mode-filled",
        });
        button.Text = Loc.GetString(locId, ("mode", modeText));
    }

    private void CycleReadoutDetail()
    {
        NavRadar.KsReadoutDetail = (KsContactDetail)(((int)NavRadar.KsReadoutDetail + 1) % 3);
        if (_prefs != null)
            _prefs.ReadoutDetail = NavRadar.KsReadoutDetail;
        UpdateReadoutDetailButton();
    }

    private void UpdateReadoutDetailButton()
    {
        var modeText = Loc.GetString(NavRadar.KsReadoutDetail switch
        {
            KsContactDetail.None => "ks-sensor-info-mode-off",
            KsContactDetail.Basic => "ks-sensor-info-mode-basic",
            _ => "ks-sensor-info-mode-full",
        });
        SensorInfoToggle.Text = Loc.GetString("ks-sensor-info-toggle", ("mode", modeText));
    }

    public void UpdateState(NavInterfaceState scc)
    {
        NavRadar.UpdateState(scc);

        RadarEmitToggle.Visible = scc.KsSensorNav?.HasRadar ?? false;
        RadarEmitToggle.Text = Loc.GetString(scc.KsSensorNav?.RadarActive == true
            ? "ks-sensor-radar-toggle-on"
            : "ks-sensor-radar-toggle-off");

        JammerEmitToggle.Visible = scc.KsSensorNav?.HasJammer ?? false;
        JammerEmitToggle.Text = Loc.GetString(scc.KsSensorNav?.JammerActive == true
            ? "ks-sensor-jammer-toggle-on"
            : "ks-sensor-jammer-toggle-off");

        RefreshStatus(scc.KsSensorNav);
    }

    /// <summary>
    ///     The STATUS panel: posture and threat count derived exactly like the ESM
    ///         tab's warning box via the shared <see cref="KsThreatEval"/> (same
    ///         RWR-fit gate, so without an RWR receiver both instruments go dim rather
    ///         than disagreeing), plus the live/total contact count and the
    ///         designated-emitter count.
    /// </summary>
    private void RefreshStatus(KsSensorNavState? nav)
    {
        var palette = Palette;
        var contacts = nav?.Contacts;
        var hasRwr = nav?.HasRwr ?? false;

        var total = contacts?.Count ?? 0;
        var live = 0;
        var emitters = 0;
        var threats = 0;
        int? litPriority = null;

        if (contacts != null)
        {
            foreach (var contact in contacts)
            {
                if (contact.Live)
                    live++;
                if (contact.Designation != null)
                    emitters++;

                if (!hasRwr || contact.Designation == null || !contact.EmitterLive)
                    continue;

                threats++;
                if (KsThreatEval.MatchChannel(contact, _channels) is { } channel
                    && (litPriority is not { } lit || channel.Priority > lit))
                {
                    litPriority = channel.Priority;
                }
            }
        }

        if (hasRwr)
        {
            var posture = KsThreatEval.PickPosture(_postures, threats, litPriority);
            PostureValue.Text = posture != null ? Loc.GetString(posture.Label) : Loc.GetString("ks-radar-field-no-value");
            PostureValue.FontColorOverride = posture?.Color ?? palette.TextDim;

            ThreatsValue.Text = $"{threats:00}";
            ThreatsValue.FontColorOverride = threats > 0 ? palette.Warning : palette.Text;
        }
        else
        {
            PostureValue.Text = Loc.GetString("ks-radar-field-no-value");
            PostureValue.FontColorOverride = palette.TextDim;
            ThreatsValue.Text = Loc.GetString("ks-radar-field-no-value");
            ThreatsValue.FontColorOverride = palette.TextDim;
        }

        ContactsValue.Text = Loc.GetString("ks-radar-field-contacts-value", ("live", $"{live:00}"), ("total", $"{total:00}"));
        EmittersValue.Text = $"{emitters:00}";
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        _shuttleEntity = coordinates?.EntityId;
        NavRadar.SetMatrix(coordinates, angle);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (!_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? gridXform) ||
            !_entManager.TryGetComponent(_shuttleEntity, out PhysicsComponent? gridBody))
        {
            return;
        }

        var (_, worldRot, worldMatrix) = _xformSystem.GetWorldPositionRotationMatrix(gridXform);
        var worldPos = Vector2.Transform(gridBody.LocalCenter, worldMatrix);

        // Get the positive reduced angle.
        var displayRot = -worldRot.Reduced();

        GridPosition.Text = Loc.GetString("shuttle-console-position-value",
            ("X", $"{worldPos.X:0.0}"),
            ("Y", $"{worldPos.Y:0.0}"));
        GridOrientation.Text = Loc.GetString("shuttle-console-orientation-value",
            ("angle", $"{displayRot.Degrees:0.0}"));

        var gridVelocity = gridBody.LinearVelocity;
        gridVelocity = displayRot.RotateVec(gridVelocity);
        // Get linear velocity relative to the console entity
        GridLinearVelocity.Text = Loc.GetString("shuttle-console-linear-velocity-value",
            ("X", $"{gridVelocity.X + 10f * float.Epsilon:0.0}"),
            ("Y", $"{gridVelocity.Y + 10f * float.Epsilon:0.0}"));
        GridAngularVelocity.Text = Loc.GetString("shuttle-console-angular-velocity-value",
            ("angularVelocity", $"{-MathHelper.RadiansToDegrees(gridBody.AngularVelocity) + 10f * float.Epsilon:0.0}"));
    }
}
