using System.Numerics;
using Content.Client._KS14.Sensors;
using Content.Client.Resources;
using Content.Client.Shuttles.UI;
using Content.Shared._KS14.CCVar;
using Content.Shared._KS14.RadarInterest;
using Content.Shared._KS14.Sensors;
using Content.Shared._KS14.Sensors.Prototypes;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._KS14.Shuttles.UI;

/// <summary>
///     The KS14 shuttle/radar console display. Keeps the grid, ring and coordinate
///         machinery of <see cref="BaseShuttleControl"/> but renders foreign grids
///         purely from the sensor contact picture (full fog of war) instead of the
///         vanilla "draw every CanDraw grid" loop, so a ship only appears once a
///         sensor tracks it. Forked so upstream <see cref="ShuttleNavControl"/>
///         carries no sensor code.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class KsRadarControl : BaseShuttleControl
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IMapManager _mapManager = default!;
    private readonly SharedShuttleSystem _shuttles;
    private readonly SharedTransformSystem _transform;
    private readonly KsRadarInterestSystem _radarInterestSystem;
    private readonly IPrototypeManager _protoManager;
    private readonly IGameTiming _timing;

    /// <summary>
    ///     The pixel-terminal font used for every KS-drawn string instead of the
    ///         inherited NotoSans <c>Font</c>. A parallel field, not an override,
    ///         because the base field is readonly.
    /// </summary>
    private readonly Font _ksFont;

    /// <summary>Transforms all radar objects. Typically a shuttle console parented to a grid.</summary>
    private EntityCoordinates? _coordinates;

    private EntityUid? _consoleEntity;

    private Angle? _rotation;

    private Dictionary<NetEntity, List<DockingPortState>> _docks = new();

    public bool ShowDocks { get; set; } = true;
    public bool RotateWithEntity { get; set; } = true;

    /// <summary>Per-sensor-type coverage-fan display mode (off / outline / filled), cycled from the toggle buttons.</summary>
    public Dictionary<KsSensorType, KsCoverageDisplayMode> KsCoverageModes { get; } = new()
    {
        [KsSensorType.VisualSearch] = KsCoverageDisplayMode.Outline,
        [KsSensorType.IRST] = KsCoverageDisplayMode.Outline,
        [KsSensorType.Radar] = KsCoverageDisplayMode.Outline,
        [KsSensorType.Elint] = KsCoverageDisplayMode.Outline,
        [KsSensorType.Rwr] = KsCoverageDisplayMode.Outline,
        [KsSensorType.Jammer] = KsCoverageDisplayMode.Outline,
    };

    /// <summary>
    ///     How much of the per-contact text readout (name, coords, range, intel) to
    ///         draw. Which lines survive a cutback is prototype data, not code: see
    ///         <see cref="KsSensorIntelPrototype.Detail"/> and the HUD prototype's
    ///         name/position/age levels.
    /// </summary>
    public KsContactDetail KsReadoutDetail { get; set; } = KsContactDetail.Full;

    public Action<EntityCoordinates>? OnRadarClick;

    private List<Entity<MapGridComponent>> _grids = new();

    private List<KsSensorContactState>? _ksContacts;
    private List<KsSensorRegionState>? _ksSensorRegions;
    private bool _ksJammed;
    private readonly HashSet<NetEntity> _ksLiveContacts = new();
    private readonly HashSet<NetEntity> _ksRealDrawn = new();
    private readonly List<(Vector2 ScreenPos, KsSensorContactState Contact)> _ksContactHits = new();
    private Vector2? _ksMousePos;
    private List<KsSensorIntelPrototype>? _ksIntelRoster;

    /// <summary>Liveness edge detector driving the contact ping and the ghost fade.</summary>
    private readonly KsContactTransitions _ksTransitions = new();

    /// <summary>
    ///     Themes the instrument face only (background, range rings, ring labels).
    ///         Contact and cone colours stay per-sensor-tier from the HUD prototype.
    /// </summary>
    public KsInstrumentPalette KsPalette { get; set; } = new();

    /// <summary>
    ///     The radar HUD colour/animation theme from YAML. Lazy so the prototype manager
    ///         is ready; fixed for a session, like <see cref="_ksIntelRoster"/>.
    /// </summary>
    private KsSensorHudPrototype? _ksHud;
    private KsSensorHudPrototype KsHud => _ksHud ??= _protoManager.Index(KsSensorHudPrototype.DefaultId);

    // (minRange, maxRange, defaultRange) in metres. maxRange is re-applied from the
    // console's RadarConsole.MaxRange every UpdateState; 512 here only keeps the
    // pre-first-state cap in step with the KS console prototypes.
    public KsRadarControl() : base(64f, 512f, 256f)
    {
        RobustXamlLoader.Load(this);
        _shuttles = EntManager.System<SharedShuttleSystem>();
        _transform = EntManager.System<SharedTransformSystem>();
        _radarInterestSystem = EntManager.System<KsRadarInterestSystem>();
        _protoManager = IoCManager.Resolve<IPrototypeManager>();
        _timing = IoCManager.Resolve<IGameTiming>();
        _ksFont = IoCManager.Resolve<IResourceCache>()
            .GetFont(KsInstrumentSheetlet.FontPath, KsInstrumentSheetlet.FontSizeBody + 2);
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        _coordinates = coordinates;
        _rotation = angle;
    }

    public void SetConsole(EntityUid? consoleEntity)
    {
        _consoleEntity = consoleEntity;
    }

    /// <summary>
    ///     The wheel's zoom target, exposed for the prefs write-through: the public
    ///         WorldRange is the lerped display value, which mid-glide is not what
    ///         the crew dialled.
    /// </summary>
    public float KsTargetRange => ActualRadarRange;

    /// <summary>
    ///     Restores a remembered zoom in one step: setting WorldRange alongside the
    ///         target skips the wheel lerp, so a reopened console snaps to its old
    ///         range instead of visibly gliding there.
    /// </summary>
    public void KsRestoreRange(float range)
    {
        ActualRadarRange = Math.Clamp(range, WorldMinRange, WorldMaxRange);
        WorldRange = ActualRadarRange;
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (_coordinates == null || _rotation == null || args.Function != EngineKeyFunctions.UIClick ||
            OnRadarClick == null)
        {
            return;
        }

        var a = InverseScalePosition(args.RelativePosition);
        var relativeWorldPos = new Vector2(a.X, -a.Y);
        relativeWorldPos = _rotation.Value.RotateVec(relativeWorldPos);
        var coords = _coordinates.Value.Offset(relativeWorldPos);
        OnRadarClick?.Invoke(coords);
    }

    [PublicAPI]
    public EntityCoordinates GetMouseCoordinates(ScreenCoordinates screen)
    {
        if (_coordinates == null || _rotation == null)
        {
            return EntityCoordinates.Invalid;
        }

        var pos = screen.Position / UIScale - GlobalPosition;

        var a = InverseScalePosition(pos);
        var relativeWorldPos = new Vector2(a.X, -a.Y);
        relativeWorldPos = _rotation.Value.RotateVec(relativeWorldPos);
        var coords = _coordinates.Value.Offset(relativeWorldPos);
        return coords;
    }

    public void UpdateState(NavInterfaceState state)
    {
        SetMatrix(EntManager.GetCoordinates(state.Coordinates), state.Angle);

        WorldMaxRange = state.MaxRange;

        if (WorldMaxRange < WorldRange)
        {
            ActualRadarRange = WorldMaxRange;
        }

        if (WorldMaxRange < WorldMinRange)
            WorldMinRange = WorldMaxRange;

        ActualRadarRange = Math.Clamp(ActualRadarRange, WorldMinRange, WorldMaxRange);

        RotateWithEntity = state.RotateWithEntity;

        _docks = state.Docks;

        // Sensor contacts are the sole source of foreign-grid visibility. A null
        // sensor picture (no coverage) reads back as the old all-null/false defaults.
        _ksContacts = state.KsSensorNav?.Contacts;
        _ksSensorRegions = state.KsSensorNav?.Regions;
        _ksJammed = state.KsSensorNav?.Jammed ?? false;
        _ksTransitions.Update(_ksContacts, _timing.CurTime);
        _ksLiveContacts.Clear();
        if (_ksContacts != null)
        {
            foreach (var contact in _ksContacts)
            {
                // Real-hull gate: only an Exact-quality live track may draw the actual
                // grid. Letting a bearing track draw the PVS-replicated hull would put
                // the target at its true position and leak what the server withheld.
                if (contact.Live && contact.Quality == KsPositionQuality.Exact)
                    _ksLiveContacts.Add(contact.Grid);
            }
        }
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        KsDrawInstrumentFace(handle);

        // Drawn before the nav picture so it survives when jamming has left the radar
        // with nothing to show.
        KsDrawJammedIndicator(handle);

        if (_coordinates == null || _rotation == null)
        {
            return;
        }

        var xformQuery = EntManager.GetEntityQuery<TransformComponent>();
        var fixturesQuery = EntManager.GetEntityQuery<FixturesComponent>();

        if (!xformQuery.TryGetComponent(_coordinates.Value.EntityId, out var xform)
            || xform.MapID == MapId.Nullspace)
        {
            return;
        }

        var mapPos = _transform.ToMapCoordinates(_coordinates.Value);
        var posMatrix = Matrix3Helpers.CreateTransform(_coordinates.Value.Position, _rotation.Value);
        var ourEntRot = RotateWithEntity ? _transform.GetWorldRotation(xform) : _rotation.Value;
        var ourEntMatrix = Matrix3Helpers.CreateTransform(_transform.GetWorldPosition(xform), ourEntRot);
        var shuttleToWorld = Matrix3x2.Multiply(posMatrix, ourEntMatrix);
        Matrix3x2.Invert(shuttleToWorld, out var worldToShuttle);
        var shuttleToView = Matrix3x2.CreateScale(new Vector2(MinimapScale, -MinimapScale)) * Matrix3x2.CreateTranslation(MidPointVector);

        var ourGridId = xform.GridUid;
        if (EntManager.TryGetComponent<MapGridComponent>(ourGridId, out var ourGrid))
        {
            var ourGridToWorld = _transform.GetWorldMatrix(ourGridId.Value);
            var ourGridToShuttle = Matrix3x2.Multiply(ourGridToWorld, worldToShuttle);
            var ourGridToView = ourGridToShuttle * shuttleToView;
            var color = _shuttles.GetIFFColor(ourGridId.Value, self: true);

            KsDrawInterests(handle, ourGridToView, new Box2(mapPos.Position - MaxRadarRangeVector, mapPos.Position + MaxRadarRangeVector), (ourGridId.Value, ourGrid));

            // Coverage fans, under the hull and contacts.
            KsDrawSensorRegions(handle, ourGridToView, worldToShuttle * shuttleToView, EntManager.GetNetEntity(ourGridId.Value));

            if (fixturesQuery.HasComponent(ourGridId.Value))
            {
                DrawGrid(handle, ourGridToView, (ourGridId.Value, ourGrid), color);
                DrawDocks(handle, ourGridId.Value, ourGridToView);
            }
        }

        const float radarVertRadius = 2f;
        var radarPosVerts = new Vector2[]
        {
            ScalePosition(new Vector2(0f, -radarVertRadius)),
            ScalePosition(new Vector2(radarVertRadius / 2f, 0f)),
            ScalePosition(new Vector2(0f, radarVertRadius)),
            ScalePosition(new Vector2(radarVertRadius / -2f, 0f)),
        };

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, radarPosVerts, KsHud.SelfPosition);

        var rot = ourEntRot + _rotation.Value;
        var viewBounds = new Box2Rotated(new Box2(-WorldRange, -WorldRange, WorldRange, WorldRange).Translated(mapPos.Position), rot, mapPos.Position);
        var viewAABB = viewBounds.CalcBoundingBox();

        _grids.Clear();
        _mapManager.FindGridsIntersecting(xform.MapID, new Box2(mapPos.Position - MaxRadarRangeVector, mapPos.Position + MaxRadarRangeVector), ref _grids, approx: true, includeMap: false);

        _ksRealDrawn.Clear();

        // Full fog of war: a foreign grid renders as a real hull only when the console's
        // grid has a live sensor track on it; everything else is the contact layer's job.
        // Replaces the vanilla CanDraw/IFF loop, so IFF hiding no longer gates rendering.
        foreach (var grid in _grids)
        {
            var gUid = grid.Owner;
            if (gUid == ourGridId || !fixturesQuery.HasComponent(gUid))
                continue;

            var ksGridNet = EntManager.GetNetEntity(gUid);
            if (!_ksLiveContacts.Contains(ksGridNet))
                continue;

            _ksRealDrawn.Add(ksGridNet);

            EntManager.TryGetComponent<IFFComponent>(gUid, out var iff);
            var curGridToWorld = _transform.GetWorldMatrix(gUid);
            var curGridToView = curGridToWorld * worldToShuttle * shuttleToView;
            var labelColor = _shuttles.GetIFFColor(grid, self: false, iff);

            var gridAABB = curGridToWorld.TransformBox(grid.Comp.LocalAABB);

            if (!gridAABB.Intersects(viewAABB))
                continue;

            DrawGrid(handle, curGridToView, grid, labelColor);
            DrawDocks(handle, gUid, curGridToView);
        }

        // An extra marker when the controlling console sits on a different grid to the
        // shuttle, so the player can place themselves relative to it.
        if (_consoleEntity != null && xformQuery.TryGetComponent(_consoleEntity, out var consoleXform))
        {
            if (consoleXform.ParentUid != _coordinates.Value.EntityId)
            {
                var consolePositionWorld = _transform.GetWorldPosition((EntityUid)_consoleEntity);
                var p = Vector2.Transform(consolePositionWorld, worldToShuttle * shuttleToView);
                handle.DrawCircle(p, 5, Color.ToSrgb(KsHud.OffGrid), true);
            }
        }

        // Contact layer and hover tooltip on top of everything. mapPos.Position is the
        // radar's own centre in world space, used to label each contact's range.
        KsDrawContacts(handle, worldToShuttle * shuttleToView, mapPos.Position);
        KsDrawContactTooltip(handle, mapPos.Position);
    }

    // Track the mouse for contact hover tooltips.
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);
        _ksMousePos = args.RelativePosition * UIScale;
    }

    protected override void MouseExited()
    {
        base.MouseExited();
        _ksMousePos = null;
    }

    /// <summary>
    ///     A contact's map coordinates and its range from this radar's own centre, for
    ///         the contact label and hover tooltip. For a memory ghost this reads as
    ///         where the target <em>was</em>.
    /// </summary>
    private string KsContactPosRange(KsSensorContactState contact, Vector2 ownWorldPos, TimeSpan curTime)
    {
        // Dead-reckoned, matching the drawn blip, so coords and range tick smoothly
        // instead of stepping on the sensor cadence.
        var estPos = contact.EstimatedPosition(curTime);
        var range = (estPos - ownWorldPos).Length();
        return Loc.GetString("ks-sensor-contact-pos-range",
            ("x", $"{estPos.X:0}"),
            ("y", $"{estPos.Y:0}"),
            ("range", $"{range:0}"));
    }

    /// <summary>
    ///     Draws the sensor contact layer: blips or silhouette outlines with their intel
    ///         readout, and registers hover hit points for the tooltip.
    /// </summary>
    private void KsDrawContacts(DrawingHandleScreen handle, Matrix3x2 worldToView, Vector2 ownWorldPos)
    {
        _ksContactHits.Clear();

        if (_ksContacts == null)
            return;

        var curTime = _timing.CurTime;
        var reduced = _cfg.GetCVar(KsCCVars.HudReducedMotion);

        foreach (var contact in _ksContacts)
        {
            var isAlly = KsIsAlly(contact);

            // Colour by the sensor tier that found it, an ally self-report overriding
            // to the friendly colour.
            var baseColor = isAlly ? KsHud.Ally : KsHud.GetContactColor(contact.Type);
            var color = KsContactDisplayColor(contact, baseColor, curTime, reduced);

            // A bearing-quality contact has no position at all (the state's position
            // block is zeroed server-side): it renders purely as its single wedge.
            if (contact.Quality == KsPositionQuality.Bearing)
            {
                KsDrawBearingContact(handle, contact, worldToView, color, curTime, reduced);
                continue;
            }

            // Dead-reckoned between pushes: every drawn element of this contact (blip,
            // outline, markers, anchors) uses the same estimate so nothing shears apart.
            var estPos = contact.EstimatedPosition(curTime);

            // Real hull already drawn this frame: use the live client-side centre of
            // mass (fresher than the 0.5s snapshot) for its marker, hit point and
            // edge test.
            if (_ksRealDrawn.Contains(contact.Grid))
            {
                if (!EntManager.TryGetEntity(contact.Grid, out var gridUid) ||
                    !EntManager.TryGetComponent(gridUid.Value, out PhysicsComponent? gridPhysics))
                    continue;

                var centre = Vector2.Transform(Vector2.Transform(gridPhysics.LocalCenter, _transform.GetWorldMatrix(gridUid.Value)), worldToView);

                // Off the view box: pin a compact rim marker (name + coords).
                if (KsClampToRim(centre, out var rimCentre))
                {
                    handle.DrawCircle(rimCentre, 3f, color, true);
                    if (KsReadoutDetail != KsContactDetail.None)
                        KsDrawContactEdgeLabel(handle, rimCentre, contact, ownWorldPos, color, curTime);
                    KsDrawContactPing(handle, rimCentre, contact.Grid, baseColor, curTime, reduced);
                    _ksContactHits.Add((rimCentre, contact));
                    continue;
                }

                KsDrawContactPing(handle, centre, contact.Grid, baseColor, curTime, reduced);
                _ksContactHits.Add((centre, contact));

                // Fog of war removed the stock IFF label, so the readout carries the
                // name and coordinates for live hulls too.
                if (KsReadoutDetail != KsContactDetail.None)
                    KsDrawContactReadout(handle, KsReadoutAnchor(contact, estPos, worldToView, forceRect: true), contact, ownWorldPos, color, curTime, intelOnly: false);

                continue;
            }

            var pos = Vector2.Transform(estPos, worldToView);

            // Off the view box: same compact rim marker. Nothing is culled; a contact
            // that leaves the box is pinned to the edge, not hidden.
            if (KsClampToRim(pos, out var rimPos))
            {
                handle.DrawCircle(rimPos, 3f, color, true);
                if (KsReadoutDetail != KsContactDetail.None)
                    KsDrawContactEdgeLabel(handle, rimPos, contact, ownWorldPos, color, curTime);
                KsDrawContactPing(handle, rimPos, contact.Grid, baseColor, curTime, reduced);
                _ksContactHits.Add((rimPos, contact));
                continue;
            }

            // The body. A silhouette is drawn only when the sensor is authorized to
            // reveal it (RenderMode.Outline): the real hull frozen at the last-seen
            // pose when the grid is loaded, otherwise the last-known bounding rectangle
            // from the replicated state. A withheld silhouette (RenderMode.Blip, e.g.
            // RevealSilhouette off) is only ever an anonymous dot, never the real hull,
            // even if the grid is loaded.
            if (contact.RenderMode == KsContactRenderMode.Outline)
            {
                if (KsTryGetLoadedGrid(contact.Grid, out var bodyUid, out var bodyGrid))
                {
                    DrawGrid(handle, KsFrozenGridToView(contact, estPos, worldToView), (bodyUid, bodyGrid), color);
                }
                else
                {
                    // Fallback beyond PVS. The estimate tracks the centre of mass, so
                    // corners are taken relative to LocalCenter, not the AABB centre.
                    var b = contact.LocalBounds;
                    var c = contact.LocalCenter;
                    var verts = new[]
                    {
                        Vector2.Transform(estPos + contact.Rotation.RotateVec(new Vector2(b.Left, b.Bottom) - c), worldToView),
                        Vector2.Transform(estPos + contact.Rotation.RotateVec(new Vector2(b.Right, b.Bottom) - c), worldToView),
                        Vector2.Transform(estPos + contact.Rotation.RotateVec(new Vector2(b.Right, b.Top) - c), worldToView),
                        Vector2.Transform(estPos + contact.Rotation.RotateVec(new Vector2(b.Left, b.Top) - c), worldToView),
                        Vector2.Transform(estPos + contact.Rotation.RotateVec(new Vector2(b.Left, b.Bottom) - c), worldToView),
                    };

                    handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, verts, color);
                }

                handle.DrawCircle(pos, 2f, color, true);
            }
            else
            {
                handle.DrawCircle(pos, 4f, color, true);
            }

            if (contact.Live && !contact.Static)
            {
                var headingEnd = Vector2.Transform(estPos + contact.Rotation.RotateVec(new Vector2(0f, -4f)), worldToView);
                handle.DrawLine(pos, headingEnd, color);

                if (contact.LinearVelocity.LengthSquared() > 0.01f)
                {
                    var velEnd = Vector2.Transform(estPos + contact.LinearVelocity * 3f, worldToView);
                    handle.DrawLine(pos, velEnd, color.WithAlpha(0.5f));
                }
            }

            if (KsReadoutDetail != KsContactDetail.None)
                KsDrawContactReadout(handle, KsReadoutAnchor(contact, estPos, worldToView), contact, ownWorldPos, color, curTime, intelOnly: false);

            KsDrawContactPing(handle, pos, contact.Grid, baseColor, curTime, reduced);
            _ksContactHits.Add((pos, contact));
        }
    }

    /// <summary>
    ///     The contact's colour this frame: the tier colour riding the phosphor afterglow
    ///         while live, or the memory-ghost tone, reached through a short fade when the
    ///         client saw the track go stale rather than an instant snap.
    /// </summary>
    private Color KsContactDisplayColor(KsSensorContactState contact, Color baseColor, TimeSpan curTime, bool reduced)
    {
        if (contact.Live)
        {
            var glow = KsHud.Afterglow.Eval(Math.Max(0d, (curTime - contact.LastSeen).TotalSeconds), reduced);
            return new Color(
                Math.Clamp(baseColor.R * glow, 0f, 1f),
                Math.Clamp(baseColor.G * glow, 0f, 1f),
                Math.Clamp(baseColor.B * glow, 0f, 1f),
                baseColor.A);
        }

        var dimmed = KsHud.Dim(baseColor);
        if (_ksTransitions.BecameGhost(contact.Grid) is not { } ghostAt || reduced || KsHud.GhostFadeSeconds <= 0f)
            return dimmed;

        var fade = (float) Math.Clamp((curTime - ghostAt).TotalSeconds / KsHud.GhostFadeSeconds, 0d, 1d);
        return Color.InterpolateBetween(baseColor, dimmed, fade);
    }

    /// <summary>
    ///     One frame of the expanding ring around a contact that just appeared or came
    ///         back live, timed by the client-side transition tracker.
    /// </summary>
    private void KsDrawContactPing(DrawingHandleScreen handle, Vector2 pos, NetEntity grid, Color colour, TimeSpan curTime, bool reduced)
    {
        if (reduced || KsHud.PingSeconds <= 0f || _ksTransitions.BecameLive(grid) is not { } start)
            return;

        var progress = (float) ((curTime - start).TotalSeconds / KsHud.PingSeconds);
        KsInstrumentDraw.DrawPing(handle, pos, progress, colour, UIScale, KsHud.PingAlpha);
    }

    /// <summary>Whether the contact is a datalink self-report: a source mounted on the contact's own grid.</summary>
    private static bool KsIsAlly(KsSensorContactState contact)
    {
        foreach (var source in contact.Sources)
        {
            if (source.SourceGrid == contact.Grid)
                return true;
        }

        return false;
    }

    /// <summary>
    ///     Resolves a contact's grid to a loaded client-side entity with tile data.
    ///         Beyond PVS there is no such entity, so callers fall back to the
    ///         last-known bounds.
    /// </summary>
    private bool KsTryGetLoadedGrid(NetEntity net, out EntityUid uid, out MapGridComponent grid)
    {
        uid = default;
        grid = default!;

        if (!EntManager.TryGetEntity(net, out var resolved) ||
            !EntManager.TryGetComponent(resolved.Value, out MapGridComponent? gridComp))
            return false;

        uid = resolved.Value;
        grid = gridComp;
        return true;
    }

    /// <summary>
    ///     Places a target grid's local frame at the contact's estimated pose (centre of
    ///         mass at <paramref name="estPos"/>, the dead-reckoned fix) and then into
    ///         view, so its real tiles draw where the track puts it, not where the
    ///         still-moving grid now is.
    /// </summary>
    private static Matrix3x2 KsFrozenGridToView(KsSensorContactState contact, Vector2 estPos, Matrix3x2 worldToView)
    {
        var gridToWorld = Matrix3x2.CreateTranslation(-contact.LocalCenter) * Matrix3Helpers.CreateTransform(estPos, contact.Rotation);
        return gridToWorld * worldToView;
    }

    /// <summary>
    ///     True and the rim-pinned position when <paramref name="pos"/> is outside the
    ///         view box, false and the unchanged position when inside. The square
    ///         normalize keeps the bearing to the contact so the marker sits in the
    ///         right direction.
    /// </summary>
    private bool KsClampToRim(Vector2 pos, out Vector2 clamped)
    {
        var offset = pos / PixelSize - new Vector2(0.5f, 0.5f);
        var offsetMax = MathF.Max(MathF.Abs(offset.X), MathF.Abs(offset.Y)) * 2f;
        if (offsetMax > 1f)
        {
            clamped = (offset / offsetMax + new Vector2(0.5f, 0.5f)) * PixelSize;
            return true;
        }

        clamped = pos;
        return false;
    }

    /// <summary>
    ///     The compact readout for a rim-pinned contact: name and coordinates only, kept
    ///         fully on screen. Intel, memory-age and source lines are reserved for
    ///         contacts inside the box so the edge stays uncluttered.
    /// </summary>
    private void KsDrawContactEdgeLabel(DrawingHandleScreen handle, Vector2 rimPos, KsSensorContactState contact, Vector2 ownWorldPos, Color color, TimeSpan curTime)
    {
        var showName = KsReadoutDetail >= KsHud.NameDetail;
        var showCoords = KsReadoutDetail >= KsHud.PositionDetail;

        if (!showName && !showCoords)
            return;

        var name = showName ? contact.Name ?? Loc.GetString("ks-sensor-contact-unknown") : string.Empty;
        var coords = showCoords ? KsContactPosRange(contact, ownWorldPos, curTime) : string.Empty;

        var nameDim = showName ? handle.GetDimensions(_ksFont, name, 0.7f) : Vector2.Zero;
        var coordsDim = showCoords ? handle.GetDimensions(_ksFont, coords, 0.6f) : Vector2.Zero;

        // Centre the stack on the rim point, then clamp it inside the control so the
        // text never spills off screen.
        var blockWidth = MathF.Max(nameDim.X, coordsDim.X);
        // Guard against a label wider/taller than the control: a negative max would
        // make Vector2.Clamp push the text off the top/left edge.
        var extents = Vector2.Max(Vector2.Zero, PixelSize - new Vector2(blockWidth, nameDim.Y + coordsDim.Y));
        var top = Vector2.Clamp(rimPos - new Vector2(blockWidth / 2f, 0f), Vector2.Zero, extents);

        if (showName)
            handle.DrawString(_ksFont, top, name, 0.7f, color);

        if (showCoords)
            handle.DrawString(_ksFont, top + new Vector2(0f, nameDim.Y), coords, 0.6f, color.WithAlpha(KsHud.ReadoutDetailAlpha));
    }

    /// <summary>
    ///     Draws a Bearing-quality contact: a wedge from the measuring grid along the
    ///         measured direction, its half-width the sensor's accuracy, plus a rim
    ///         marker and label where the centreline leaves the view. Range is unknown,
    ///         so nothing is drawn AT the target and the label shows a bearing instead
    ///         of coordinates. A strobe-less contact (a bearing relayed by an ally this
    ///         grid cannot place) draws nothing. Only a live track earns the wedge;
    ///         a memory strobe keeps just the rim marker and label.
    /// </summary>
    private void KsDrawBearingContact(DrawingHandleScreen handle, KsSensorContactState contact, Matrix3x2 worldToView, Color color, TimeSpan curTime, bool reduced)
    {
        if (contact.Bearing is not { } strobe)
            return;

        var apex = Vector2.Transform(strobe.Origin, worldToView);

        var bearing = (float) strobe.Bearing.Theta;

        // Far enough that every ray crosses the rim from anywhere in the view; the
        // control clips its own drawing, so overshoot costs nothing.
        var reachPx = PixelSize.X + PixelSize.Y;

        var centreEnd = apex + KsViewDirection(strobe.Origin, bearing, worldToView, apex) * reachPx;

        // The filled wedge is an emission claim, so once the track goes stale it
        // fades out with the ghost transition instead of squatting on the scope
        // forever; the rim marker and label below stay as the remembered bearing.
        var wedgeAlpha = 1f;
        if (!contact.Live)
        {
            wedgeAlpha = _ksTransitions.BecameGhost(contact.Grid) is { } ghostAt && !reduced && KsHud.GhostFadeSeconds > 0f
                ? 1f - (float) Math.Clamp((curTime - ghostAt).TotalSeconds / KsHud.GhostFadeSeconds, 0d, 1d)
                : 0f;
        }

        if (wedgeAlpha > 0f)
        {
            var half = MathHelper.DegreesToRadians(MathF.Max(0.5f, strobe.AccuracyDeg));
            var leftEnd = apex + KsViewDirection(strobe.Origin, bearing - half, worldToView, apex) * reachPx;
            var rightEnd = apex + KsViewDirection(strobe.Origin, bearing + half, worldToView, apex) * reachPx;

            // Translucent fill and dim edges echo the sensor-cone style so the wedge
            // reads as "somewhere in this direction"; the centreline is the actual track.
            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, new[] { apex, leftEnd, rightEnd }, color.WithAlpha(KsHud.ConeFillAlpha * wedgeAlpha));
            handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, new[] { leftEnd, apex, rightEnd }, color.WithAlpha(KsHud.ConeLineAlpha * wedgeAlpha));
            handle.DrawLine(apex, centreEnd, color.WithAlpha(color.A * wedgeAlpha));
        }

        // Marked where the centreline actually leaves the view box: a relayed apex can
        // sit off-screen with only part of the ray crossing, where a naive centre-clamp
        // would float the marker mid-view. Doubles as the hover spot.
        if (!KsRayViewExit(apex, centreEnd - apex, out var rimPos))
            return;

        handle.DrawCircle(rimPos, 3f, color, true);

        if (KsReadoutDetail != KsContactDetail.None)
            KsDrawBearingEdgeLabel(handle, rimPos, contact, strobe, color);

        KsDrawContactPing(handle, rimPos, contact.Grid, color, curTime, reduced);
        _ksContactHits.Add((rimPos, contact));
    }

    /// <summary>
    ///     Where the ray from <paramref name="origin"/> along <paramref name="delta"/>
    ///         LAST intersects the control rectangle (the exit point), by the standard
    ///         slab test. False when the ray misses the view box entirely.
    /// </summary>
    private bool KsRayViewExit(Vector2 origin, Vector2 delta, out Vector2 exit)
    {
        exit = default;
        var size = (Vector2) PixelSize;

        var tMin = 0f;
        var tMax = 1f;

        for (var axis = 0; axis < 2; axis++)
        {
            var o = axis == 0 ? origin.X : origin.Y;
            var d = axis == 0 ? delta.X : delta.Y;
            var s = axis == 0 ? size.X : size.Y;

            if (MathF.Abs(d) < 1e-6f)
            {
                if (o < 0f || o > s)
                    return false;

                continue;
            }

            var t1 = -o / d;
            var t2 = (s - o) / d;
            tMin = MathF.Max(tMin, MathF.Min(t1, t2));
            tMax = MathF.Min(tMax, MathF.Max(t1, t2));
        }

        if (tMax < tMin)
            return false;

        exit = origin + delta * tMax;
        return true;
    }

    /// <summary>
    ///     Unit direction, in view space, of a world-space angle taken at a world origin.
    ///         Transforming a one-unit probe through the view matrix picks up the
    ///         display's own rotation (ship-heading-up) for free.
    /// </summary>
    private static Vector2 KsViewDirection(Vector2 worldOrigin, float worldAngle, Matrix3x2 worldToView, Vector2 apexView)
    {
        var probe = Vector2.Transform(worldOrigin + new Vector2(MathF.Cos(worldAngle), MathF.Sin(worldAngle)), worldToView);
        var dir = probe - apexView;
        return dir.LengthSquared() > 0f ? Vector2.Normalize(dir) : Vector2.UnitY;
    }

    /// <summary>
    ///     The bearing contact's rim label: name, bearing line, and any resolved intel
    ///         readouts. The full label roster is reserved for positioned contacts; at
    ///         the rim only actual values earn a line.
    /// </summary>
    private void KsDrawBearingEdgeLabel(DrawingHandleScreen handle, Vector2 rimPos, KsSensorContactState contact, KsBearingLine strobe, Color color)
    {
        var lines = new List<(string Text, float Scale, float Alpha)>();

        if (KsReadoutDetail >= KsHud.NameDetail)
            lines.Add((contact.Name ?? Loc.GetString("ks-sensor-contact-unknown"), 0.7f, 1f));

        // The bearing IS this contact's position line, so it answers to the same level.
        if (KsReadoutDetail >= KsHud.PositionDetail)
            lines.Add((Loc.GetString("ks-sensor-contact-bearing", ("deg", $"{KsBearingPlot.CompassDegrees(strobe.Bearing):000}")), 0.6f, KsHud.ReadoutDetailAlpha));

        foreach (var (intelId, value) in contact.Intel)
        {
            if (_protoManager.TryIndex(intelId, out var proto) && KsReadoutDetail >= proto.Detail)
                lines.Add(($"{Loc.GetString(proto.Label)}: {value}", 0.6f, KsHud.ReadoutDetailAlpha));
        }

        if (lines.Count == 0)
            return;

        var blockWidth = 0f;
        var blockHeight = 0f;
        var dims = new List<Vector2>(lines.Count);

        foreach (var (text, scale, _) in lines)
        {
            var d = handle.GetDimensions(_ksFont, text, scale);
            dims.Add(d);
            blockWidth = MathF.Max(blockWidth, d.X);
            blockHeight += d.Y;
        }

        // Same clamping as the positional edge label: centre the stack on the rim
        // point, then keep it fully inside the control.
        var extents = Vector2.Max(Vector2.Zero, PixelSize - new Vector2(blockWidth, blockHeight));
        var linePos = Vector2.Clamp(rimPos - new Vector2(blockWidth / 2f, 0f), Vector2.Zero, extents);

        for (var i = 0; i < lines.Count; i++)
        {
            handle.DrawString(_ksFont, linePos, lines[i].Text, lines[i].Scale, color.WithAlpha(lines[i].Alpha));
            linePos += new Vector2(0f, dims[i].Y);
        }
    }

    /// <summary>
    ///     Anchors a contact's readout just outside the upper-right of its silhouette
    ///         (max screen X, min screen Y of the four projected corners), so the
    ///         left-aligned text sits beside the outline rather than over the centre of
    ///         mass at any rotation. Blip-rendered contacts have no outline, so their
    ///         anchor sits just off the marker; <paramref name="forceRect"/> uses the
    ///         silhouette anyway for a live contact drawn as a full hull.
    /// </summary>
    private Vector2 KsReadoutAnchor(KsSensorContactState contact, Vector2 estPos, Matrix3x2 worldToView, bool forceRect = false)
    {
        var useBounds = forceRect || contact.RenderMode == KsContactRenderMode.Outline;

        if (!useBounds)
            return Vector2.Transform(estPos, worldToView) + new Vector2(6f, -6f);

        var b = contact.LocalBounds;
        var c = contact.LocalCenter;

        var bl = Vector2.Transform(estPos + contact.Rotation.RotateVec(new Vector2(b.Left, b.Bottom) - c), worldToView);
        var br = Vector2.Transform(estPos + contact.Rotation.RotateVec(new Vector2(b.Right, b.Bottom) - c), worldToView);
        var tr = Vector2.Transform(estPos + contact.Rotation.RotateVec(new Vector2(b.Right, b.Top) - c), worldToView);
        var tl = Vector2.Transform(estPos + contact.Rotation.RotateVec(new Vector2(b.Left, b.Top) - c), worldToView);

        var right = MathF.Max(MathF.Max(bl.X, br.X), MathF.Max(tr.X, tl.X));
        var top = MathF.Min(MathF.Min(bl.Y, br.Y), MathF.Min(tr.Y, tl.Y));

        return new Vector2(right + 4f, top);
    }

    /// <summary>
    ///     Draws a contact's text readout as a left-aligned stack starting at
    ///         <paramref name="anchor"/> (the contact's upper-right corner): name,
    ///         coordinates + range, memory age and the readout roster (every label, its
    ///         value where a sensor resolved one, else a dimmed blank slot).
    ///         <paramref name="intelOnly"/> draws only the roster, for a live contact
    ///         whose real hull is on screen.
    /// </summary>
    private void KsDrawContactReadout(DrawingHandleScreen handle, Vector2 anchor, KsSensorContactState contact, Vector2 ownWorldPos, Color color, TimeSpan curTime, bool intelOnly)
    {
        var line = anchor;

        if (!intelOnly)
        {
            if (KsReadoutDetail >= KsHud.NameDetail)
            {
                handle.DrawString(_ksFont, line, contact.Name ?? Loc.GetString("ks-sensor-contact-unknown"), 0.7f, color);
                line += new Vector2(0f, 11f);
            }

            if (KsReadoutDetail >= KsHud.PositionDetail)
            {
                handle.DrawString(_ksFont, line, KsContactPosRange(contact, ownWorldPos, curTime), 0.6f, color.WithAlpha(KsHud.ReadoutDetailAlpha));
                line += new Vector2(0f, 10f);
            }

            if (!contact.Live && KsReadoutDetail >= KsHud.AgeDetail)
            {
                var seconds = (int)Math.Max(0, (curTime - contact.LastSeen).TotalSeconds);
                handle.DrawString(_ksFont, line, Loc.GetString("ks-sensor-contact-last-seen", ("seconds", seconds)), 0.6f, color.WithAlpha(KsHud.ReadoutDetailAlpha));
                line += new Vector2(0f, 10f);
            }
        }

        // The full roster, not only detected lines: the labels are a fixed panel, so a
        // quantity no sensor of ours resolved reads as a dimmed blank slot rather than
        // dropping its row and shifting the stack.
        foreach (var intelProto in KsIntelRoster())
        {
            // Each readout declares the lowest detail level it survives at, so cutting
            // the plot back is a YAML decision per quantity, not a hardcoded shortlist.
            if (KsReadoutDetail < intelProto.Detail)
                continue;

            string? value = null;
            foreach (var (intelId, v) in contact.Intel)
            {
                if (intelId.Id == intelProto.ID)
                {
                    value = v;
                    break;
                }
            }

            // A readout may opt out of the always-on roster; then it appears only when
            // a value is actually present.
            if (value == null && !intelProto.AlwaysShowLabel)
                continue;

            var shown = value ?? Loc.GetString("ks-sensor-intel-no-value");
            // An unresolved value is dimmer, so the panel shows what is known apart
            // from what is merely listed.
            var alpha = value != null ? KsHud.ReadoutDetailAlpha : KsHud.ReadoutUnresolvedAlpha;
            handle.DrawString(_ksFont, line, $"{Loc.GetString(intelProto.Label)}: {shown}", 0.6f, color.WithAlpha(alpha));
            line += new Vector2(0f, 10f);
        }
    }

    /// <summary>
    ///     The fixed roster of readout labels drawn on every contact panel, ordered
    ///         exactly as the server orders a contact's own readouts (by Order, then id).
    ///         Cached: the prototype set does not change mid round and rebuilding it per
    ///         contact per frame would allocate inside the draw loop.
    /// </summary>
    private List<KsSensorIntelPrototype> KsIntelRoster()
    {
        if (_ksIntelRoster != null)
            return _ksIntelRoster;

        _ksIntelRoster = new List<KsSensorIntelPrototype>();
        foreach (var proto in _protoManager.EnumeratePrototypes<KsSensorIntelPrototype>())
            _ksIntelRoster.Add(proto);

        _ksIntelRoster.Sort((a, b) =>
            a.Order != b.Order ? a.Order.CompareTo(b.Order) : string.CompareOrdinal(a.ID, b.ID));

        return _ksIntelRoster;
    }

    /// <summary>Hover tooltip attributing a contact to the sensors and ships that see it.</summary>
    private void KsDrawContactTooltip(DrawingHandleScreen handle, Vector2 ownWorldPos)
    {
        if (_ksMousePos is not { } mousePos || _ksContactHits.Count == 0)
            return;

        KsSensorContactState? best = null;
        var bestDist = 20f * UIScale;

        foreach (var (pos, contact) in _ksContactHits)
        {
            var dist = (pos - mousePos).Length();
            if (dist < bestDist)
            {
                bestDist = dist;
                best = contact;
            }
        }

        if (best == null)
            return;

        var curTime = _timing.CurTime;

        // A bearing contact's position block is zeroed, so the coordinate line would
        // print a (0, 0) lie; show the bearing instead. A hit point only ever exists
        // for a bearing contact with a strobe, so the fallthrough cannot leak.
        var whereLine = best.Quality == KsPositionQuality.Bearing && best.Bearing is { } strobe
            ? Loc.GetString("ks-sensor-contact-bearing", ("deg", $"{KsBearingPlot.CompassDegrees(strobe.Bearing):000}"))
            : KsContactPosRange(best, ownWorldPos, curTime);

        var lines = new List<(string Text, Color Color)>
        {
            (best.Name ?? Loc.GetString("ks-sensor-contact-unknown"), KsHud.TooltipText),
            best.Live
                ? (Loc.GetString("ks-sensor-contact-live"), KsHud.Live)
                : (Loc.GetString("ks-sensor-contact-last-seen", ("seconds", (int)Math.Max(0, (curTime - best.LastSeen).TotalSeconds))), KsHud.Memory),
            (whereLine, KsHud.TooltipDetail),
        };

        foreach (var source in best.Sources)
        {
            var line = Loc.GetString("ks-sensor-contact-source-line", ("sensor", source.SensorName), ("grid", source.SourceGridName));
            if (source.Hops > 0)
                line += " " + Loc.GetString("ks-sensor-contact-hops", ("hops", source.Hops));

            lines.Add((line, KsHud.TooltipDetail));
        }

        var width = 0f;
        var height = 6f;
        var dims = new List<Vector2>(lines.Count);

        foreach (var (text, _) in lines)
        {
            var d = handle.GetDimensions(_ksFont, text, 0.8f);
            dims.Add(d);
            width = Math.Max(width, d.X);
            height += d.Y + 2f;
        }

        width += 12f;

        var origin = mousePos + new Vector2(16f, 8f);
        origin = Vector2.Clamp(origin, Vector2.Zero, Vector2.Max(Vector2.Zero, (Vector2)PixelSize - new Vector2(width, height)));

        var box = new UIBox2(origin, origin + new Vector2(width, height));
        handle.DrawRect(box, KsHud.TooltipBackground);
        handle.DrawRect(box, KsHud.TooltipBorder, false);

        var linePos = origin + new Vector2(6f, 4f);
        for (var i = 0; i < lines.Count; i++)
        {
            handle.DrawString(_ksFont, linePos, lines[i].Text, 0.8f, lines[i].Color);
            linePos += new Vector2(0f, dims[i].Y + 2f);
        }
    }

    /// <summary>
    ///     Outlines the console grid's own sensor coverage fans, each cut short wherever
    ///         the hull or another grid blocks the line of sight. The apex arrives
    ///         grid-local so the fan follows the ship every frame; a fan's boundary
    ///         arrives as world-oriented offsets (see
    ///         <see cref="KsSensorRegionState.WorldOffsets"/>) so its occlusion notches
    ///         hold their world bearing while the ship spins, and a jammer wedge stays
    ///         fully grid-local because it follows its mount.
    /// </summary>
    private void KsDrawSensorRegions(DrawingHandleScreen handle, Matrix3x2 gridToView, Matrix3x2 worldToView, NetEntity ourGridNet)
    {
        if (_ksSensorRegions == null)
            return;

        var reduced = _cfg.GetCVar(KsCCVars.HudReducedMotion);

        foreach (var region in _ksSensorRegions)
        {
            // Own-grid sensors only: relayed ally cones belong to the sector map's
            // network picture, not the close-range scope. A wedge needs the apex plus
            // at least two boundary points.
            if (region.Grid != ourGridNet || region.Relayed || region.Points.Count < 3)
                continue;

            var mode = KsCoverageModes.GetValueOrDefault(region.Type, KsCoverageDisplayMode.Outline);
            if (mode == KsCoverageDisplayMode.Off)
                continue;

            // Tint to the type's contact colour so a cone reads as that sensor's reach.
            var tint = KsHud.GetContactColor(region.Type);

            // An emitting cone (radar / jammer) pulses as a reminder that running it
            // exposes you to enemy ELINT; passive fans hold steady. Reduce-motion holds
            // it at its peak instead of blinking.
            var pulse = region.Emitting
                ? reduced
                    ? KsHud.ConePulse.Base + KsHud.ConePulse.Amplitude
                    : KsHud.ConePulse.Eval(_timing.CurTime.TotalSeconds)
                : 1f;

            var verts = KsRegionDraw.BuildVerts(region, gridToView, worldToView);

            // verts[0] is the apex: the fan fills the star-shaped cone in Filled mode,
            // and the boundary stroke skips the apex.
            if (mode == KsCoverageDisplayMode.Filled)
                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, verts, tint.WithAlpha(KsHud.ConeFillAlpha * pulse));

            handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, verts.AsSpan(1), tint.WithAlpha(KsHud.ConeLineAlpha * pulse));
        }
    }

    /// <summary>
    ///     The instrument face under the whole picture: palette background, labelled
    ///         range rings at even fractions of the display range, faint radial spokes
    ///         and the ticked compass rim on the outermost ring. Replaces the vanilla
    ///         near-invisible DrawBacking/DrawCircles pair.
    /// </summary>
    private void KsDrawInstrumentFace(DrawingHandleScreen handle)
    {
        var size = (Vector2) PixelSize;
        handle.DrawRect(new UIBox2(Vector2.Zero, size), KsPalette.Background);

        if (WorldRange <= 0f)
            return;

        var centre = MidPointVector;
        var count = Math.Max(1, KsHud.RangeRingCount);
        var outerPx = WorldRange * MinimapScale;

        // Faint radial spokes every 45 degrees, under the rings.
        for (var deg = 0; deg < 360; deg += 45)
        {
            var dir = new Vector2(MathF.Sin(MathHelper.DegreesToRadians(deg)), -MathF.Cos(MathHelper.DegreesToRadians(deg)));
            handle.DrawLine(centre, centre + dir * outerPx, KsPalette.AccentDim.WithAlpha(0.2f));
        }

        for (var i = 1; i <= count; i++)
        {
            var worldR = WorldRange * i / count;
            var radiusPx = worldR * MinimapScale;

            // The outermost ring is the compass rim and gets the tick pass; the
            // inner rings stay quiet so the picture reads over them.
            if (i == count)
                KsInstrumentDraw.DrawRingTicks(handle, centre, radiusPx, UIScale, KsPalette.AccentDim.WithAlpha(0.55f), KsPalette.AccentDim, KsPalette.Accent);
            else
                handle.DrawCircle(centre, radiusPx, KsPalette.AccentDim.WithAlpha(0.3f), false);

            // Range label just inside each ring, up the bow axis.
            var label = $"{worldR:0}";
            var dim = handle.GetDimensions(_ksFont, label, 0.7f);
            var pos = new Vector2(centre.X + 3f * UIScale, centre.Y - radiusPx + 2f * UIScale);
            pos = Vector2.Clamp(pos, Vector2.Zero, Vector2.Max(Vector2.Zero, size - dim));
            handle.DrawString(_ksFont, pos, label, 0.7f, KsPalette.TextDim);
        }
    }

    /// <summary>
    ///     The "JAMMED" alarm text, top-centre, pulsing red, shown whenever any radar on
    ///         the console's grid is jammed. Reduce-motion holds it steady at full
    ///         strength: the alarm stays, only the blink goes.
    /// </summary>
    private void KsDrawJammedIndicator(DrawingHandleScreen handle)
    {
        if (!_ksJammed)
            return;

        var text = Loc.GetString("ks-sensor-jammed");
        var scale = KsHud.JammedTextScale;
        var dims = handle.GetDimensions(_ksFont, text, scale);
        var pos = new Vector2((PixelSize.X - dims.X) / 2f, 6f * UIScale);

        var pulse = _cfg.GetCVar(KsCCVars.HudReducedMotion)
            ? KsHud.JammedPulse.Base + KsHud.JammedPulse.Amplitude
            : KsHud.JammedPulse.Eval(_timing.CurTime.TotalSeconds);
        handle.DrawString(_ksFont, pos, text, scale, KsHud.JammedColor.WithAlpha(Math.Clamp(pulse, 0f, 1f)));
    }

    private void KsDrawInterests(DrawingHandleScreen handle, Matrix3x2 curGridToViewMatrix, Box2 viewAABB, Entity<MapGridComponent> gridEntity)
    {
        foreach (var (_, interest) in _radarInterestSystem.StaticInterests)
        {
            if (gridEntity.Owner != interest.Item2)
                continue;

            var interestPosition = Vector2.Transform(interest.Item3, curGridToViewMatrix);
            if (!viewAABB.Contains(interestPosition))
                continue;

            handle.DrawCircle(interestPosition, 5, Color.ToSrgb(KsHud.Interest), true);
            handle.DrawString(_ksFont, interestPosition, interest.Item1.Text, KsHud.Interest);
        }
    }

    private void DrawDocks(DrawingHandleScreen handle, EntityUid uid, Matrix3x2 gridToView)
    {
        if (!ShowDocks)
            return;

        const float DockScale = 0.6f;
        var nent = EntManager.GetNetEntity(uid);

        const float sqrt2 = 1.41421356f;
        const float dockRadius = DockScale * sqrt2;
        // Worst-case bounds used to cull a dock:
        Box2 viewBounds = new Box2(
            -dockRadius * UIScale,
            -dockRadius * UIScale,
            (Size.X + dockRadius) * UIScale,
            (Size.Y + dockRadius) * UIScale);

        if (_docks.TryGetValue(nent, out var docks))
        {
            foreach (var state in docks)
            {
                var position = state.Coordinates.Position;

                var positionInView = Vector2.Transform(position, gridToView);
                if (!viewBounds.Contains(positionInView))
                {
                    continue;
                }

                var color = Color.ToSrgb(state.HighlightedColor);

                var verts = new[]
                {
                    Vector2.Transform(position + new Vector2(-DockScale, -DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(DockScale, -DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(DockScale, DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(-DockScale, DockScale), gridToView),
                };

                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, verts, color.WithAlpha(0.8f));
                handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, verts, color);
            }
        }
    }

    private Vector2 InverseScalePosition(Vector2 value)
    {
        return (value - MidPointVector) / MinimapScale;
    }
}
