using System.Numerics;
using Content.Client.Resources;
using Content.Client.Shuttles.Systems;
using Content.Client.Shuttles.UI;
using Content.Shared._KS14.CCVar;
using Content.Shared._KS14.Sensors;
using Content.Shared._KS14.Sensors.Prototypes;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.UI.MapObjects;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Collections;
using Robust.Shared.Configuration;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._KS14.Shuttles.UI;

/// <summary>
///     The fork counterpart of the upstream <see cref="ShuttleMapControl"/>, copied
///         rather than subclassed because that control is sealed, and kept a copy so
///         the shared control stays pristine master for vanilla consoles. Identical
///         except for the instrument dressing and the KS sensor picture: with the
///         SENSORS toggle on, the chart overlays the datalink network's coverage cones
///         (own and relayed, both console-grid-local) and every live position-fixed
///         contact.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class KsShuttleMapControl : BaseShuttleControl
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IInputManager _inputs = default!;
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IPrototypeManager _protoManager = default!;
    private readonly SharedMapSystem _mapSystem;
    private readonly ShuttleSystem _shuttles;
    private readonly SharedTransformSystem _xformSystem;

    protected override bool Draggable => true;

    public bool ShowBeacons = true;
    public MapId ViewingMap = MapId.Nullspace;

    private EntityUid? _shuttleEntity;

    private readonly Font _font;

    private readonly EntityQuery<PhysicsComponent> _physicsQuery;

    /// <summary>Shows a pre-vis for FTLing a grid.</summary>
    public bool FtlMode;

    private Angle _ftlAngle;

    public bool InFtl;

    public event Action<MapCoordinates, Angle>? RequestFTL;

    public event Action<NetEntity, Angle>? RequestBeaconFTL;

    /// <summary>Set every draw to determine the beacons that are clickable for mouse events.</summary>
    private List<IMapObject> _beacons = new();

    // Per frame data to avoid re-allocating
    private readonly List<IMapObject> _mapObjects = new();
    private readonly Dictionary<Color, List<Vector2>> _verts = new();
    private readonly Dictionary<Color, List<Vector2>> _edges = new();
    private readonly Dictionary<Color, List<(Vector2, string)>> _strings = new();
    private readonly List<ShuttleExclusionObject> _viewportExclusions = new();

    /// <summary>Beacon name labels for this draw: drawn in the face font, so they skip the vanilla string batches.</summary>
    private readonly List<(Vector2 Pos, string Name)> _ksBeaconLabels = new();

    /// <summary>Whether the SENSORS overlay (network cones + live contacts) is switched on. Default off.</summary>
    public bool KsShowSensors;

    /// <summary>How far inside the chart edge an off-view ally's pin sits, leaving room for its chevron.</summary>
    private const float KsEdgePinMarginPx = 12f;

    /// <summary>The console's sensor picture, pushed with the nav state. Null = no picture.</summary>
    private KsSensorNavState? _ksSensorNav;

    private KsSensorHudPrototype? _ksHud;
    private KsSensorHudPrototype KsHud => _ksHud ??= _protoManager.Index(KsSensorHudPrototype.DefaultId);
    private KsInstrumentPalette KsPalette => KsHud.GetScreen("map");

    private readonly Font _ksFont;

    public KsShuttleMapControl() : base(256f, 512f, 512f)
    {
        RobustXamlLoader.Load(this);
        _mapSystem = EntManager.System<SharedMapSystem>();
        _shuttles = EntManager.System<ShuttleSystem>();
        _xformSystem = EntManager.System<SharedTransformSystem>();
        var cache = IoCManager.Resolve<IResourceCache>();

        _physicsQuery = EntManager.GetEntityQuery<PhysicsComponent>();

        _font = new VectorFont(cache.GetResource<FontResource>("/EngineFonts/NotoSans/NotoSans-Regular.ttf"), 10);
        _ksFont = cache.GetFont(KsInstrumentSheetlet.FontPath, KsInstrumentSheetlet.FontSizeBody);
    }

    public void SetMap(MapId mapId, Vector2 offset, bool recentering = false)
    {
        ViewingMap = mapId;
        TargetOffset = offset;
        Recentering = recentering;
    }

    public void SetShuttle(EntityUid? entity)
    {
        _shuttleEntity = entity;
    }

    public void KsSetSensorPicture(KsSensorNavState? nav)
    {
        _ksSensorNav = nav;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        if (FtlMode)
            return;

        base.MouseMove(args);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        if (FtlMode && ViewingMap != MapId.Nullspace)
        {
            if (args.Function == EngineKeyFunctions.UIClick)
            {
                var mapUid = _mapSystem.GetMapOrInvalid(ViewingMap);

                var beaconsOnly = EntManager.TryGetComponent(mapUid, out FTLDestinationComponent? destComp) &&
                                  destComp.BeaconsOnly;

                var mapTransform = Matrix3Helpers.CreateInverseTransform(Offset, Angle.Zero);

                if (beaconsOnly && TryGetBeacon(_beacons, mapTransform, args.RelativePixelPosition, PixelRect, out var foundBeacon, out _))
                {
                    RequestBeaconFTL?.Invoke(foundBeacon.Entity, _ftlAngle);
                }
                else
                {
                    // We'll send the "adjusted" position and server will adjust it back when relevant.
                    var mapCoords = new MapCoordinates(InverseMapPosition(args.RelativePixelPosition), ViewingMap);
                    RequestFTL?.Invoke(mapCoords, _ftlAngle);
                }
            }
        }

        base.KeyBindUp(args);
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        if (FtlMode)
        {
            _ftlAngle += Angle.FromDegrees(15f) * args.Delta.Y;
            _ftlAngle = _ftlAngle.Reduced();
            return;
        }

        base.MouseWheel(args);
    }

    private void DrawParallax(DrawingHandleScreen handle)
    {
        if (!EntManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform) || shuttleXform.MapUid == null)
            return;

        var tex = _shuttles.GetTexture(shuttleXform.MapUid.Value);

        // Size of the texture in world units.
        var size = tex.Size * MinimapScale * 1f;

        var position = ScalePosition(new Vector2(-Offset.X, Offset.Y));
        var slowness = 1f;

        // Parallax shifts relative to the "home" origin, away from home and towards the
        // eye centre: slowness 1 anchors the layer to the screen centre, 0 anchors it to
        // the world. Deliberately unclamped outside that range.
        var home = Vector2.Zero;
        var scrolled = Vector2.Zero;

        var originBL = (position - home) * slowness + scrolled;

        originBL += home;

        // Centre the image.
        originBL -= size / 2;

        // Remove offset so we can floor.
        var botLeft = new Vector2(0f, 0f);
        var topRight = botLeft + PixelSize;

        var flooredBL = botLeft - originBL;

        flooredBL = (flooredBL / size).Floored() * size;

        flooredBL += originBL;

        for (var x = flooredBL.X; x < topRight.X; x += size.X)
        {
            for (var y = flooredBL.Y; y < topRight.Y; y += size.Y)
            {
                // Amber-modulated so the chart grid reads as part of the instrument.
                handle.DrawTextureRect(tex, new UIBox2(x, y, x + size.X, y + size.Y), KsPalette.Text);
            }
        }
    }

    private List<IMapObject> GetViewportMapObjects(Matrix3x2 matty, List<IMapObject> mapObjects)
    {
        var results = new List<IMapObject>();
        var enlargement = new Vector2i((int)(16 * UIScale), (int)(16 * UIScale));
        var viewBox = new UIBox2i(Vector2i.Zero - enlargement, PixelSize + enlargement);

        foreach (var mapObj in mapObjects)
        {
            if (mapObj is GridMapObject gridObj && EntManager.HasComponent<MapComponent>(gridObj.Entity))
                continue;

            var mapCoords = _shuttles.GetMapCoordinates(mapObj);

            var relativePos = Vector2.Transform(mapCoords.Position, matty);
            relativePos = relativePos with { Y = -relativePos.Y };
            var uiPosition = ScalePosition(relativePos);

            if (!viewBox.Contains(uiPosition.Floored()))
                continue;

            results.Add(mapObj);
        }

        return results;
    }

    /// <summary>
    ///     Whether a sensor picture exists to draw at all, before the operator's
    ///         SENSORS toggle gets a say. Split out because the allied layer ignores
    ///         that toggle.
    /// </summary>
    private bool KsSensorPictureAvailable()
    {
        return _ksSensorNav != null
               && !InFtl
               && EntManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform)
               && shuttleXform.MapID == ViewingMap;
    }

    /// <summary>Whether the network holds a self-reporting member other than this ship.</summary>
    private bool KsHasAllyContact()
    {
        if (_ksSensorNav?.Contacts is not { } contacts)
            return false;

        foreach (var contact in contacts)
        {
            if (KsIsAlly(contact))
                return true;
        }

        return false;
    }

    /// <summary>
    ///     World space to chart pixels: the same -Offset -> scale(MinimapScale,
    ///         -MinimapScale) -> mid-point chain the stock draw applies step by step.
    /// </summary>
    private Matrix3x2 KsWorldToView()
    {
        return Matrix3Helpers.CreateInverseTransform(Offset, Angle.Zero)
               * Matrix3x2.CreateScale(new Vector2(MinimapScale, -MinimapScale))
               * Matrix3x2.CreateTranslation(MidPointVector);
    }

    /// <summary>
    ///     Range rings around the own ship, labelled in metres. Pure chrome: always
    ///         drawn, no sensor data involved.
    /// </summary>
    private void KsDrawRangeRings(DrawingHandleScreen handle, Matrix3x2 worldToView)
    {
        if (_shuttleEntity is not { } shuttle
            || !EntManager.TryGetComponent(shuttle, out TransformComponent? shuttleXform)
            || shuttleXform.MapID != ViewingMap)
        {
            return;
        }

        // CoM-adjusted like every other own-ship anchor here: the grid origin can sit
        // tens of metres from the hull on asymmetric grids.
        var (shipPos, shipRot) = _xformSystem.GetWorldPositionRotation(shuttleXform);
        shipPos = Maps.GetGridPosition((shuttle, _physicsQuery.CompOrNull(shuttle)), shipPos, shipRot);
        var centre = Vector2.Transform(shipPos, worldToView);
        var count = Math.Max(1, KsHud.RangeRingCount);

        for (var i = 1; i <= count; i++)
        {
            var worldR = WorldRange * i / count;
            var radiusPx = worldR * MinimapScale;
            handle.DrawCircle(centre, radiusPx, KsPalette.AccentDim.WithAlpha(0.25f), false);

            var label = $"{worldR:0}";
            var dim = handle.GetDimensions(_ksFont, label, 0.7f);
            var pos = new Vector2(centre.X + 3f * UIScale, centre.Y - radiusPx + 2f * UIScale);
            pos = Vector2.Clamp(pos, Vector2.Zero, Vector2.Max(Vector2.Zero, (Vector2) PixelSize - dim));
            handle.DrawString(_ksFont, pos, label, 0.7f, KsPalette.AccentDim);
        }
    }

    /// <summary>Per-frame scratch for the cone vertices, sliced by BuildVerts' returned count.</summary>
    private Vector2[] _ksConeVerts = Array.Empty<Vector2>();

    /// <summary>
    ///     The network's coverage cones, own and datalink-relayed alike: every apex
    ///         arrives framed against the console's grid, so one matrix chain places
    ///         them all (fan boundaries ride their apex as world-oriented offsets, see
    ///         <see cref="KsSensorRegionState.WorldOffsets"/>). The radar tab
    ///         deliberately does not draw the relayed ones.
    /// </summary>
    private void KsDrawSensorCones(DrawingHandleScreen handle, Matrix3x2 worldToView)
    {
        if (_ksSensorNav?.Regions is not { } regions || _shuttleEntity is not { } shuttle)
            return;

        var gridToView = _xformSystem.GetWorldMatrix(shuttle) * worldToView;
        var reduced = _cfg.GetCVar(KsCCVars.HudReducedMotion);

        foreach (var region in regions)
        {
            if (region.Points.Count < 3)
                continue;

            var tint = KsHud.GetContactColor(region.Type);

            var pulse = region.Emitting
                ? reduced
                    ? KsHud.ConePulse.Base + KsHud.ConePulse.Amplitude
                    : KsHud.ConePulse.Eval(_timing.CurTime.TotalSeconds)
                : 1f;

            var count = KsRegionDraw.BuildVerts(region, gridToView, worldToView, ref _ksConeVerts);

            // verts[0] is the apex: the fan fills the cone, the stroked boundary skips it.
            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, _ksConeVerts.AsSpan(0, count), tint.WithAlpha(KsHud.ConeFillAlpha * pulse));
            handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, _ksConeVerts.AsSpan(1, count - 1), tint.WithAlpha(KsHud.ConeLineAlpha * pulse));
        }
    }

    /// <summary>Whether the contact is a datalink self-report: a source mounted on the contact's own grid.</summary>
    private static bool KsIsAlly(KsSensorContactState contact)
    {
        foreach (var source in contact.Sources)
        {
            if (source.SourceGrid == contact.Grid)
                return true;
        }

        return false;
    }

    /// <summary>
    ///     Live position-fixed contacts as tier-coloured markers. Live fixes only: a
    ///         bearing-only track has no charted position, and memory ghosts belong to
    ///         the RADAR/ESM instruments. An off-view datalinked ally pins to the chart
    ///         edge with an outward chevron so the operator always knows where the
    ///         network is; every other off-view contact simply drops.
    /// </summary>
    private void KsDrawSensorContacts(DrawingHandleScreen handle, Matrix3x2 worldToView, bool alliesOnly)
    {
        if (_ksSensorNav?.Contacts is not { } contacts)
            return;

        var viewBounds = PixelRect;
        var curTime = _timing.CurTime;

        foreach (var contact in contacts)
        {
            if (!contact.Live || contact.Quality != KsPositionQuality.Exact)
                continue;

            var ally = KsIsAlly(contact);
            if (alliesOnly && !ally)
                continue;

            var color = ally ? KsHud.Ally : KsHud.GetContactColor(contact.Type);
            // Dead-reckoned like the radar scope, so a moving marker glides between
            // sensor pushes instead of stepping.
            var pos = Vector2.Transform(contact.EstimatedPosition(curTime), worldToView);

            var onScreen = viewBounds.Contains(pos.Floored());
            if (!onScreen && !ally)
                continue;

            if (!onScreen)
            {
                // The pin rides the ray from the view centre, so it sits on the true
                // direction from wherever the operator has dragged the chart to.
                var away = pos - MidPointVector;
                if (away.LengthSquared() < 1e-6f)
                    continue;

                pos = KsClampToChartEdge(pos, KsEdgePinMarginPx * UIScale);
                KsDrawEdgeChevron(handle, pos, Vector2.Normalize(away), color);
            }

            handle.DrawCircle(pos, 4f, color.WithAlpha(0.25f));
            handle.DrawCircle(pos, 4f, color, false);

            var label = contact.Designation ?? contact.Name;
            if (label == null)
                continue;

            var labelPos = pos + new Vector2(6f, -6f);
            if (!onScreen)
            {
                // A pinned label would run off the very edge its marker hugs, so it
                // clamps back inside the chart like the range-ring labels do.
                var dim = handle.GetDimensions(_ksFont, label, 0.8f);
                labelPos = Vector2.Clamp(labelPos, Vector2.Zero, Vector2.Max(Vector2.Zero, (Vector2) PixelSize - dim));
            }

            handle.DrawString(_ksFont, labelPos, label, 0.8f, color);
        }
    }

    /// <summary>
    ///     Where the segment from the view centre toward <paramref name="pos"/> crosses
    ///         the chart rect inset by <paramref name="margin"/>: the standard slab
    ///         test, anchored at the centre so the pin holds its true bearing through
    ///         chart drags and zooms.
    /// </summary>
    private Vector2 KsClampToChartEdge(Vector2 pos, float margin)
    {
        var origin = MidPointVector;
        var d = pos - origin;
        var t = 1f;

        for (var axis = 0; axis < 2; axis++)
        {
            var o = axis == 0 ? origin.X : origin.Y;
            var dv = axis == 0 ? d.X : d.Y;
            var max = (axis == 0 ? PixelSize.X : PixelSize.Y) - margin;

            if (MathF.Abs(dv) < 1e-6f)
                continue;

            var bound = dv > 0f ? max : margin;
            t = MathF.Min(t, (bound - o) / dv);
        }

        return origin + d * MathF.Max(0f, t);
    }

    /// <summary>Two short strokes at a pinned marker, pointing off-chart along the contact's true direction.</summary>
    private void KsDrawEdgeChevron(DrawingHandleScreen handle, Vector2 pos, Vector2 outward, Color color)
    {
        var perp = new Vector2(-outward.Y, outward.X);
        var tip = pos + outward * 9f * UIScale;
        var arm = 5f * UIScale;

        handle.DrawLine(tip, tip - outward * arm + perp * arm, color);
        handle.DrawLine(tip, tip - outward * arm - perp * arm, color);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (ViewingMap == MapId.Nullspace)
            return;

        var mapObjects = _mapObjects;
        DrawRecenter();

        var ksAvailable = KsSensorPictureAvailable();
        var ksSensors = KsShowSensors && ksAvailable;

        // Allies survive the SENSORS toggle: a datalinked ship is telling you where it
        // is, not showing up as a sensor return, so the fleet stays plotted while the
        // operator declutters everything the sensors found.
        var ksAllies = ksAvailable && !ksSensors && KsHasAllyContact();

        // Fork change: an un-pinged chart with the sensor overlay on still shows the
        // live picture instead of NO SIGNAL; the ping objects and the sensor layer are
        // independent. In FTL (or with neither layer) the stock dead screen stays.
        if (InFtl || mapObjects.Count == 0 && !ksSensors && !ksAllies)
        {
            // Fork change: the dead screen wears the instrument palette and face font.
            KsInstrumentDraw.DrawDeadScreen(handle, PixelSizeBox, MidPointVector, Width,
                Loc.GetString("shuttle-console-no-signal"), _ksFont, KsPalette);
            return;
        }

        DrawParallax(handle);

        var viewedMapUid = _mapSystem.GetMapOrInvalid(ViewingMap);
        var matty = Matrix3Helpers.CreateInverseTransform(Offset, Angle.Zero);
        var realTime = _timing.RealTime;
        var viewBox = new Box2(Offset - WorldRangeVector, Offset + WorldRangeVector);
        var viewportObjects = GetViewportMapObjects(matty, mapObjects);
        _viewportExclusions.Clear();

        var ksWorldToView = KsWorldToView();
        KsDrawRangeRings(handle, ksWorldToView);

        // Coverage under everything else: the picture reads through it.
        if (ksSensors)
            KsDrawSensorCones(handle, ksWorldToView);

        // Up here because the FTL range wants to layer below most things.
        if (FtlMode)
        {
            if (EntManager.TryGetComponent<TransformComponent>(_shuttleEntity, out var shuttleXform))
            {
                var gridUid = _shuttleEntity.Value;
                var gridPhysics = _physicsQuery.GetComponent(gridUid);
                var (gridPos, gridRot) = _xformSystem.GetWorldPositionRotation(shuttleXform);
                gridPos = Maps.GetGridPosition((gridUid, gridPhysics), gridPos, gridRot);

                var gridRelativePos = Vector2.Transform(gridPos, matty);
                gridRelativePos = gridRelativePos with { Y = -gridRelativePos.Y };
                var gridUiPos = ScalePosition(gridRelativePos);

                var range = _shuttles.GetFTLRange(gridUid);
                range *= MinimapScale;
                // Fork change: stock gold traded for the instrument's own chrome.
                handle.DrawCircle(gridUiPos, range, KsPalette.Accent, filled: false);
            }
        }

        // Fork change: exclusions speak the palette's alert colour.
        var exclusionColor = KsPalette.Warning;

        // Exclusions need a bumped range so we check all the ones on the map.
        foreach (var mapObj in mapObjects)
        {
            if (mapObj is not ShuttleExclusionObject exclusion)
                continue;

            var coords = EntManager.GetCoordinates(exclusion.Coordinates);
            var mapCoords = _xformSystem.ToMapCoordinates(coords);
            var enlargedBounds = viewBox.Enlarged(exclusion.Range);

            if (mapCoords.MapId != ViewingMap ||
                !enlargedBounds.Contains(mapCoords.Position))
            {
                continue;
            }

            var adjustedPos = Vector2.Transform(mapCoords.Position, matty);
            var localPos = ScalePosition(adjustedPos with { Y = -adjustedPos.Y });
            handle.DrawCircle(localPos, exclusion.Range * MinimapScale, exclusionColor.WithAlpha(0.05f));
            handle.DrawCircle(localPos, exclusion.Range * MinimapScale, exclusionColor, filled: false);

            _viewportExclusions.Add(exclusion);
        }

        _verts.Clear();
        _edges.Clear();
        _strings.Clear();

        var beaconsOnly = _shuttles.IsBeaconMap(viewedMapUid);
        var controlLocalBounds = PixelRect;
        _beacons.Clear();
        _ksBeaconLabels.Clear();

        if (ShowBeacons)
        {
            // Fork change: chart furniture wears the chrome accent, keeping it
            // apart from the tier-coloured returns, and the glyph is the classic
            // nav-mark triangle instead of the stock diamond. The name label moves
            // to the face font, skipping the vanilla string batch below.
            var beaconColor = KsPalette.Accent;

            foreach (var (beaconName, coords, mapO) in GetBeacons(viewportObjects, matty, controlLocalBounds))
            {
                var localPos = Vector2.Transform(coords.Position, matty);
                localPos = localPos with { Y = -localPos.Y };
                var beaconUiPos = ScalePosition(localPos);

                var existingVerts = _verts.GetOrNew(beaconColor);
                var existingEdges = _edges.GetOrNew(beaconColor);

                AddKsBeaconGlyph(existingEdges, existingVerts, beaconUiPos, GetMapObjectRadius() * MinimapScale);
                _beacons.Add(mapO);

                _ksBeaconLabels.Add((beaconUiPos, beaconName));
            }
        }

        foreach (var mapObj in viewportObjects)
        {
            if (mapObj is not GridMapObject gridObj || !EntManager.TryGetComponent(gridObj.Entity, out MapGridComponent? mapGrid))
                continue;

            Entity<MapGridComponent> grid = (gridObj.Entity, mapGrid);
            IFFComponent? iffComp = null;

            // Rudimentary IFF for now, if IFF hiding on then we don't show on the map at all
            if (grid.Owner != _shuttleEntity &&
                EntManager.TryGetComponent(grid, out iffComp) &&
                (iffComp.Flags & IFFFlags.Hide) != 0x0)
            {
                continue;
            }

            var gridColor = _shuttles.GetIFFColor(grid, self: _shuttleEntity == grid.Owner, component: iffComp);

            var existingVerts = _verts.GetOrNew(gridColor);
            var existingEdges = _edges.GetOrNew(gridColor);

            var gridPhysics = _physicsQuery.GetComponent(grid.Owner);
            var (gridPos, gridRot) = _xformSystem.GetWorldPositionRotation(grid.Owner);
            gridPos = Maps.GetGridPosition((grid, gridPhysics), gridPos, gridRot);

            var gridRelativePos = Vector2.Transform(gridPos, matty);
            gridRelativePos = gridRelativePos with { Y = -gridRelativePos.Y };
            var gridUiPos = ScalePosition(gridRelativePos);

            // KS survey glyph instead of the stock wizden diamond: corner brackets
            // around a small lozenge read as "charted return" on the instrument face.
            AddKsScannedGridGlyph(existingEdges, existingVerts, gridUiPos, GetMapObjectRadius() * MinimapScale);

            if (iffComp != null && (iffComp.Flags & IFFFlags.HideLabel) != 0x0)
                continue;

            // Force drawing it at this point.
            var iffText = _shuttles.GetIFFLabel(grid, self: true, component: iffComp);

            if (string.IsNullOrEmpty(iffText))
                continue;

            var existingStrings = _strings.GetOrNew(gridColor);
            existingStrings.Add((gridUiPos, iffText));
        }

        // Batch by colour; really only affects forks with lots of grids.
        foreach (var (color, sendVerts) in _verts)
        {
            handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList, sendVerts, color.WithAlpha(0.05f));
        }

        foreach (var (color, sendEdges) in _edges)
        {
            handle.DrawPrimitives(DrawPrimitiveTopology.LineList, sendEdges, color);
        }

        foreach (var (color, sendStrings) in _strings)
        {
            var adjustedColor = Color.FromSrgb(color);

            foreach (var (gridUiPos, iffText) in sendStrings)
            {
                var textWidth = handle.GetDimensions(_font, iffText, 1f);
                handle.DrawString(_font, gridUiPos + textWidth with { X = -textWidth.X / 2f, Y = textWidth.Y * UIScale }, iffText, adjustedColor);
            }
        }

        // Fork change: beacon names ride the face font in the chrome accent
        // rather than the vanilla batch above.
        foreach (var (beaconUiPos, beaconName) in _ksBeaconLabels)
        {
            var dim = handle.GetDimensions(_ksFont, beaconName, 0.7f);
            handle.DrawString(_ksFont, beaconUiPos + new Vector2(-dim.X / 2f, dim.Y), beaconName, 0.7f, KsPalette.Accent);
        }

        // Live contacts sit over the pinged diamonds: fresher data wins the eye, and a
        // dot on a diamond reads as "pinged AND currently tracked".
        if (ksSensors || ksAllies)
            KsDrawSensorContacts(handle, ksWorldToView, alliesOnly: !ksSensors);

        var mousePos = _inputs.MouseScreenPosition;
        var mouseLocalPos = GetLocalPosition(mousePos);

        if (FtlMode)
        {
            if (mousePos.Window != WindowId.Invalid)
            {
                if (_shuttleEntity != null && controlLocalBounds.Contains(mouseLocalPos.Floored()) &&
                    EntManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform) &&
                    shuttleXform.MapID != MapId.Nullspace)
                {
                    // If it's a beacon only map then snap the mouse to a nearby spot.
                    ShuttleBeaconObject foundBeacon = default;

                    if (beaconsOnly && TryGetBeacon(viewportObjects, matty, mouseLocalPos, controlLocalBounds, out foundBeacon, out var foundLocalPos))
                    {
                        mouseLocalPos = foundLocalPos;
                    }

                    var grid = EntManager.GetComponent<MapGridComponent>(_shuttleEntity.Value);

                    var (gridPos, gridRot) = _xformSystem.GetWorldPositionRotation(shuttleXform);
                    gridPos = Maps.GetGridPosition(_shuttleEntity.Value, gridPos, gridRot);

                    // do NOT apply LocalCenter operation here because it will be adjusted in FTLFree.
                    var mouseMapPos = InverseMapPosition(mouseLocalPos);

                    var ftlFree = (!beaconsOnly || foundBeacon != default) &&
                                  _shuttles.FTLFree(_shuttleEntity.Value, new EntityCoordinates(viewedMapUid, mouseMapPos), _ftlAngle, _viewportExclusions);

                    // Fork change: the designator speaks the palette's verdict
                    // colours, and the buffer ring below joins it instead of the
                    // stock always-magenta.
                    var color = ftlFree ? KsPalette.Good : KsPalette.Warning;

                    var gridRelativePos = Vector2.Transform(gridPos, matty);
                    gridRelativePos = gridRelativePos with { Y = -gridRelativePos.Y };
                    var gridUiPos = ScalePosition(gridRelativePos);

                    var ourFTLBuffer = _shuttles.GetFTLBufferRange(_shuttleEntity.Value, grid);
                    ourFTLBuffer *= MinimapScale;
                    handle.DrawCircle(mouseLocalPos, ourFTLBuffer, color.WithAlpha(0.01f));
                    handle.DrawCircle(mouseLocalPos, ourFTLBuffer, color, filled: false);

                    // Might need to clip the line if it's too far.
                    handle.DrawDottedLine(gridUiPos, mouseLocalPos, color, (float)realTime.TotalSeconds * 30f);

                    DrawKsFtlDesignator(handle, mouseLocalPos, _ftlAngle, GetMapObjectRadius() * MinimapScale, color);
                }
            }
        }

        var mapOffset = MidPointVector;

        if (mousePos.Window != WindowId.Invalid &&
            controlLocalBounds.Contains(mouseLocalPos.Floored()))
        {
            mapOffset = mouseLocalPos;
        }

        mapOffset = InverseMapPosition(mapOffset);
        var coordsText = $"{mapOffset.X:0.0}, {mapOffset.Y:0.0}";
        DrawData(handle, coordsText);
    }

    /// <summary>
    ///     The scanned-grid marker: four corner brackets around a small centre lozenge,
    ///         appended to the same per-colour batches the stock diamonds ride so the
    ///         IFF tint and the faint fill keep working unchanged. Sized in screen
    ///         pixels off the stock diamond radius, so it keeps the constant on-chart
    ///         footprint across zoom.
    /// </summary>
    private static void AddKsScannedGridGlyph(List<Vector2> edges, List<Vector2> verts, Vector2 centre, float radiusPx)
    {
        var half = radiusPx * 1.4f;
        var arm = half * 0.5f;
        var lozenge = radiusPx * 0.45f;

        for (var sx = -1; sx <= 1; sx += 2)
        {
            for (var sy = -1; sy <= 1; sy += 2)
            {
                var corner = centre + new Vector2(sx * half, sy * half);

                edges.Add(corner);
                edges.Add(corner - new Vector2(sx * arm, 0f));
                edges.Add(corner);
                edges.Add(corner - new Vector2(0f, sy * arm));
            }
        }

        var top = centre + new Vector2(0f, -lozenge);
        var right = centre + new Vector2(lozenge, 0f);
        var bottom = centre + new Vector2(0f, lozenge);
        var left = centre + new Vector2(-lozenge, 0f);

        edges.Add(top);
        edges.Add(right);
        edges.Add(right);
        edges.Add(bottom);
        edges.Add(bottom);
        edges.Add(left);
        edges.Add(left);
        edges.Add(top);

        // The faint interior fill the stock diamonds had, kept on the lozenge only.
        verts.Add(top);
        verts.Add(right);
        verts.Add(bottom);
        verts.Add(top);
        verts.Add(bottom);
        verts.Add(left);
    }

    /// <summary>
    ///     The beacon glyph: a small open triangle, the classic chart symbol for a
    ///         fixed nav mark, batched like the grid glyphs so the faint interior
    ///         fill keeps working unchanged.
    /// </summary>
    private static void AddKsBeaconGlyph(List<Vector2> edges, List<Vector2> verts, Vector2 centre, float radiusPx)
    {
        var top = centre + new Vector2(0f, -radiusPx);
        var right = centre + new Vector2(radiusPx * 0.866f, radiusPx * 0.5f);
        var left = centre + new Vector2(-radiusPx * 0.866f, radiusPx * 0.5f);

        edges.Add(top);
        edges.Add(right);
        edges.Add(right);
        edges.Add(left);
        edges.Add(left);
        edges.Add(top);

        verts.Add(top);
        verts.Add(right);
        verts.Add(left);
    }

    /// <summary>
    ///     The FTL landing designator: an open footprint box turned to the dialled
    ///         facing with a heading spike off its leading edge, replacing the stock
    ///         diamond so the cursor speaks the instrument's glyph language. The
    ///         colour carries the verdict, Good for clear and Warning for blocked.
    /// </summary>
    private static void DrawKsFtlDesignator(DrawingHandleScreen handle, Vector2 centre, Angle facing, float radiusPx, Color color)
    {
        var half = radiusPx * 1.2f;

        var box = new ValueList<Vector2>(4)
        {
            centre + facing.RotateVec(new Vector2(-half, -half)),
            centre + facing.RotateVec(new Vector2(half, -half)),
            centre + facing.RotateVec(new Vector2(half, half)),
            centre + facing.RotateVec(new Vector2(-half, half)),
        };

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, box.Span, color.WithAlpha(0.05f));
        handle.DrawPrimitives(DrawPrimitiveTopology.LineLoop, box.Span, color);

        var spikeStart = centre + facing.RotateVec(new Vector2(0f, -half));
        var spikeEnd = centre + facing.RotateVec(new Vector2(0f, -half - radiusPx * 1.6f));
        handle.DrawLine(spikeStart, spikeEnd, color);
    }

    /// <summary>Returns the beacons that intersect the viewport.</summary>
    private IEnumerable<(string Beacon, MapCoordinates Coordinates, IMapObject MapObject)> GetBeacons(List<IMapObject> mapObjs, Matrix3x2 mapTransform, UIBox2i area)
    {
        foreach (var mapO in mapObjs)
        {
            if (mapO is not ShuttleBeaconObject beacon)
                continue;

            var beaconCoords = _xformSystem.ToMapCoordinates(EntManager.GetCoordinates(beacon.Coordinates));
            var position = Vector2.Transform(beaconCoords.Position, mapTransform);
            var localPos = ScalePosition(position with { Y = -position.Y });

            if (!area.Contains(localPos.Floored()))
                continue;

            yield return (beacon.Name, beaconCoords, mapO);
        }
    }

    private float GetMapObjectRadius(float scale = 1f) => WorldRange / 40f * scale;

    private bool TryGetBeacon(IEnumerable<IMapObject> mapObjects, Matrix3x2 mapTransform, Vector2 mousePos, UIBox2i area, out ShuttleBeaconObject foundBeacon, out Vector2 foundLocalPos)
    {
        // In pixels
        const float BeaconSnapRange = 32f;
        float nearestValue = float.MaxValue;
        foundLocalPos = Vector2.Zero;
        foundBeacon = default;

        foreach (var mapObj in mapObjects)
        {
            if (mapObj is not ShuttleBeaconObject beaconObj)
                continue;

            var beaconCoords = _xformSystem.ToMapCoordinates(EntManager.GetCoordinates(beaconObj.Coordinates));

            if (beaconCoords.MapId != ViewingMap)
                continue;

            if (!_shuttles.CanFTLBeacon(beaconObj.Coordinates))
                continue;

            var position = Vector2.Transform(beaconCoords.Position, mapTransform);
            var localPos = ScalePosition(position with { Y = -position.Y });

            if (!area.Contains(localPos.Floored()))
                continue;

            var distance = (localPos - mousePos).Length();

            if (distance > BeaconSnapRange * UIScale ||
                distance > nearestValue)
            {
                continue;
            }

            foundLocalPos = localPos;
            nearestValue = distance;
            foundBeacon = beaconObj;
        }

        return foundBeacon != default;
    }

    /// <summary>Sets the map objects for the next draw.</summary>
    public void SetMapObjects(Dictionary<MapId, List<IMapObject>> mapObjects)
    {
        _mapObjects.Clear();

        if (mapObjects.TryGetValue(ViewingMap, out var obbies))
        {
            _mapObjects.AddRange(obbies);
        }
    }
}
