using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._KS14.McqDialogue.UI;

[GenerateTypedNameReferences]
public sealed partial class McqDialogueWindow() : FancyWindow()
{
    // Method to add a new option at runtime
    public void AddOption(string text, Action handler)
    {
        var button = new Button
        {
            Text = text,
            //StyleClasses = { "OpenBoth" }
        };

        OptionsContainer.AddChild(button);
        button.OnPressed += (args) => { handler(); };
    }
}
