using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client._KS14.McqDialogue.UI;

/// <summary>
/// Client-side UI used to control a molar mixer.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class McqDialogueWindow() : DefaultWindow()
{
    // Method to add a new option at runtime
    public void AddOption(string text, Action handler)
    {
        var button = new Button
        {
            Text = text,
            StyleClasses = { "OpenBoth" }
        };

        OptionsContainer.AddChild(button);
        button.OnPressed += (args) => { handler(); };
    }
}
