- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Box
  - Marathon
  - Packed
  # KS14 start: restored maps
  - Saltern
  - Meta
  # KS14 end
  # KS14 start: removed maps
  # - Bagel
  # - Fland
  # - Snowball
  # - Oasis
  # - Plasma
  # - Exo
  # - Reach
  #- Serpentcrest # FUCK NO
  # KS14 end
