- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Box
  - Marathon
  - Packed
  # KS14 start: ported maps
  - Mira
  - Omega
  # KS14 end
  # KS14 start: restored maps
  - Saltern
  # KS14 end
  # KS14 start: removed maps
  # - Meta #RIP
  # - Bagel
  # - Fland
  # - Snowball
  # - Oasis
  # - Plasma
  # - Exo
  # - Reach
  #- Serpentcrest # FUCK NO
  # KS14 end
