using Content.Shared._KS14.Sensors;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._KS14.Sensors.UI;

[GenerateTypedNameReferences]
public sealed partial class KsDatalinkReceiverWindow : FancyWindow
{
    public event Action? OnTogglePressed;
    public event Action<int>? OnFrequencyChanged;

    private readonly FloatSpinBox _frequencySpinBox;

    public KsDatalinkReceiverWindow()
    {
        RobustXamlLoader.Load(this);

        // Integer-flavored tuning across the 1000-3000 band.
        _frequencySpinBox = new FloatSpinBox(10f, 0) { MinWidth = 100, HorizontalExpand = true };
        FrequencyBox.AddChild(_frequencySpinBox);

        ToggleButton.OnPressed += _ => OnTogglePressed?.Invoke();

        // FloatSpinBox only fires on button press / focus-exit / enter, never mid-keystroke,
        //     so this only sends on commit.
        _frequencySpinBox.OnValueChanged += args =>
        {
            var clamped = Math.Clamp((int) MathF.Round(args.Value), KsDatalink.MinFrequency, KsDatalink.MaxFrequency);
            // Echo the clamp locally so the box never shows an out-of-band value while
            // waiting for the server state.
            _frequencySpinBox.Value = clamped;
            OnFrequencyChanged?.Invoke(clamped);
        };
    }

    public void UpdateState(KsDatalinkReceiverBuiState state)
    {
        StatusLabel.Text = GetStatusText(state.Enabled, state.Powered);

        // Don't fight in-progress edits.
        if (!_frequencySpinBox.HasKeyboardFocus())
            _frequencySpinBox.Value = state.Frequency;

        HeardValueLabel.Text = state.HeardTransmitters.ToString();
    }

    private static string GetStatusText(bool enabled, bool powered)
    {
        if (!enabled)
            return Loc.GetString("ks-datalink-ui-status-off");

        if (!powered)
            return Loc.GetString("ks-datalink-ui-status-unpowered");

        return Loc.GetString("ks-datalink-ui-status-listening");
    }
}
