using Content.Shared._KS14.Sensors;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._KS14.Sensors.UI;

[GenerateTypedNameReferences]
public sealed partial class KsDatalinkTransmitterWindow : FancyWindow
{
    public event Action? OnTogglePressed;
    public event Action<int>? OnFrequencyChanged;
    public event Action<float>? OnPowerChanged;

    private readonly FloatSpinBox _frequencySpinBox;

    public KsDatalinkTransmitterWindow()
    {
        RobustXamlLoader.Load(this);

        // Integer-flavored tuning across the 1000-3000 band. Built in code, not XAML, so we
        //     control step/precision (same pattern as GasThermomachineWindow).
        _frequencySpinBox = new FloatSpinBox(10f, 0) { MinWidth = 100, HorizontalExpand = true };
        FrequencyBox.AddChild(_frequencySpinBox);

        ToggleButton.OnPressed += _ => OnTogglePressed?.Invoke();

        // FloatSpinBox only fires on button press / focus-exit / enter, never mid-keystroke,
        //     so this only sends on commit.
        _frequencySpinBox.OnValueChanged += args =>
        {
            var clamped = Math.Clamp((int) MathF.Round(args.Value), KsDatalink.MinFrequency, KsDatalink.MaxFrequency);
            // Echo the clamp locally so the box never shows an out-of-band value while
            // waiting for the server state.
            _frequencySpinBox.Value = clamped;
            OnFrequencyChanged?.Invoke(clamped);
        };

        PowerSlider.OnReleased += _ =>
        {
            OnPowerChanged?.Invoke(PowerSlider.Value / 100f);
        };

        PowerSlider.OnValueChanged += _ =>
        {
            PowerValueLabel.Text = Loc.GetString("ks-datalink-ui-power-value", ("percent", (int) PowerSlider.Value));
        };
    }

    public void UpdateState(KsDatalinkTransmitterBuiState state)
    {
        StatusLabel.Text = GetStatusText(state.Enabled, state.Powered, state.PowerFraction);

        // A mapping-set public beacon is heard on every channel, so its tuner is meaningless.
        _frequencySpinBox.Visible = !state.AllFrequencies;
        FrequencyAllLabel.Visible = state.AllFrequencies;

        // Don't fight in-progress edits.
        if (!state.AllFrequencies && !_frequencySpinBox.HasKeyboardFocus())
            _frequencySpinBox.Value = state.Frequency;

        if (!PowerSlider.Grabbed)
        {
            PowerSlider.SetValueWithoutEvent(state.PowerFraction * 100f);
            PowerValueLabel.Text = Loc.GetString("ks-datalink-ui-power-value", ("percent", (int) MathF.Round(state.PowerFraction * 100f)));
        }

        // Sector-wide beacon: no falloff, so a numeric range would be a lie.
        RangeValueLabel.Text = state.UnlimitedRange
            ? Loc.GetString("ks-datalink-ui-range-unlimited")
            : Loc.GetString("ks-datalink-ui-range-value", ("range", (int) MathF.Round(state.EffectiveRange)));
    }

    private static string GetStatusText(bool enabled, bool powered, float powerFraction)
    {
        if (!enabled)
            return Loc.GetString("ks-datalink-ui-status-off");

        if (!powered)
            return Loc.GetString("ks-datalink-ui-status-unpowered");

        // The datalink resolve treats 0% power as not broadcasting at all.
        if (powerFraction <= 0f)
            return Loc.GetString("ks-datalink-ui-status-silent");

        return Loc.GetString("ks-datalink-ui-status-transmitting");
    }
}
