using System.Linq; // _sin
using Content.Shared._sin.Audio.Jukebox; // _sin
using Content.Shared.Audio.Jukebox;
using Content.Shared.CCVar; // _sin
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Configuration; // _sin
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Audio.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class JukeboxMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!; // _sin
    private AudioSystem _audioSystem;

    /// <summary>
    /// Are we currently 'playing' or paused for the play / pause button.
    /// </summary>
    private bool _playState;

    /// <summary>
    /// True if playing, false if paused.
    /// </summary>
    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action<ProtoId<JukeboxPrototype>>? OnSongSelected;
    public event Action<float>? SetTime;
    // _sin start
    public event Action<float>? SetVolume;
    public event Action<bool>? OnAutoplayChanged;
    public event Action<List<ProtoId<JukeboxPrototype>>>? OnQueueChanged;

    /// <summary>
    /// Sends the current queue to the server. Call this when a track is selected.
    /// </summary>
    public void SendQueueUpdate()
    {
        var queue = BuildQueue();
        OnQueueChanged?.Invoke(queue);
    }
    // _sin end

    private EntityUid? _audio;

    private float _lockTimer;

    // _sin start
    private readonly List<JukeboxPrototype> _allProtos = new();
    private readonly List<BoomboxGroupPrototype> _allGroups = new();
    private readonly HashSet<string> _favorites = new();
    private readonly HashSet<string> _pendingFavoritesRemoval = new();
    private string? _selectedTrackId;
    private BoomboxGroupPrototype? _currentGroup;

    private enum JukeboxTab { Main, Groups, Favorites }
    private JukeboxTab _activeTab = JukeboxTab.Main;
    // _sin end

    public JukeboxMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        // _sin start
        // Load favorites from CVar
        var saved = _cfg.GetCVar(Shared._sin.CCVar.SinCCVars.SinJukeboxFavorites);
        if (!string.IsNullOrWhiteSpace(saved))
        {
            foreach (var id in saved.Split(',', StringSplitOptions.RemoveEmptyEntries))
                _favorites.Add(id.Trim());
        }

        // Tab buttons
        var tabGroup = new ButtonGroup();
        MainTabButton.Group = tabGroup;
        GroupsTabButton.Group = tabGroup;
        FavoritesTabButton.Group = tabGroup;
        MainTabButton.Pressed = true;
        MainTabButton.OnPressed += _ => SwitchTab(JukeboxTab.Main);
        GroupsTabButton.OnPressed += _ => SwitchTab(JukeboxTab.Groups);
        FavoritesTabButton.OnPressed += _ => SwitchTab(JukeboxTab.Favorites);

        ToggleFavoriteButton.OnPressed += _ =>
        {
            if (_selectedTrackId != null)
                ToggleFavorite(_selectedTrackId);
        };
        // _sin end

        MusicList.OnItemSelected += args =>
        {
            var entry = MusicList[args.ItemIndex];

            if (entry.Metadata is not string juke)
                return;

            // _sin start
            _selectedTrackId = juke;
            UpdateToggleFavoriteButton(juke);
            // _sin end
            OnSongSelected?.Invoke(juke);
        };

        PlayButton.OnPressed += args =>
        {
            OnPlayPressed?.Invoke(!_playState);
        };

        StopButton.OnPressed += args =>
        {
            OnStopPressed?.Invoke();
        };
        PlaybackSlider.OnReleased += PlaybackSliderKeyUp;

        // _sin start
        VolumeSlider.MinValue = 0f;
        VolumeSlider.MaxValue = 200f;
        VolumeSlider.Value = 100f;
        VolumeLabel.Text = "100%";
        VolumeSlider.OnValueChanged += _ => VolumeLabel.Text = $"{(int)VolumeSlider.Value}%";
        VolumeSlider.OnReleased += _ => SetVolume?.Invoke(VolumeSlider.Value);

        AutoplayCheckBox.OnToggled += args =>
        {
            OnAutoplayChanged?.Invoke(args.Pressed);
            if (args.Pressed && _selectedTrackId != null)
            {
                SendQueueUpdate();
            }
        };

        SearchBar.OnTextChanged += _ => FilterMusic(SearchBar.Text);
        GroupSearchBar.OnTextChanged += _ => FilterGroups(GroupSearchBar.Text);
        FavoritesSearchBar.OnTextChanged += _ => FilterFavorites(FavoritesSearchBar.Text);

        FavoritesList.OnItemSelected += args =>
        {
            var entry = FavoritesList[args.ItemIndex];
            if (entry.Metadata is not string juke)
                return;
            _selectedTrackId = juke;
            UpdateToggleFavoriteButton(juke);
            OnSongSelected?.Invoke(juke);
        };

        RemoveFavoriteButton.OnPressed += _ =>
        {
            if (_selectedTrackId != null)
                ToggleFavorite(_selectedTrackId);
        };
        // _sin end

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio), force: true);
    }

    // _sin start
    private void SwitchTab(JukeboxTab tab)
    {
        _activeTab = tab;
        MainContainer.Visible = tab == JukeboxTab.Main;
        GroupsContainer.Visible = tab == JukeboxTab.Groups;
        FavoritesContainer.Visible = tab == JukeboxTab.Favorites;
        if (tab == JukeboxTab.Main)
        {
            _currentGroup = null;
            SearchBar.Text = string.Empty;
            FilterMusic(string.Empty);
        }
        if (tab == JukeboxTab.Favorites)
        {
            _pendingFavoritesRemoval.Clear();
            FilterFavorites(FavoritesSearchBar.Text);
        }
    }

    private void ToggleFavorite(string id)
    {
        if (!_favorites.Remove(id))
        {
            _favorites.Add(id);
            _pendingFavoritesRemoval.Remove(id);
        }
        else if (_activeTab == JukeboxTab.Favorites)
        {
            _pendingFavoritesRemoval.Add(id);
        }

        _cfg.SetCVar(Shared._sin.CCVar.SinCCVars.SinJukeboxFavorites, string.Join(",", _favorites));
        // Update only the star prefix of the affected item — avoids scroll reset from a full rebuild.
        RefreshFavoriteStarInList(MusicList, id);
        FilterFavorites(FavoritesSearchBar.Text);
        UpdateToggleFavoriteButton(id);
    }

    private void RefreshFavoriteStarInList(ItemList list, string id)
    {
        var isFav = _favorites.Contains(id);
        var entry = _allProtos.FirstOrDefault(p => p.ID == id);
        if (entry == null)
            return;

        for (var i = 0; i < list.Count; i++)
        {
            if (list[i].Metadata is string itemId && itemId == id)
            {
                list[i].Text = isFav ? $"\u2605 {entry.Name}" : entry.Name;
                break;
            }
        }
    }

    private void UpdateToggleFavoriteButton(string? id)
    {
        if (id == null)
        {
            ToggleFavoriteButton.Text = Loc.GetString("sin-jukebox-menu-button-favorite");
            return;
        }
        ToggleFavoriteButton.Text = _favorites.Contains(id)
            ? Loc.GetString("sin-jukebox-menu-button-unfavorite")
            : Loc.GetString("sin-jukebox-menu-button-favorite");
    }

    private void FilterFavorites(string query)
    {
        FavoritesList.Clear();

        foreach (var entry in _allProtos)
        {
            var isFavorite = _favorites.Contains(entry.ID);
            var isPending = _pendingFavoritesRemoval.Contains(entry.ID);

            if (!isFavorite && !isPending)
                continue;

            if (!string.IsNullOrEmpty(query) &&
                !entry.Name.Contains(query, StringComparison.OrdinalIgnoreCase) &&
                !entry.ID.Contains(query, StringComparison.OrdinalIgnoreCase) &&
                !entry.SearchTag.Any(tag => tag.Contains(query, StringComparison.OrdinalIgnoreCase)))
            {
                continue;
            }

            var label = isFavorite ? $"\u2605 {entry.Name}" : entry.Name;
            FavoritesList.AddItem(label, metadata: entry.ID);
        }
    }
    // _sin end

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
    }

    private void PlaybackSliderKeyUp(Slider args)
    {
        SetTime?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    // _sin start
    /// <summary>
    /// Re-populates the list of jukebox prototypes available.
    /// </summary>
    public void Populate(IEnumerable<JukeboxPrototype> jukeboxProtos)
    {
        _allProtos.Clear();
        _allProtos.AddRange(jukeboxProtos.OrderBy(p => p.Name));
        FilterMusic(SearchBar.Text);
    }

    /// <summary>
    /// Populates the Groups tab with group buttons.
    /// </summary>
    public void PopulateGroups(IEnumerable<BoomboxGroupPrototype> groups)
    {
        _allGroups.Clear();
        _allGroups.AddRange(groups.OrderBy(g => g.Name));
        FilterGroups(GroupSearchBar.Text);
    }

    private void FilterGroups(string query)
    {
        GroupsList.RemoveAllChildren();

        foreach (var group in _allGroups)
        {
            if (!string.IsNullOrEmpty(query) &&
                !group.Name.Contains(query, StringComparison.OrdinalIgnoreCase) &&
                !group.ID.Contains(query, StringComparison.OrdinalIgnoreCase) &&
                !group.GroupTag.Any(t => t.Contains(query, StringComparison.OrdinalIgnoreCase)))
            {
                continue;
            }

            var button = new Button
            {
                Text = group.Name,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2),
            };

            var capturedGroup = group;
            button.OnPressed += _ =>
            {
                _activeTab = JukeboxTab.Main;
                MainContainer.Visible = true;
                GroupsContainer.Visible = false;
                FavoritesContainer.Visible = false;
                MainTabButton.Pressed = false;
                GroupsTabButton.Pressed = false;
                FavoritesTabButton.Pressed = false;
                _currentGroup = capturedGroup;
                FilterMusicByGroup(capturedGroup);
            };

            GroupsList.AddChild(button);
        }
    }

    private void FilterMusicByGroup(BoomboxGroupPrototype group)
    {
        SearchBar.Text = string.Empty;
        MusicList.Clear();

        foreach (var entry in _allProtos)
        {
            var matches = group.GroupSearchTag.Any(gt =>
                entry.SearchTag.Any(st => st.Contains(gt, StringComparison.OrdinalIgnoreCase)) ||
                entry.Name.Contains(gt, StringComparison.OrdinalIgnoreCase));

            if (!matches)
                continue;

            var label = _favorites.Contains(entry.ID) ? $"\u2605 {entry.Name}" : entry.Name;
            MusicList.AddItem(label, metadata: entry.ID);
        }
    }
    // _sin end

    private void FilterMusic(string query)
    {
        MusicList.Clear();

        foreach (var entry in _allProtos)
        {
            // _sin start
            if (!string.IsNullOrEmpty(query) &&
                !entry.Name.Contains(query, StringComparison.OrdinalIgnoreCase) &&
                !entry.ID.Contains(query, StringComparison.OrdinalIgnoreCase) &&
                !entry.SearchTag.Any(tag => tag.Contains(query, StringComparison.OrdinalIgnoreCase)))
            {
                continue;
            }

            var label = _favorites.Contains(entry.ID)
                ? $"★ {entry.Name}"
                : entry.Name;
            MusicList.AddItem(label, metadata: entry.ID);
            // _sin end
        }
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;

        if (playing)
        {
            PlayButton.Text = Loc.GetString("jukebox-menu-buttonpause");
            return;
        }

        PlayButton.Text = Loc.GetString("jukebox-menu-buttonplay");
    }

    public void SetSelectedSong(string name, float length)
    {
        SetSelectedSongText(name);
        PlaybackSlider.MaxValue = length;
        PlaybackSlider.SetValueWithoutEvent(0);
    }

    // _sin start
    public void SetVolumeSliderValue(float volume)
    {
        VolumeSlider.SetValueWithoutEvent(volume);
        VolumeLabel.Text = $"{(int)volume}%";
    }

    public void SetAutoplayEnabled(bool enabled)
    {
        AutoplayCheckBox.Pressed = enabled;
    }

    public bool AutoplayEnabled => AutoplayCheckBox.Pressed;

    /// <summary>
    /// Builds the queue from the current filtered list, starting from the selected track,
    /// wrapping circularly and collecting only unique tracks (max 200).
    /// </summary>
    public List<ProtoId<JukeboxPrototype>> BuildQueue()
    {
        var tracks = GetCurrentFilteredTracks();
        var result = new List<ProtoId<JukeboxPrototype>>();

        if (tracks.Count == 0)
            return result;

        // Find index of selected track
        var startIndex = 0;
        if (_selectedTrackId != null)
        {
            var idx = tracks.FindIndex(t => t.ID == _selectedTrackId);
            if (idx >= 0)
                startIndex = idx;
        }

        // Collect unique tracks by wrapping circularly, up to 200 or all unique tracks
        var unique = new HashSet<string>();
        for (var i = 0; i < 200 && unique.Count < tracks.Count; i++)
        {
            var index = (startIndex + i) % tracks.Count;
            var id = tracks[index].ID;
            if (unique.Add(id))
                result.Add(id);
        }

        return result;
    }

    /// <summary>
    /// Gets the currently filtered track list based on active tab and search.
    /// </summary>
    private List<JukeboxPrototype> GetCurrentFilteredTracks()
    {
        if (_activeTab == JukeboxTab.Favorites)
        {
            // Favorites tab
            return _allProtos
                .Where(p => _favorites.Contains(p.ID))
                .ToList();
        }
        else if (_activeTab == JukeboxTab.Main && _currentGroup != null)
        {
            // Group view - filter by group tags
            return _allProtos
                .Where(p => _currentGroup.GroupSearchTag.Any(gt =>
                    p.SearchTag.Any(st => st.Contains(gt, StringComparison.OrdinalIgnoreCase)) ||
                    p.Name.Contains(gt, StringComparison.OrdinalIgnoreCase)))
                .ToList();
        }
        else
        {
            // Main tab - filter by search bar text
            var query = SearchBar.Text;
            if (string.IsNullOrEmpty(query))
            {
                return _allProtos.ToList();
            }

            return _allProtos
                .Where(p => p.Name.Contains(query, StringComparison.OrdinalIgnoreCase) ||
                            p.ID.Contains(query, StringComparison.OrdinalIgnoreCase) ||
                            p.SearchTag.Any(tag => tag.Contains(query, StringComparison.OrdinalIgnoreCase)))
                .ToList();
        }
    }
    // _sin end

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
        {
            _lockTimer -= args.DeltaSeconds;
        }

        PlaybackSlider.Disabled = _lockTimer > 0f;


        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            DurationLabel.Text = $@"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\:ss} / {_audioSystem.GetAudioLength(audio.FileName):mm\:ss}";
        }
        else
        {
            DurationLabel.Text = $"00:00 / 00:00";
        }

        if (PlaybackSlider.Grabbed)
            return;

        // _sin start
        // Ensure audio is resolved even when skipping slider update (needed for SetPlayPauseButton).
        if (audio == null)
            _entManager.TryGetComponent(_audio, out audio);

        // Don't update slider position while the lock timer is active — prevents visual bounce-back
        // while waiting for the server to confirm the new playback position.
        if (_lockTimer <= 0f)
        {
            PlaybackSlider.SetValueWithoutEvent(audio?.PlaybackPosition ?? 0f);
        }
        // _sin end

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));
    }

    public void SetSelectedSongText(string? text)
    {
        if (!string.IsNullOrEmpty(text))
        {
            SongName.Text = text;
        }
        else
        {
            SongName.Text = "---";
        }
    }
}
