using Content.Client.Markers;
using Content.Client.SubFloor;
using Content.Client.Stylesheets;
using Content.Shared.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.Debugging;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls; // KS14
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Sandbox.Windows;

[GenerateTypedNameReferences]
public sealed partial class SandboxWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entManager = null!;
    [Dependency] private IEyeManager _eyeManager = null!;
    [Dependency] private ILightManager _lightManager = null!;
    [Dependency] private IPlayerManager _playerManager = null!;
    private readonly DebugPhysicsSystem _debugPhysicsSystem;
    private readonly MarkerSystem _markerSystem;
    private readonly SubFloorHideSystem _subFloorSystem;

    public SandboxWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _debugPhysicsSystem = _entManager.System<DebugPhysicsSystem>();
        _markerSystem = _entManager.System<MarkerSystem>();
        _subFloorSystem = _entManager.System<SubFloorHideSystem>();
    }

    // KS14 start: DefaultWindow subscribes its close handler once in its constructor but drops it in
    // ExitedTree (RobustToolbox DefaultWindow.xaml.cs), and never re-subscribes. Every other window is
    // disposed and rebuilt on close, so the constructor re-wires it; this one is deliberately kept alive
    // and reused for the whole session by SandboxUIController.EnsureWindow, which also closes it once up
    // front to pre-centre it. That first close strips the handler permanently, leaving the X hoverable
    // but inert. Re-hook it on every entry into the tree until the engine makes this symmetric.
    protected override void EnteredTree()
    {
        base.EnteredTree();

        CloseButton.OnPressed -= OnCloseButtonPressed;
        CloseButton.OnPressed += OnCloseButtonPressed;
    }

    private void OnCloseButtonPressed(BaseButton.ButtonEventArgs args)
    {
        Close();
    }
    // KS14 end

    protected override void Opened()
    {
        base.Opened();

        ToggleSubfloorButton.Pressed = _subFloorSystem.ShowAll;
        ToggleLightButton.Pressed = !_lightManager.Enabled;
        ToggleFovButton.Pressed = !_eyeManager.CurrentEye.DrawFov;
        ToggleShadowsButton.Pressed = !_lightManager.DrawShadows;
        ShowMarkersButton.Pressed = _markerSystem.MarkersVisible;
        ShowBbButton.Pressed = (_debugPhysicsSystem.Flags & PhysicsDebugFlags.Shapes) != 0x0;
        AiOverlayButton.Pressed = _playerManager.LocalEntity is { } player && _entManager.HasComponent<StationAiOverlayComponent>(player);
    }
}
