using System.Globalization;
using Content.Shared._KS14.Medical.IvDrip;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._KS14.Medical.IvDrip;

[GenerateTypedNameReferences]
public sealed partial class IvDripWindow : FancyWindow
{
    public event Action<bool>? OnEnabledChanged;
    public event Action<FixedPoint2>? OnAmountChanged;
    public event Action<float>? OnIntervalChanged;

    public IvDripWindow()
    {
        RobustXamlLoader.Load(this);
        EnabledCheckBox.OnToggled += args => OnEnabledChanged?.Invoke(args.Pressed);
        AmountSlider.OnReleased += _ => OnAmountChanged?.Invoke(FixedPoint2.New(AmountSlider.Value));
        IntervalSlider.OnReleased += _ => OnIntervalChanged?.Invoke(IntervalSlider.Value);
        AmountInput.OnTextEntered += args => SubmitAmount(args.Text);
        AmountInput.OnFocusExit += args => SubmitAmount(args.Text);
        IntervalInput.OnTextEntered += args => SubmitInterval(args.Text);
        IntervalInput.OnFocusExit += args => SubmitInterval(args.Text);
    }

    public void UpdateState(IvDripBoundUserInterfaceState state)
    {
        VolumeLabel.Text = $"Contents: {state.SolutionVolume} / {state.SolutionMaxVolume} u";
        EnabledCheckBox.Pressed = state.InjectionEnabled;
        AmountSlider.Disabled = !state.CanSetInjectionAmount;
        AmountInput.Editable = state.CanSetInjectionAmount;
        AmountSlider.MinValue = (float)state.MinimumInjectionAmount;
        AmountSlider.MaxValue = (float)state.MaximumInjectionAmount;
        AmountSlider.SetValueWithoutEvent((float)state.InjectionAmount);
        AmountInput.Text = state.InjectionAmount.ToString();
        AmountLabel.Text = $"Amount: {state.InjectionAmount} u";
        IntervalSlider.Disabled = !state.CanSetInjectionInterval;
        IntervalInput.Editable = state.CanSetInjectionInterval;
        IntervalSlider.MinValue = state.MinimumInjectionInterval;
        IntervalSlider.MaxValue = state.MaximumInjectionInterval;
        IntervalSlider.SetValueWithoutEvent(state.InjectionInterval);
        IntervalInput.Text = state.InjectionInterval.ToString(CultureInfo.InvariantCulture);
        IntervalLabel.Text = $"Rate: {state.InjectionInterval:F1} s";
    }

    private void SubmitAmount(string text)
    {
        if (float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out var amount))
            OnAmountChanged?.Invoke(FixedPoint2.New(amount));
    }

    private void SubmitInterval(string text)
    {
        if (float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out var interval))
            OnIntervalChanged?.Invoke(interval);
    }
}