using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared._KS14.Medical.IvDrip;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._KS14.Medical.IvDrip;

/// <summary>
///     Lets the wearer of an IV drip start it, stop it, and set how much it pumps and how often.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class IvDripWindow : FancyWindow
{
    /// <summary>
    ///     Raised when the wearer ticks or unticks the enable box.
    /// </summary>
    public event Action<bool>? OnEnabledChanged;

    /// <summary>
    ///     Raised when the wearer picks a new dose, by slider or by text box.
    /// </summary>
    public event Action<FixedPoint2>? OnAmountChanged;

    /// <summary>
    ///     Raised when the wearer picks a new interval, by slider or by text box.
    /// </summary>
    public event Action<float>? OnIntervalChanged;

    /// <summary>
    ///     What the last state put in each text box.
    /// </summary>
    /// <remarks>
    ///     Focus-exit fires on every focus loss, including the one that follows the server clamping a
    ///         value and pushing the clamped text straight back here. Without remembering what was put
    ///         in the box, that echoes the value back to the server on the way out.
    /// </remarks>
    private string _lastAmountText = string.Empty;
    private string _lastIntervalText = string.Empty;

    public IvDripWindow()
    {
        RobustXamlLoader.Load(this);
        EnabledCheckBox.OnToggled += args => OnEnabledChanged?.Invoke(args.Pressed);
        AmountSlider.OnReleased += _ => OnAmountChanged?.Invoke(FixedPoint2.New(AmountSlider.Value));
        IntervalSlider.OnReleased += _ => OnIntervalChanged?.Invoke(NormalizeInterval(IntervalSlider.Value));
        AmountInput.OnTextEntered += args => SubmitAmount(args.Text);
        AmountInput.OnFocusExit += args => SubmitAmount(args.Text);
        IntervalInput.OnTextEntered += args => SubmitInterval(args.Text);
        IntervalInput.OnFocusExit += args => SubmitInterval(args.Text);
    }

    /// <summary>
    ///     Redraws the whole window from a server-pushed state.
    /// </summary>
    public void UpdateState(IvDripBoundUserInterfaceState state)
    {
        VolumeLabel.Text = Loc.GetString("iv-drip-window-contents",
            ("volume", state.SolutionVolume),
            ("maxVolume", state.SolutionMaxVolume));

        EnabledCheckBox.Pressed = state.InjectionEnabled;

        AmountSlider.Disabled = !state.CanSetInjectionAmount;
        AmountInput.Editable = state.CanSetInjectionAmount;
        AmountSlider.MinValue = (float)state.MinimumInjectionAmount;
        AmountSlider.MaxValue = (float)state.MaximumInjectionAmount;
        AmountSlider.SetValueWithoutEvent((float)state.InjectionAmount);
        _lastAmountText = ((float)state.InjectionAmount).ToString("F2", CultureInfo.InvariantCulture);
        AmountInput.Text = _lastAmountText;
        AmountLabel.Text = Loc.GetString("iv-drip-window-amount", ("amount", state.InjectionAmount));

        IntervalSlider.Disabled = !state.CanSetInjectionInterval;
        IntervalInput.Editable = state.CanSetInjectionInterval;
        IntervalSlider.MinValue = state.MinimumInjectionInterval;
        IntervalSlider.MaxValue = state.MaximumInjectionInterval;
        IntervalSlider.SetValueWithoutEvent(state.InjectionInterval);
        _lastIntervalText = state.InjectionInterval.ToString("F2", CultureInfo.InvariantCulture);
        IntervalInput.Text = _lastIntervalText;
        IntervalLabel.Text = Loc.GetString("iv-drip-window-rate", ("interval", _lastIntervalText));
    }

    private void SubmitAmount(string text)
    {
        if (text == _lastAmountText)
            return;

        if (float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out var amount))
            OnAmountChanged?.Invoke(FixedPoint2.New(amount));
    }

    private void SubmitInterval(string text)
    {
        if (text == _lastIntervalText)
            return;

        if (float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out var interval))
            OnIntervalChanged?.Invoke(NormalizeInterval(interval));
    }

    /// <summary>
    ///     Rounds an interval to the same two decimal places the server clamps it to, so that the value
    ///         sent up matches the one that comes back.
    /// </summary>
    private static float NormalizeInterval(float interval) =>
        (float)Math.Round(interval, 2, MidpointRounding.AwayFromZero);
}
