using Content.Client.UserInterface.Controls;
using Content.Shared._KS14.Language;
using Content.Shared._KS14.Language.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._KS14.Language;

[GenerateTypedNameReferences]
public sealed partial class KsLanguageMenuWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPlayerManager _player = default!;

    private KsLanguageSystem? _system;

    public KsLanguageMenuWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (_entMan.TrySystem<KsLanguageSystem>(out var system))
            _system = system;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        if (_system != null)
            _system.LanguagesUpdated += Refresh;
        Refresh();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        if (_system != null)
            _system.LanguagesUpdated -= Refresh;
    }

    private void Refresh()
    {
        LanguageList.RemoveAllChildren();

        if (_player.LocalEntity is not { } player)
            return;

        // A player without the component implicitly speaks the station default only.
        if (!_entMan.TryGetComponent<KsLanguageSpeakerComponent>(player, out var speaker))
        {
            LanguageList.AddChild(new Label
            {
                Text = Loc.GetString("ks-language-menu-default-only"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 12),
            });
            return;
        }

        foreach (var lang in speaker.Spoken)
        {
            AddLanguageCard(lang, speaker, spoken: true);
        }

        var understoodHeaderAdded = false;
        foreach (var lang in speaker.Understood)
        {
            if (speaker.Spoken.Contains(lang))
                continue;

            if (!understoodHeaderAdded)
            {
                understoodHeaderAdded = true;
                LanguageList.AddChild(new Label
                {
                    Text = Loc.GetString("ks-language-menu-understood-header"),
                    StyleClasses = { "LabelSubText" },
                    Margin = new Thickness(0, 8, 0, 0),
                });
            }

            AddLanguageCard(lang, speaker, spoken: false);
        }
    }

    private void AddLanguageCard(ProtoId<KsLanguagePrototype> langId, KsLanguageSpeakerComponent speaker, bool spoken)
    {
        if (!_prototypes.TryIndex(langId, out var proto))
            return;

        var card = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(30, 30, 34) },
            HorizontalExpand = true,
        };

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(8, 6),
            HorizontalExpand = true,
        };
        card.AddChild(content);

        var headerRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };
        content.AddChild(headerRow);

        // Same markup tags chat uses, so the card previews the language's chat look.
        var name = new FormattedMessage();
        if (proto.FontId is { } fontId)
            name.PushTag(new MarkupNode("font", new MarkupParameter(fontId), null));
        if (proto.Color is { } color)
            name.PushColor(color);
        name.AddText(proto.LocalizedName);

        var nameLabel = new RichTextLabel
        {
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        // tagsAllowed null lifts the DefaultTags filter, which would drop the font node.
        nameLabel.SetMessage(name, tagsAllowed: null);
        headerRow.AddChild(nameLabel);

        if (spoken)
        {
            var current = speaker.CurrentLanguage == langId;
            var choose = new Button
            {
                Text = Loc.GetString(current ? "ks-language-menu-current" : "ks-language-menu-choose"),
                Disabled = current,
            };
            var chosen = langId;
            choose.OnPressed += _ => _system?.RequestSetLanguage(chosen);
            headerRow.AddChild(choose);
        }

        var description = new RichTextLabel
        {
            HorizontalExpand = true,
        };
        description.SetMessage(proto.LocalizedDescription);
        content.AddChild(description);

        LanguageList.AddChild(card);
    }
}
