- components:
  - type: EmitSoundOnPickup
    sound:
      path: /Audio/_KS14/Handling/component_pickup.ogg
  - type: EmitSoundOnDrop
    sound:
      path: /Audio/_KS14/Handling/component_drop.ogg
  type: !PartialOnly entity
  id: AccessConfigurator
- components:
  - accessLevels: !Remove
    - Armory
    - Atmospherics
    - Bar
    - BasicSilicon
    - Borg
    - Brig
    - Detective
    - Captain
    - Cargo
    - Chapel
    - Chemistry
    - ChiefEngineer
    - ChiefMedicalOfficer
    - Command
    - Cryogenics
    - EmergencyShuttleRepealAll
    - Engineering
    - External
    - HeadOfPersonnel
    - HeadOfSecurity
    - Hydroponics
    - Janitor
    - Kitchen
    - Lawyer
    - Maintenance
    - Medical
    - Quartermaster
    - Research
    - ResearchDirector
    - Salvage
    - Security
    - Service
    - StationAi
    - Theatre
    - CentralCommand
    - NuclearOperative
    - SyndicateAgent
    - Wizard
    - Xenoborg
    - Bluelab
    - GenpopEnter
    - GenpopLeave
    type: AccessOverrider
  type: !PartialOnly entity
  id: AccessConfiguratorUniversal
...
