name: Build & Test Map Renderer

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master, staging, stable ]

jobs:
  build:
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Master
        uses: actions/checkout@v7

      # KS14 Start
      # If we have the secret repo PAT, use it to init submodules. Otherwise don't; it's not available in PRs from forks
      - name: Init submodules (conditional)
        shell: bash
        env:
          HAS_TOKEN: ${{ secrets.SECREPO_PAT != '' }}
        run: |
          set -e

          if [ "$HAS_TOKEN" = "true" ]; then
            echo "Token present → injecting auth for submodules"

            git config --global url."https://x-access-token:${{ secrets.SECREPO_PAT }}@github.com/".insteadOf "https://github.com/"

            git submodule sync --recursive
            git submodule update --init --recursive
          else
            echo "No token → only RobustToolbox"

            git submodule sync RobustToolbox
            git submodule update --init RobustToolbox
          fi
      # KS14 End

      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5

      - name: Update Engine Submodules
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build Content.MapRenderer --configuration Release --no-restore /m

      - name: Run Map Renderer
        run: dotnet run --project Content.MapRenderer Dev

  ci-success:
    name: Build & Test Debug
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
