name: RSI Validator

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    paths:
      - '**.rsi/**'

jobs:
  validate_rsis:
    name: Validate RSIs
    runs-on: ubuntu-latest
    permissions: # KS14
      contents: read
    steps:
      - uses: actions/checkout@v4.2.2

      # KS14 Start
      # If we have the secret repo PAT, use it to init submodules. Otherwise don't; it's not available in PRs from forks
      - name: Init submodules (conditional)
        shell: bash
        env:
          HAS_TOKEN: ${{ secrets.SECREPO_PAT != '' }}
        run: |
          set -e

          if [ "$HAS_TOKEN" = "true" ]; then
            echo "Token present → injecting auth for submodules"

            git config --global url."https://x-access-token:${{ secrets.SECREPO_PAT }}@github.com/".insteadOf "https://github.com/"

            git submodule sync --recursive
            git submodule update --init --recursive
          else
            echo "No token → only RobustToolbox"

            git submodule sync RobustToolbox
            git submodule update --init RobustToolbox
          fi
      # KS14 End

      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Install Python dependencies
        run: |
          pip3 install --ignore-installed --user pillow jsonschema
      - name: Validate RSIs
        run: |
          python3 RobustToolbox/Schemas/validate_rsis.py Resources/
