name: YAML Linter (No Secrets)

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: YAML Linter
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # If we have the secret repo PAT, don't do anything and only init RT. Otherwise quit early; there's no point testing `nosecret` now because we can't; the other workflow for builds will do it instead.
      ### Not done recursively (for no-token run because we update submodules in a later step
      - name: Init submodules (conditional)
        shell: bash
        env:
          HAS_TOKEN: ${{ secrets.SECREPO_PAT != '' }}
        run: |
          set -e

          if [ "$HAS_TOKEN" = "true" ]; then
            echo "Token present → only initing RT"

            git config --global url."https://x-access-token:${{ secrets.SECREPO_PAT }}@github.com/".insteadOf "https://github.com/"

            git submodule sync RobustToolbox
            git submodule update --init RobustToolbox

            echo "EXIT_EARLY=false" >> $GITHUB_ENV
          else
            echo "No token → quit early to let other workflow handle it"
            echo "EXIT_EARLY=true" >> $GITHUB_ENV
          fi

      - name: Cancel early if condition met
        if: ${{ env.EXIT_EARLY == 'true' }}
        uses: space-klovns/cancel-action@v0.0  # Cancels the run gracefully
      # KS14 End

      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Update Engine Submodules
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:WarningsAsErrors= /m
      - name: Run Linter
        run: dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
