name: YAML Linter

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: YAML Linter
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # KS14 Start
      - name: Init submodules (conditional)
        shell: bash
        env:
          HAS_TOKEN: ${{ secrets.SECREPO_PAT != '' }}
        run: |
          set -e

          if [ "$HAS_TOKEN" = "true" ]; then
            echo "Token present → full recursive submodule update"

            git submodule sync --recursive
            git submodule update --init --recursive
          else
            echo "No token → only updating RobustToolbox"

            git submodule sync RobustToolbox
            git submodule update --init RobustToolbox
          fi
      # KS14 End

      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Update Engine Submodules
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:WarningsAsErrors= /m
      - name: Run Linter
        run: dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
